// Ícones personalizados da Arena dos Heróis (desenhados no Canva, em /public/arena/icones). `AT` troca os emojis
// de um texto por eles; `AIcon` mostra um ícone pelo nome.
import { createIconText, type IconMap } from "@/components/ui/IconText";

export const ARENA_ICONS: IconMap = {
  "🏆": "trofeu",
  "⚔": "espadas",
  "👑": "coroa",
  "♛": "coroa",
  "✨": "brilhos",
  "💫": "brilhos",
  "👥": "dupla",
  "🔒": "cadeado",
  "🔓": "cadeado-aberto",
  "🤝": "aperto-de-mao",
  "✅": "certo",
  "✔": "certo",
  "😅": "derrota",
  "🏰": "castelo",
  "⚠": "alerta",
  "🏅": "medalha",
  "🥇": "ouro",
  "🥈": "prata",
  "🥉": "bronze",
  "🔥": "fogo",
  "🎉": "festa",
  "🛡": "escudo",
  "🎁": "presente",
  "📖": "livro",
  "♪": "nota",
  "♫": "nota",
  "♬": "nota",
  "♩": "nota",
  "🎵": "nota",
  "🎶": "nota",
  "🍞": "pao",
  "🎯": "alvo",
  "⭐": "estrela",
  "★": "estrela",
  "⬆": "seta-cima",
  "💍": "anel",
  "💙": "coracao-azul",
  "🪨": "pedra",
  "🏺": "vaso",
  "❔": "interrogacao",
  "❓": "interrogacao",
  "🌊": "onda",
  "⛪": "igreja",
  "🕊": "pomba",
  "🪖": "capacete-militar",
  "🌿": "folha",
  "🍃": "folha",
  "🎸": "guitarra",
  "🎮": "controle",
  "📡": "antena",
  "🍎": "maca",
  "☄": "cometa",
  "📯": "trombeta",
  "🎺": "trombeta",
  "🏋": "forca",
  "💪": "forca",
  "⚪": "circulo",
  "📜": "pergaminho",
  "🧰": "bau",
  "🗼": "torre",
  "🔇": "mudo",
  "🔊": "som",
  "✕": "x",
  "✖": "x",
  "⚡": "raio",
  "🐢": "tartaruga",
  "📚": "livros",
  "💧": "gota",
  "🏹": "arco",
  "💥": "explosao",
  "👟": "bota",
  "📊": "grafico",
  "📣": "megafone",
  "❤": "coracao",
  "🌳": "arvore",
  "⛰": "montanha",
  "🏜": "deserto",
  "⛵": "barco",
  "🕍": "templo",
  "🏛": "templo",
  "🐿": "esquilo",
  "🧢": "bone",
  "😴": "sono",
  "🌙": "lua",
  "🌾": "trigo",
  "🦁": "leao",
  "🐑": "ovelha",
  "🛶": "canoa",
  "🌸": "flor",
  "🌹": "flor",
  "🦋": "borboleta",
  "☕": "cafe",
  "🥐": "croissant",
  "📐": "esquadro",
  "📦": "caixa",
  "🆚": "espadas",
  "⏳": "ampulheta",
  "⏱": "cronometro",
  "👆": "dedo",
  "🚪": "porta",
  "🟢": "orbe-verde",
  "🟡": "orbe-amarelo",
  "🔴": "orbe-vermelho",
  "⭕": "orbe-vermelho",
  "💚": "coracao-verde",
  "🤍": "coracao-branco",
  "➕": "mais",
  "🃏": "carta",
  "▶": "play",
  "←": "voltar",
  "⬇": "seta-baixo",
  "●": "orbe-verde",
  "○": "orbe-cinza",
};

const arena = createIconText("/arena/icones", ARENA_ICONS);
/** Texto com os emojis trocados pelos ícones da Arena. */
export const AT = arena.IconText;
/** Um ícone da Arena pelo nome (arquivo em public/arena/icones). */
export const AIcon = arena.Icon;
