// Conteúdo dos jogos bíblicos. Só roda no servidor: as respostas certas nunca
// vão para o navegador antes de o jogador responder (ver engine.ts).
// Textos de versículos seguem a Almeida Revista e Atualizada (ARA).

export type QuizItem = { q: string; a: string; w: [string, string, string]; ref: string };

export const QUIZ: QuizItem[] = [
  { q: "Quem construiu a arca para sobreviver ao dilúvio?", a: "Noé", w: ["Abraão", "Moisés", "Davi"], ref: "Gênesis 6–7" },
  { q: "Quantos dias Jesus ficou no deserto sendo tentado?", a: "40", w: ["7", "12", "3"], ref: "Mateus 4:2" },
  { q: "Quem foi lançado na cova dos leões?", a: "Daniel", w: ["José", "Jonas", "Elias"], ref: "Daniel 6" },
  { q: "Qual é o primeiro livro da Bíblia?", a: "Gênesis", w: ["Êxodo", "Salmos", "Mateus"], ref: "Gênesis 1:1" },
  { q: "Quem derrotou o gigante Golias?", a: "Davi", w: ["Saul", "Jônatas", "Sansão"], ref: "1 Samuel 17" },
  { q: "Quantos apóstolos Jesus escolheu?", a: "12", w: ["7", "10", "70"], ref: "Lucas 6:13" },
  { q: "Em que cidade Jesus nasceu?", a: "Belém", w: ["Nazaré", "Jerusalém", "Cafarnaum"], ref: "Mateus 2:1" },
  { q: "Quem negou Jesus três vezes antes de o galo cantar?", a: "Pedro", w: ["João", "Tomé", "Judas"], ref: "Mateus 26:34" },
  { q: "Qual profeta foi engolido por um grande peixe?", a: "Jonas", w: ["Elias", "Eliseu", "Oseias"], ref: "Jonas 1:17" },
  { q: "Quem recebeu os Dez Mandamentos no monte Sinai?", a: "Moisés", w: ["Josué", "Arão", "Calebe"], ref: "Êxodo 20" },
  { q: "Qual foi o primeiro milagre de Jesus, nas bodas de Caná?", a: "Transformou água em vinho", w: ["Curou um cego", "Multiplicou os pães", "Andou sobre as águas"], ref: "João 2:1-11" },
  { q: "Quantos livros tem a Bíblia protestante?", a: "66", w: ["73", "39", "27"], ref: "Antigo (39) + Novo Testamento (27)" },
  { q: "Quem era a mãe do profeta Samuel?", a: "Ana", w: ["Sara", "Rebeca", "Raquel"], ref: "1 Samuel 1" },
  { q: "Quem vendeu o direito de filho mais velho por um prato de lentilhas?", a: "Esaú", w: ["Jacó", "Isaque", "Ismael"], ref: "Gênesis 25:34" },
  { q: "Quem foi vendido pelos irmãos e depois governou o Egito?", a: "José", w: ["Benjamim", "Judá", "Rúben"], ref: "Gênesis 37–41" },
  { q: "Em que monte Elias desafiou os profetas de Baal?", a: "Carmelo", w: ["Sinai", "Sião", "Horebe"], ref: "1 Reis 18" },
  { q: "Qual rei de Israel ficou famoso pela sabedoria?", a: "Salomão", w: ["Davi", "Saul", "Ezequias"], ref: "1 Reis 3" },
  { q: "Quem escreveu a maior parte dos Salmos?", a: "Davi", w: ["Salomão", "Moisés", "Josué"], ref: "Livro dos Salmos" },
  { q: "Qual apóstolo era cobrador de impostos antes de seguir Jesus?", a: "Mateus", w: ["Pedro", "André", "Filipe"], ref: "Mateus 9:9" },
  { q: "Qual apóstolo duvidou da ressurreição até ver as marcas de Jesus?", a: "Tomé", w: ["Pedro", "Tiago", "Natanael"], ref: "João 20:24-29" },
  { q: "Qual é o último livro da Bíblia?", a: "Apocalipse", w: ["Judas", "Malaquias", "Atos"], ref: "Apocalipse 22" },
  { q: "Quem ajudou Jesus a carregar a cruz?", a: "Simão de Cirene", w: ["José de Arimateia", "Nicodemos", "Barrabás"], ref: "Mateus 27:32" },
  { q: "Em que dia, depois da crucificação, Jesus ressuscitou?", a: "No terceiro dia", w: ["No sétimo dia", "No primeiro dia", "No quadragésimo dia"], ref: "Lucas 24:7" },
  { q: "Quem escondeu os espias de Israel em Jericó?", a: "Raabe", w: ["Rute", "Ester", "Débora"], ref: "Josué 2" },
  { q: "Qual jovem judia se tornou rainha da Pérsia e salvou seu povo?", a: "Ester", w: ["Rute", "Débora", "Miriã"], ref: "Livro de Ester" },
  { q: "Rute foi nora de quem?", a: "Noemi", w: ["Ana", "Sara", "Miriã"], ref: "Rute 1" },
  { q: "Quem foi o primeiro homem criado por Deus?", a: "Adão", w: ["Abel", "Sete", "Noé"], ref: "Gênesis 2:7" },
  { q: "Quem matou Abel, seu irmão?", a: "Caim", w: ["Sete", "Lameque", "Enoque"], ref: "Gênesis 4:8" },
  { q: "Quantas pragas Deus enviou sobre o Egito?", a: "10", w: ["7", "12", "3"], ref: "Êxodo 7–12" },
  { q: "Qual mar se abriu para o povo de Israel atravessar?", a: "Mar Vermelho", w: ["Mar Morto", "Mar da Galileia", "Mar Mediterrâneo"], ref: "Êxodo 14" },
  { q: "Quem era o pai de João Batista?", a: "Zacarias", w: ["José", "Simeão", "Eli"], ref: "Lucas 1:13" },
  { q: "Quem foi chamado de apóstolo dos gentios?", a: "Paulo", w: ["Pedro", "Barnabé", "Timóteo"], ref: "Romanos 11:13" },
  { q: "Qual era o nome de Paulo antes da conversão?", a: "Saulo", w: ["Silas", "Estêvão", "Barnabé"], ref: "Atos 9:1-4" },
  { q: "Quem batizou Jesus?", a: "João Batista", w: ["Pedro", "Tiago", "Filipe"], ref: "Mateus 3:13-17" },
  { q: "Em que rio Jesus foi batizado?", a: "Jordão", w: ["Nilo", "Eufrates", "Tigre"], ref: "Mateus 3:13" },
  { q: "Quem perdeu a força quando teve o cabelo cortado?", a: "Sansão", w: ["Golias", "Gideão", "Jefté"], ref: "Juízes 16" },
  { q: "Qual juiz derrotou os midianitas com apenas 300 homens?", a: "Gideão", w: ["Sansão", "Samuel", "Josué"], ref: "Juízes 7" },
  { q: "Quem liderou o povo de Israel depois de Moisés?", a: "Josué", w: ["Calebe", "Arão", "Samuel"], ref: "Josué 1" },
  { q: "Qual cidade teve os muros derrubados depois de o povo marchar ao redor dela?", a: "Jericó", w: ["Jerusalém", "Babilônia", "Nínive"], ref: "Josué 6" },
  { q: "Cerca de quantos homens Jesus alimentou com 5 pães e 2 peixes (sem contar mulheres e crianças)?", a: "5 mil", w: ["500", "12 mil", "100"], ref: "Mateus 14:21" },
  { q: "Quem escreveu o livro de Apocalipse?", a: "João", w: ["Paulo", "Pedro", "Lucas"], ref: "Apocalipse 1:1" },
  { q: "Qual livro vem logo depois de Gênesis?", a: "Êxodo", w: ["Levítico", "Números", "Josué"], ref: "Êxodo 1:1" },
  { q: "Qual oração Jesus ensinou aos discípulos?", a: "Pai Nosso", w: ["Salmo 23", "Oração de Jabez", "Cântico de Maria"], ref: "Mateus 6:9-13" },
  { q: "Quem sonhou com uma escada que ligava a terra ao céu?", a: "Jacó", w: ["Abraão", "José", "Daniel"], ref: "Gênesis 28:12" },
  { q: "Quem recebeu de Deus a promessa de ser pai de uma grande nação?", a: "Abraão", w: ["Isaque", "Jacó", "Ló"], ref: "Gênesis 12:1-2" },
  { q: "Quem era o grande amigo de Davi, filho do rei Saul?", a: "Jônatas", w: ["Abner", "Joabe", "Absalão"], ref: "1 Samuel 18:1" },
  { q: "Qual profeta foi levado ao céu num redemoinho sem passar pela morte?", a: "Elias", w: ["Moisés", "Eliseu", "Isaías"], ref: "2 Reis 2:11" },
  { q: "Quem interpretou os sonhos do faraó do Egito?", a: "José", w: ["Daniel", "Moisés", "Arão"], ref: "Gênesis 41" },
  { q: "Qual fariseu visitou Jesus de noite?", a: "Nicodemos", w: ["Zaqueu", "Lázaro", "Bartimeu"], ref: "João 3:1-2" },
  { q: "Quem subiu numa árvore para conseguir ver Jesus passar?", a: "Zaqueu", w: ["Bartimeu", "Lázaro", "Mateus"], ref: "Lucas 19:1-4" },
  { q: "Quem Jesus ressuscitou depois de quatro dias no túmulo?", a: "Lázaro", w: ["Dorcas", "Êutico", "Jairo"], ref: "João 11" },
  { q: "Qual é o maior mandamento, segundo Jesus?", a: "Amar a Deus sobre todas as coisas", w: ["Guardar o sábado", "Honrar pai e mãe", "Não matar"], ref: "Mateus 22:37-38" },
  { q: "Em que dia da criação Deus descansou?", a: "No sétimo", w: ["No sexto", "No primeiro", "No terceiro"], ref: "Gênesis 2:2" },
  { q: "Qual foi a primeira praga do Egito?", a: "Água transformada em sangue", w: ["Rãs", "Gafanhotos", "Trevas"], ref: "Êxodo 7:20" },
  { q: "Qual profeta ungiu Davi como rei?", a: "Samuel", w: ["Natã", "Elias", "Isaías"], ref: "1 Samuel 16:13" },
  { q: "Quem escreveu o livro de Atos dos Apóstolos?", a: "Lucas", w: ["Marcos", "João", "Paulo"], ref: "Atos 1:1" },
  { q: "Quantos anos o povo de Israel andou pelo deserto?", a: "40", w: ["7", "70", "12"], ref: "Números 14:33" },
];

export type VerseItem = { ref: string; before: string; after: string; a: string; w: [string, string, string] };

export const VERSES: VerseItem[] = [
  { ref: "João 3:16", before: "Porque Deus", after: "ao mundo de tal maneira que deu o seu Filho unigênito, para que todo o que nele crê não pereça, mas tenha a vida eterna.", a: "amou", w: ["temeu", "chamou", "criou"] },
  { ref: "Salmos 23:1", before: "O Senhor é o meu", after: "; nada me faltará.", a: "pastor", w: ["rei", "refúgio", "escudo"] },
  { ref: "Filipenses 4:13", before: "Posso todas as coisas naquele que me", after: ".", a: "fortalece", w: ["ensina", "guia", "ama"] },
  { ref: "Provérbios 3:5", before: "Confia no Senhor de todo o teu", after: "e não te estribes no teu próprio entendimento.", a: "coração", w: ["tempo", "pensamento", "caminho"] },
  { ref: "Josué 1:9", before: "Não to mandei eu? Sê forte e", after: "; não temas, nem te espantes, porque o Senhor, teu Deus, é contigo por onde quer que andares.", a: "corajoso", w: ["sábio", "paciente", "humilde"] },
  { ref: "Romanos 8:28", before: "Sabemos que todas as coisas cooperam para o", after: "daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.", a: "bem", w: ["mal", "tempo", "caminho"] },
  { ref: "Isaías 41:10", before: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te", after: ", e te sustento com a destra da minha justiça.", a: "ajudo", w: ["guardo", "visito", "consolo"] },
  { ref: "Mateus 11:28", before: "Vinde a mim, todos os que estais cansados e sobrecarregados, e eu vos", after: ".", a: "aliviarei", w: ["ensinarei", "guardarei", "curarei"] },
  { ref: "Salmos 119:105", before: "", after: "para os meus pés é a tua palavra e luz para o meu caminho.", a: "Lâmpada", w: ["Espada", "Escudo", "Cajado"] },
  { ref: "1 Timóteo 4:12", before: "Ninguém despreze a tua", after: "; mas sê padrão dos fiéis, na palavra, no procedimento, no amor, no espírito, na fé, na pureza.", a: "mocidade", w: ["pobreza", "coragem", "presença"] },
  { ref: "Jeremias 29:11", before: "Porque eu bem sei os pensamentos que tenho a vosso respeito, diz o Senhor; pensamentos de", after: "e não de mal, para vos dar o fim que esperais.", a: "paz", w: ["guerra", "glória", "poder"] },
  { ref: "Salmos 46:1", before: "Deus é o nosso", after: "e fortaleza, socorro bem presente na angústia.", a: "refúgio", w: ["pastor", "escudo", "rei"] },
  { ref: "Mateus 6:33", before: "Buscai, pois, em primeiro lugar, o seu", after: "e a sua justiça, e todas estas coisas vos serão acrescentadas.", a: "reino", w: ["templo", "povo", "caminho"] },
  { ref: "Salmos 119:11", before: "Guardo no", after: "as tuas palavras, para não pecar contra ti.", a: "coração", w: ["livro", "altar", "caderno"] },
  { ref: "1 Coríntios 13:13", before: "Agora, pois, permanecem a fé, a esperança, o amor, estes três, mas o", after: "destes é o amor.", a: "maior", w: ["menor", "primeiro", "último"] },
  { ref: "Mateus 28:20", before: "E eis que estou", after: "todos os dias até à consumação do século.", a: "convosco", w: ["diante", "longe", "atrás"] },
  { ref: "Salmos 27:1", before: "O Senhor é a minha", after: "e a minha salvação; de quem terei temor?", a: "luz", w: ["voz", "sombra", "paz"] },
  { ref: "Provérbios 22:6", before: "Ensina a criança no", after: "em que deve andar, e, ainda quando for velho, não se desviará dele.", a: "caminho", w: ["tempo", "livro", "lar"] },
  { ref: "Eclesiastes 3:1", before: "Para tudo há uma", after: ", e tempo para cada propósito debaixo do céu.", a: "ocasião", w: ["pressa", "festa", "palavra"] },
  { ref: "Tiago 4:7", before: "Sujeitai-vos, pois, a Deus; resisti ao diabo, e ele", after: "de vós.", a: "fugirá", w: ["dormirá", "voltará", "falará"] },
  { ref: "Hebreus 11:1", before: "Ora, a fé é a", after: "de coisas que se esperam, a convicção de fatos que se não veem.", a: "certeza", w: ["dúvida", "história", "lembrança"] },
];

export type WhoItem = { key: string; name: string; hints: [string, string, string, string]; ref: string };

export const WHO: WhoItem[] = [
  { key: "noe", name: "Noé", ref: "Gênesis 6–9", hints: ["Zombavam de mim por construir algo enorme em terra seca.", "Levei minha família e muitos animais para dentro do que construí.", "Choveu quarenta dias e quarenta noites.", "Uma pomba voltou com um ramo de oliveira."] },
  { key: "moises", name: "Moisés", ref: "Êxodo 2–20", hints: ["Fui salvo de um rio ainda bebê, dentro de um cesto.", "Cresci na casa do faraó, mas fugi para Midiã.", "Deus falou comigo numa sarça que queimava sem se consumir.", "Abri o Mar Vermelho e recebi os Dez Mandamentos."] },
  { key: "davi", name: "Davi", ref: "1 Samuel 16–17", hints: ["Eu era o mais novo dos irmãos e cuidava de ovelhas.", "Tocava harpa e escrevi muitos Salmos.", "Fui ungido rei por Samuel ainda jovem.", "Derrubei um gigante com uma pedra e uma funda."] },
  { key: "daniel", name: "Daniel", ref: "Daniel 1–6", hints: ["Fui levado para a Babilônia ainda jovem.", "Recusei a comida do rei para me manter fiel a Deus.", "Eu interpretava sonhos de reis.", "Passei uma noite numa cova de leões e nada me aconteceu."] },
  { key: "jose", name: "José do Egito", ref: "Gênesis 37–50", hints: ["Meu pai me deu uma túnica colorida.", "Meus irmãos me venderam por inveja.", "Fui parar no Egito e acabei preso sem culpa.", "Interpretei os sonhos do faraó e virei governador."] },
  { key: "ester", name: "Ester", ref: "Livro de Ester", hints: ["Fui criada pelo meu primo Mardoqueu.", "Fui escolhida entre muitas jovens para ser rainha.", "No começo, escondi que era judia.", "Arrisquei minha vida diante do rei para salvar o meu povo."] },
  { key: "jonas", name: "Jonas", ref: "Livro de Jonas", hints: ["Deus mandou eu ir a Nínive, mas fui para o lado contrário.", "Peguei um barco e veio uma grande tempestade.", "Fui jogado ao mar.", "Passei três dias dentro de um grande peixe."] },
  { key: "pedro", name: "Pedro", ref: "Mateus 4 e 26", hints: ["Eu era pescador na Galileia.", "Jesus me chamou dizendo que eu seria pescador de homens.", "Andei sobre as águas por alguns passos até duvidar.", "Neguei Jesus três vezes antes de o galo cantar."] },
  { key: "paulo", name: "Paulo", ref: "Atos 9", hints: ["No começo, eu perseguia os cristãos.", "Uma luz forte me parou no caminho para Damasco.", "Fiquei cego por três dias até Ananias orar por mim.", "Escrevi cartas do Novo Testamento, como Romanos e Gálatas."] },
  { key: "rute", name: "Rute", ref: "Livro de Rute", hints: ["Nasci em Moabe, não em Israel.", "Fiquei viúva muito jovem.", "Disse à minha sogra: o teu povo será o meu povo.", "Casei com Boaz e fui bisavó do rei Davi."] },
  { key: "salomao", name: "Salomão", ref: "1 Reis 3–6", hints: ["Meu pai foi rei antes de mim.", "Deus perguntou o que eu queria, e eu pedi sabedoria.", "Julguei o caso de duas mulheres que disputavam um bebê.", "Construí o templo em Jerusalém."] },
  { key: "sansao", name: "Sansão", ref: "Juízes 13–16", hints: ["Antes de nascer, um anjo anunciou que eu seria separado para Deus.", "Minha força estava ligada ao cabelo, que nunca foi cortado.", "Matei um leão com as mãos nuas.", "Derrubei as colunas do templo dos filisteus."] },
  { key: "elias", name: "Elias", ref: "1 Reis 17–18; 2 Reis 2", hints: ["Fui profeta no tempo do rei Acabe.", "Corvos me traziam comida junto a um ribeiro.", "Desafiei os profetas de Baal no monte Carmelo.", "Fui levado ao céu num redemoinho, sem morrer."] },
  { key: "abraao", name: "Abraão", ref: "Gênesis 12–22", hints: ["Deus me mandou sair da minha terra sem dizer o destino.", "Prometeu que meus descendentes seriam como as estrelas.", "Minha esposa Sara teve um filho já idosa.", "Quase ofereci meu filho Isaque, mas Deus providenciou um carneiro."] },
  { key: "zaqueu", name: "Zaqueu", ref: "Lucas 19:1-10", hints: ["Eu era muito baixinho.", "Trabalhava cobrando impostos e era mal visto.", "Subi numa árvore para ver Jesus passar.", "Jesus foi à minha casa, e eu devolvi o que tinha tomado."] },
  { key: "debora", name: "Débora", ref: "Juízes 4–5", hints: ["Fui juíza e profetisa de Israel.", "Julgava o povo sentada debaixo de uma palmeira.", "Chamei Baraque para liderar o exército.", "Cantei uma canção de vitória depois de derrotarmos Sísera."] },
];

export type OrderSet = { title: string; events: [string, string, string, string]; ref: string };

// "events" já está na ordem cronológica correta.
export const ORDER: OrderSet[] = [
  { title: "Do começo de tudo", events: ["Criação do mundo", "Adão e Eva comem do fruto proibido", "O dilúvio", "A torre de Babel"], ref: "Gênesis 1–11" },
  { title: "Os patriarcas", events: ["Deus chama Abraão", "Nasce Isaque", "José é vendido ao Egito", "O povo sai do Egito"], ref: "Gênesis 12 – Êxodo 12" },
  { title: "Liberdade e deserto", events: ["O povo sai do Egito", "Os Dez Mandamentos", "Os muros de Jericó caem", "Davi vira rei"], ref: "Êxodo – 2 Samuel" },
  { title: "Reis e exílio", events: ["Davi vence Golias", "Salomão constrói o templo", "O exílio na Babilônia", "Neemias reconstrói os muros"], ref: "1 Samuel – Neemias" },
  { title: "O ministério de Jesus", events: ["Jesus é batizado", "O Sermão do Monte", "A Última Ceia", "A ressurreição"], ref: "Evangelhos" },
  { title: "A igreja nasce", events: ["A ressurreição", "A ascensão", "Pentecostes", "A conversão de Paulo"], ref: "Lucas 24 – Atos 9" },
  { title: "Primeiras histórias", events: ["Caim e Abel", "Noé constrói a arca", "Deus chama Abraão", "Jacó sonha com a escada"], ref: "Gênesis 4–28" },
  { title: "Libertação do Egito", events: ["Moisés nasce", "A sarça ardente", "As dez pragas", "A travessia do Mar Vermelho"], ref: "Êxodo 2–14" },
  { title: "Terra prometida e juízes", events: ["Josué atravessa o Jordão", "Os muros de Jericó caem", "Gideão vence os midianitas", "Sansão derruba as colunas"], ref: "Josué – Juízes" },
  { title: "Dos juízes ao rei", events: ["Deus chama Samuel", "Saul é ungido rei", "Davi é ungido", "Davi vence Golias"], ref: "1 Samuel 3–17" },
  { title: "Infância de Jesus", events: ["O anjo anuncia a Maria", "Jesus nasce em Belém", "A fuga para o Egito", "Jesus aos doze anos no templo"], ref: "Mateus 1–2; Lucas 1–2" },
  { title: "Jesus e seus discípulos", events: ["Jesus chama os primeiros discípulos", "Multiplicação dos pães", "A transfiguração", "A entrada em Jerusalém"], ref: "Evangelhos" },
  { title: "Dias da paixão", events: ["A Última Ceia", "A oração no Getsêmani", "A negação de Pedro", "A crucificação"], ref: "Mateus 26–27" },
  { title: "Reconstrução de Israel", events: ["O exílio na Babilônia", "Daniel na cova dos leões", "Neemias reconstrói os muros", "O povo lê a Lei com Esdras"], ref: "Daniel – Neemias" },
];
