// Perguntas extras do Quiz Bíblico (Bíblia protestante, ARA). Entram no FIM da lista (content.ts) para não
// mudar as partidas antigas. d: 1 = fácil, 2 = médio, 3 = difícil.
import type { QuizItem } from "./content";

export const QUIZ_EXTRA: QuizItem[] = [
  // ---------------------------------------------------------------- fácil
  { q: "Quem foi a mãe de Jesus?", a: "Maria", w: ["Isabel", "Marta", "Ana"], ref: "Lucas 1:30-31", d: 1 },
  { q: "Quem foi a primeira mulher, criada por Deus?", a: "Eva", w: ["Sara", "Ester", "Ana"], ref: "Gênesis 2:22", d: 1 },
  { q: "Em que jardim viviam Adão e Eva?", a: "Éden", w: ["Getsêmani", "Gósen", "Canaã"], ref: "Gênesis 2:8", d: 1 },
  { q: "Qual sinal Deus colocou no céu depois do dilúvio?", a: "Arco-íris", w: ["Estrela", "Cometa", "Nuvem de fogo"], ref: "Gênesis 9:13", d: 1 },
  { q: "Quantos dias e noites choveu no dilúvio?", a: "40", w: ["7", "100", "12"], ref: "Gênesis 7:12", d: 1 },
  { q: "Em quantos dias Deus criou o céu e a terra antes de descansar?", a: "6", w: ["7", "3", "12"], ref: "Gênesis 1–2", d: 1 },
  { q: "O que Deus criou no primeiro dia?", a: "A luz", w: ["Os animais", "O mar", "O homem"], ref: "Gênesis 1:3", d: 1 },
  { q: "Qual era a árvore proibida do jardim do Éden?", a: "A do conhecimento do bem e do mal", w: ["A figueira", "A oliveira", "A palmeira"], ref: "Gênesis 2:17", d: 1 },
  { q: "Quem enganou Eva no jardim do Éden?", a: "A serpente", w: ["Um leão", "Um corvo", "Uma raposa"], ref: "Gênesis 3:1", d: 1 },
  { q: "Quem foi a esposa de Abraão?", a: "Sara", w: ["Rebeca", "Raquel", "Lia"], ref: "Gênesis 17:15", d: 1 },
  { q: "Quem foi a esposa de Isaque?", a: "Rebeca", w: ["Raquel", "Lia", "Sara"], ref: "Gênesis 24", d: 1 },
  { q: "Quem era o irmão gêmeo de Jacó?", a: "Esaú", w: ["Ismael", "Labão", "Rúben"], ref: "Gênesis 25:24-26", d: 1 },
  { q: "Quantos filhos Jacó (Israel) teve?", a: "12", w: ["7", "10", "3"], ref: "Gênesis 35:22", d: 1 },
  { q: "Que cidade foi destruída com fogo junto com Gomorra?", a: "Sodoma", w: ["Jericó", "Nínive", "Betel"], ref: "Gênesis 19", d: 1 },
  { q: "Quem virou estátua de sal por olhar para trás?", a: "A mulher de Ló", w: ["Raabe", "Sara", "Lia"], ref: "Gênesis 19:26", d: 1 },
  { q: "Quantos mandamentos Deus entregou a Moisés no monte Sinai?", a: "10", w: ["7", "12", "5"], ref: "Êxodo 20", d: 1 },
  { q: "Qual comida Deus mandava do céu para o povo no deserto?", a: "Maná", w: ["Pão de cevada", "Mel", "Figos"], ref: "Êxodo 16:15", d: 1 },
  { q: "Em que monte Moisés recebeu os Dez Mandamentos?", a: "Sinai", w: ["Sião", "Carmelo", "Tabor"], ref: "Êxodo 19–20", d: 1 },
  { q: "Quem foi o irmão de Moisés que o ajudou a falar com o faraó?", a: "Arão", w: ["Josué", "Calebe", "Levi"], ref: "Êxodo 4:14-16", d: 1 },
  { q: "Quem foi o primeiro rei de Israel?", a: "Saul", w: ["Davi", "Salomão", "Samuel"], ref: "1 Samuel 10", d: 1 },
  { q: "Quem foi o homem de força extraordinária, com cabelo nunca cortado?", a: "Sansão", w: ["Golias", "Gideão", "Davi"], ref: "Juízes 16", d: 1 },
  { q: "Qual livro da Bíblia tem 150 capítulos?", a: "Salmos", w: ["Provérbios", "Isaías", "Gênesis"], ref: "Livro dos Salmos", d: 1 },
  { q: "Quem escreveu a maior parte do livro de Provérbios?", a: "Salomão", w: ["Davi", "Moisés", "Asafe"], ref: "Provérbios 1:1", d: 1 },
  { q: "Qual livro conta a história de um homem que perdeu tudo e continuou fiel?", a: "Jó", w: ["Jonas", "Rute", "Ester"], ref: "Jó 1–2", d: 1 },
  { q: "Qual é o primeiro livro do Novo Testamento?", a: "Mateus", w: ["Marcos", "João", "Atos"], ref: "Mateus 1:1", d: 1 },
  { q: "Qual livro conta o nascimento da igreja?", a: "Atos", w: ["Romanos", "Hebreus", "Tiago"], ref: "Atos 2", d: 1 },
  { q: "Quantos Evangelhos há no Novo Testamento?", a: "4", w: ["3", "5", "12"], ref: "Mateus, Marcos, Lucas e João", d: 1 },
  { q: "Qual anjo anunciou a Maria que ela teria Jesus?", a: "Gabriel", w: ["Miguel", "Elias", "Zacarias"], ref: "Lucas 1:26-31", d: 1 },
  { q: "Em qual cidade Jesus cresceu?", a: "Nazaré", w: ["Belém", "Jericó", "Cafarnaum"], ref: "Lucas 2:39-40", d: 1 },
  { q: "Qual era a profissão de José, pai terreno de Jesus?", a: "Carpinteiro", w: ["Pescador", "Pastor", "Soldado"], ref: "Mateus 13:55", d: 1 },
  { q: "O que os magos levaram de presente a Jesus?", a: "Ouro, incenso e mirra", w: ["Pão, vinho e azeite", "Prata, bronze e ferro", "Seda, mel e sal"], ref: "Mateus 2:11", d: 1 },
  { q: "Qual era a profissão de Pedro, André, Tiago e João?", a: "Pescadores", w: ["Pastores", "Soldados", "Carpinteiros"], ref: "Mateus 4:18-22", d: 1 },
  { q: "Qual discípulo andou sobre as águas ao encontro de Jesus?", a: "Pedro", w: ["João", "Tiago", "André"], ref: "Mateus 14:29", d: 1 },
  { q: "Qual discípulo traiu Jesus?", a: "Judas Iscariotes", w: ["Pedro", "Tomé", "Filipe"], ref: "Mateus 26:14-16", d: 1 },
  { q: "Quantas moedas de prata Judas recebeu para trair Jesus?", a: "30", w: ["10", "12", "100"], ref: "Mateus 26:15", d: 1 },
  { q: "Em qual jardim Jesus orou antes de ser preso?", a: "Getsêmani", w: ["Éden", "Gósen", "Betânia"], ref: "Mateus 26:36", d: 1 },
  { q: "Qual animal Jesus montou ao entrar em Jerusalém?", a: "Um jumentinho", w: ["Um cavalo", "Um camelo", "Um boi"], ref: "Mateus 21:7", d: 1 },
  { q: "Quem lavou as mãos ao condenar Jesus à cruz?", a: "Pilatos", w: ["Herodes", "Caifás", "Nicodemos"], ref: "Mateus 27:24", d: 1 },
  { q: "Qual prisioneiro foi solto no lugar de Jesus?", a: "Barrabás", w: ["Caifás", "Herodes", "Pilatos"], ref: "Mateus 27:21", d: 1 },
  { q: "Como se chama o monte onde Jesus foi crucificado?", a: "Gólgota", w: ["Sinai", "Carmelo", "Moriá"], ref: "Mateus 27:33", d: 1 },
  { q: "Em que dia da semana Jesus ressuscitou?", a: "Domingo", w: ["Sexta-feira", "Sábado", "Quarta-feira"], ref: "Mateus 28:1", d: 1 },
  { q: "Quem foi a primeira pessoa a quem Jesus apareceu depois de ressuscitar?", a: "Maria Madalena", w: ["Pedro", "João", "Tomé"], ref: "João 20:14-16", d: 1 },
  { q: "Qual é o fruto do Espírito entre estes?", a: "Domínio próprio", w: ["Orgulho", "Inveja", "Ira"], ref: "Gálatas 5:22-23", d: 1 },
  { q: "Qual Salmo começa com \"O Senhor é o meu pastor\"?", a: "Salmo 23", w: ["Salmo 1", "Salmo 91", "Salmo 150"], ref: "Salmos 23", d: 1 },
  { q: "Qual era o nome do gigante filisteu derrotado por Davi?", a: "Golias", w: ["Sísera", "Abner", "Nabal"], ref: "1 Samuel 17:4", d: 1 },
  { q: "Quem tinha uma túnica colorida dada pelo pai?", a: "José", w: ["Benjamim", "Judá", "Levi"], ref: "Gênesis 37:3", d: 1 },
  { q: "Qual era o nome do pai de José do Egito?", a: "Jacó", w: ["Isaque", "Abraão", "Esaú"], ref: "Gênesis 37:3", d: 1 },
  { q: "Quem foi escondido num cesto no rio Nilo quando bebê?", a: "Moisés", w: ["José", "Samuel", "Davi"], ref: "Êxodo 2:3", d: 1 },
  { q: "O que Moisés viu queimando sem se consumir?", a: "Uma sarça", w: ["Uma tenda", "Uma árvore seca", "Um altar"], ref: "Êxodo 3:2", d: 1 },
  { q: "Quem foi lançado numa fornalha de fogo com Sadraque e Mesaque?", a: "Abede-Nego", w: ["Daniel", "Elias", "Ezequiel"], ref: "Daniel 3", d: 1 },
  { q: "Qual era o nome do rei que mandou fazer uma estátua de ouro e exigiu que todos a adorassem?", a: "Nabucodonosor", w: ["Dario", "Ciro", "Faraó"], ref: "Daniel 3:1", d: 1 },
  { q: "Quem foi a rainha que salvou os judeus na Pérsia?", a: "Ester", w: ["Vasti", "Rute", "Ana"], ref: "Ester 7", d: 1 },
  { q: "Qual era o homem mais sábio, que pediu a Deus sabedoria em vez de riquezas?", a: "Salomão", w: ["Davi", "Saul", "Josafá"], ref: "1 Reis 3:9-12", d: 1 },
  { q: "Quantos livros tem o Novo Testamento?", a: "27", w: ["39", "66", "12"], ref: "Do Evangelho de Mateus a Apocalipse", d: 1 },
  { q: "Quantos livros tem o Antigo Testamento?", a: "39", w: ["27", "66", "46"], ref: "De Gênesis a Malaquias", d: 1 },
  { q: "Quem foi o discípulo amado, que escreveu o quarto Evangelho?", a: "João", w: ["Mateus", "Marcos", "Lucas"], ref: "João 21:20-24", d: 1 },
  { q: "Quem era o rei que quis matar o menino Jesus?", a: "Herodes", w: ["Pilatos", "Davi", "Saul"], ref: "Mateus 2:16", d: 1 },
  { q: "Quem visitou o recém-nascido Jesus numa manjedoura, depois do aviso dos anjos?", a: "Os pastores", w: ["Os soldados", "Os fariseus", "Os pescadores"], ref: "Lucas 2:8-16", d: 1 },
  { q: "Quantos pães e peixes um menino ofereceu a Jesus para alimentar a multidão?", a: "5 pães e 2 peixes", w: ["7 pães e 3 peixes", "12 pães e 5 peixes", "2 pães e 5 peixes"], ref: "João 6:9", d: 1 },
  { q: "Qual foi o milagre de Jesus que acalmou a tempestade?", a: "Ele repreendeu o vento e o mar", w: ["Ele multiplicou o vinho", "Ele curou um paralítico", "Ele caminhou sobre o fogo"], ref: "Marcos 4:39", d: 1 },
  { q: "Quem foi ressuscitado por Jesus depois de quatro dias no túmulo?", a: "Lázaro", w: ["Tabita", "Eutico", "O filho da viúva"], ref: "João 11", d: 1 },
  { q: "Qual foi o nome do homem cego que gritava por Jesus em Jericó?", a: "Bartimeu", w: ["Zaqueu", "Lázaro", "Malco"], ref: "Marcos 10:46-52", d: 1 },
  { q: "Qual foi a oração mais curta de Pedro ao afundar no mar?", a: "\"Senhor, salva-me!\"", w: ["\"Mestre, ajuda-me!\"", "\"Pai, perdoa-me!\"", "\"Senhor, vem!\""], ref: "Mateus 14:30", d: 1 },
  { q: "O que o povo gritava quando Jesus entrou em Jerusalém?", a: "Hosana!", w: ["Aleluia!", "Amém!", "Shalom!"], ref: "Mateus 21:9", d: 1 },
  { q: "Quem era a mulher viúva moabita que seguiu a sogra Noemi?", a: "Rute", w: ["Orfa", "Ester", "Raabe"], ref: "Rute 1:16", d: 1 },
  { q: "Qual fruto Eva comeu, segundo o relato mais famoso?", a: "A Bíblia não diz qual fruto era", w: ["Maçã", "Figo", "Uva"], ref: "Gênesis 3:6", d: 1 },
  { q: "Quem construiu uma torre tentando chegar ao céu?", a: "Os homens de Babel", w: ["Os filisteus", "Os egípcios", "Os amorreus"], ref: "Gênesis 11:4", d: 1 },
  { q: "Quem foi o pai de Noé?", a: "Lameque", w: ["Enoque", "Sete", "Matusalém"], ref: "Gênesis 5:28-29", d: 3 },
  { q: "Quem foi o homem mais velho da Bíblia, que viveu 969 anos?", a: "Matusalém", w: ["Noé", "Adão", "Enoque"], ref: "Gênesis 5:27", d: 2 },

  // ---------------------------------------------------------------- médio
  { q: "Que filho de Abraão nasceu de Hagar, serva de Sara?", a: "Ismael", w: ["Isaque", "Esaú", "Jacó"], ref: "Gênesis 16:15", d: 2 },
  { q: "Quem era o pai de Davi?", a: "Jessé", w: ["Saul", "Samuel", "Obede"], ref: "1 Samuel 16:1", d: 2 },
  { q: "Qual cidade Davi conquistou dos jebuseus e tornou capital de Israel?", a: "Jerusalém", w: ["Jericó", "Siquém", "Nínive"], ref: "2 Samuel 5:6-9", d: 2 },
  { q: "Quem era o sacerdote que criou o menino Samuel no templo?", a: "Eli", w: ["Zadoque", "Arão", "Abiatar"], ref: "1 Samuel 2:11", d: 2 },
  { q: "Quais foram os dois espias que confiaram em Deus e entraram na terra prometida?", a: "Josué e Calebe", w: ["Arão e Hur", "Moisés e Arão", "Gideão e Baraque"], ref: "Números 14:30", d: 2 },
  { q: "Qual é o último livro do Antigo Testamento?", a: "Malaquias", w: ["Zacarias", "Ageu", "Neemias"], ref: "Malaquias 4", d: 2 },
  { q: "Em que festa o Espírito Santo foi derramado sobre os discípulos?", a: "Pentecostes", w: ["Páscoa", "Tabernáculos", "Purim"], ref: "Atos 2:1-4", d: 2 },
  { q: "Quem foi o primeiro mártir cristão, apedrejado por causa da fé?", a: "Estêvão", w: ["Tiago", "Paulo", "Barnabé"], ref: "Atos 7:59-60", d: 2 },
  { q: "Quem era médico e escreveu o Evangelho de Lucas e o livro de Atos?", a: "Lucas", w: ["Marcos", "Timóteo", "Tito"], ref: "Colossenses 4:14", d: 2 },
  { q: "Em que dia Deus criou o homem?", a: "No sexto dia", w: ["No primeiro dia", "No terceiro dia", "No sétimo dia"], ref: "Gênesis 1:26-31", d: 2 },
  { q: "Quantos dias Jesus apareceu aos discípulos depois de ressuscitar, antes de subir ao céu?", a: "40", w: ["3", "7", "50"], ref: "Atos 1:3", d: 2 },
  { q: "Qual era o nome do jovem que dormiu durante o discurso de Paulo e caiu da janela?", a: "Êutico", w: ["Timóteo", "Tito", "Silas"], ref: "Atos 20:9", d: 3 },
  { q: "Qual profeta foi alimentado por corvos junto ao ribeiro de Querite?", a: "Elias", w: ["Eliseu", "Samuel", "Jeremias"], ref: "1 Reis 17:4-6", d: 2 },
  { q: "Quem interpretou a escrita misteriosa na parede para o rei Belsazar?", a: "Daniel", w: ["José", "Ezequiel", "Mardoqueu"], ref: "Daniel 5", d: 2 },
  { q: "Qual era o nome da mãe de João Batista?", a: "Isabel", w: ["Ana", "Maria", "Marta"], ref: "Lucas 1:57-60", d: 2 },
  { q: "Qual era o nome da irmã de Lázaro que ficou aos pés de Jesus para ouvi-lo?", a: "Maria", w: ["Marta", "Salomé", "Joana"], ref: "Lucas 10:39", d: 2 },
  { q: "Quem Jesus elogiou por colocar duas moedinhas na oferta do templo?", a: "Uma viúva pobre", w: ["Um fariseu rico", "Zaqueu", "Um centurião"], ref: "Marcos 12:41-44", d: 2 },
  { q: "Qual apóstolo foi também chamado de Dídimo (\"gêmeo\")?", a: "Tomé", w: ["Tiago", "Natanael", "Tadeu"], ref: "João 11:16", d: 2 },
  { q: "Qual apóstolo foi escolhido para substituir Judas Iscariotes?", a: "Matias", w: ["Barnabé", "Silas", "Timóteo"], ref: "Atos 1:26", d: 2 },
  { q: "Quem orou por Paulo em Damasco para ele recuperar a visão?", a: "Ananias", w: ["Barnabé", "Silas", "Filipe"], ref: "Atos 9:17", d: 2 },
  { q: "Quem acompanhou Paulo na primeira viagem missionária?", a: "Barnabé", w: ["Silas", "Timóteo", "Tito"], ref: "Atos 13:2", d: 2 },
  { q: "Em qual cidade Paulo e Silas foram presos e um terremoto abriu as portas da prisão?", a: "Filipos", w: ["Éfeso", "Corinto", "Atenas"], ref: "Atos 16:25-26", d: 2 },
  { q: "Qual jovem discípulo recebeu duas cartas de Paulo, e foi seu \"filho na fé\"?", a: "Timóteo", w: ["Tito", "Filemom", "Epafrodito"], ref: "1 Timóteo 1:2", d: 2 },
  { q: "Qual carta de Paulo fala da \"armadura de Deus\"?", a: "Efésios", w: ["Romanos", "Gálatas", "Filipenses"], ref: "Efésios 6:10-17", d: 2 },
  { q: "Qual carta de Paulo é conhecida como a \"carta da alegria\"?", a: "Filipenses", w: ["Colossenses", "Tito", "Tessalonicenses"], ref: "Filipenses 4:4", d: 2 },
  { q: "Qual capítulo de 1 Coríntios é conhecido como o \"capítulo do amor\"?", a: "13", w: ["1", "8", "15"], ref: "1 Coríntios 13", d: 2 },
  { q: "Qual livro do Novo Testamento é conhecido pela \"galeria dos heróis da fé\"?", a: "Hebreus", w: ["Tiago", "Judas", "Filemom"], ref: "Hebreus 11", d: 2 },
  { q: "Quem foi o juiz que derrotou os midianitas com 300 homens e trombetas?", a: "Gideão", w: ["Sansão", "Jefté", "Baraque"], ref: "Juízes 7:19-22", d: 2 },
  { q: "Quem foi a juíza e profetisa que liderou Israel com Baraque?", a: "Débora", w: ["Ana", "Miriã", "Hulda"], ref: "Juízes 4:4", d: 2 },
  { q: "Qual mulher de Jericó escondeu os espias de Israel?", a: "Raabe", w: ["Rute", "Ester", "Débora"], ref: "Josué 2:1-4", d: 2 },
  { q: "Quem foi o sogro de Moisés, sacerdote de Midiã?", a: "Jetro", w: ["Calebe", "Arão", "Labão"], ref: "Êxodo 3:1", d: 3 },
  { q: "Quem foi a esposa de Moisés?", a: "Zípora", w: ["Miriã", "Raabe", "Rute"], ref: "Êxodo 2:21", d: 3 },
  { q: "Qual irmã de Moisés liderou as mulheres num canto depois da travessia do Mar Vermelho?", a: "Miriã", w: ["Zípora", "Débora", "Raabe"], ref: "Êxodo 15:20-21", d: 2 },
  { q: "Quantos anos Jacó trabalhou no total para se casar com Raquel e Lia?", a: "14", w: ["7", "10", "20"], ref: "Gênesis 29:18-30", d: 3 },
  { q: "Qual era o filho mais novo de Jacó?", a: "Benjamim", w: ["José", "Judá", "Levi"], ref: "Gênesis 35:18", d: 2 },
  { q: "Qual filho de Jacó foi vendido por vinte moedas de prata?", a: "José", w: ["Rúben", "Simeão", "Judá"], ref: "Gênesis 37:28", d: 2 },
  { q: "Qual era a terra onde José colocou sua família no Egito?", a: "Gósen", w: ["Canaã", "Moabe", "Sinai"], ref: "Gênesis 47:6", d: 3 },
  { q: "Qual praga caiu sobre o Egito por último?", a: "A morte dos primogênitos", w: ["Os gafanhotos", "As trevas", "O granizo"], ref: "Êxodo 12:29-30", d: 2 },
  { q: "Qual era a festa que lembra a saída do Egito?", a: "Páscoa", w: ["Pentecostes", "Purim", "Tabernáculos"], ref: "Êxodo 12:14", d: 2 },
  { q: "Qual era o nome do sumo sacerdote que presidiu o julgamento de Jesus?", a: "Caifás", w: ["Anás", "Zadoque", "Eli"], ref: "Mateus 26:57", d: 2 },
  { q: "O que Jesus disse ao malfeitor arrependido na cruz?", a: "Hoje estarás comigo no paraíso", w: ["Tua fé te salvou", "Vai e não peques mais", "Segue-me"], ref: "Lucas 23:43", d: 2 },
  { q: "Quem foi o primeiro a entrar no túmulo vazio de Jesus, segundo João?", a: "Pedro", w: ["João", "Tomé", "Maria Madalena"], ref: "João 20:6", d: 3 },
  { q: "Quantas vezes Jesus perguntou a Pedro \"Tu me amas?\" depois da ressurreição?", a: "3", w: ["1", "7", "12"], ref: "João 21:15-17", d: 2 },
  { q: "Onde Jesus realizou seu primeiro milagre?", a: "Caná da Galileia", w: ["Cafarnaum", "Betânia", "Nain"], ref: "João 2:1-11", d: 2 },
  { q: "Em que lugar Jesus pediu água a uma mulher samaritana?", a: "No poço de Jacó", w: ["No rio Jordão", "No mar da Galileia", "No tanque de Betesda"], ref: "João 4:5-7", d: 2 },
  { q: "Qual foi o centurião romano que recebeu Pedro em sua casa e creu em Jesus?", a: "Cornélio", w: ["Júlio", "Tito", "Longino"], ref: "Atos 10:1-2", d: 3 },
  { q: "Qual era a cidade natal de Zaqueu, o cobrador de impostos?", a: "Jericó", w: ["Belém", "Cafarnaum", "Betânia"], ref: "Lucas 19:1-2", d: 2 },
  { q: "Qual parábola fala de um pai que corre para abraçar o filho que voltou?", a: "O filho pródigo", w: ["O bom samaritano", "O semeador", "As dez virgens"], ref: "Lucas 15:11-24", d: 2 },
  { q: "Qual parábola fala de dois homens, um sacerdote e um levita, que passam direto pelo ferido?", a: "O bom samaritano", w: ["O filho pródigo", "O semeador", "O credor incompassivo"], ref: "Lucas 10:30-37", d: 2 },
  { q: "Qual parábola fala de sementes caindo em diferentes tipos de terreno?", a: "O semeador", w: ["O tesouro escondido", "O fermento", "A rede"], ref: "Mateus 13:3-9", d: 2 },
  { q: "Na parábola dos talentos, o que o servo mau fez com o talento que recebeu?", a: "Enterrou", w: ["Gastou", "Perdeu", "Emprestou"], ref: "Mateus 25:25", d: 2 },
  { q: "Na parábola das dez virgens, o que cinco delas esqueceram de levar?", a: "Azeite para as lâmpadas", w: ["Pão", "Vinho", "Mantos"], ref: "Mateus 25:3", d: 2 },
  { q: "Qual era o nome do monte onde Jesus foi transfigurado, segundo a tradição?", a: "Tabor", w: ["Sinai", "Carmelo", "Moriá"], ref: "Mateus 17:1-2", d: 3 },
  { q: "Quais dois profetas apareceram com Jesus na transfiguração?", a: "Moisés e Elias", w: ["Isaías e Jeremias", "Davi e Salomão", "Abraão e Isaque"], ref: "Mateus 17:3", d: 2 },
  { q: "Qual dos filhos de Zebedeu foi o primeiro apóstolo martirizado?", a: "Tiago", w: ["João", "Pedro", "André"], ref: "Atos 12:2", d: 3 },
  { q: "Qual apóstolo foi chamado por Jesus debaixo da figueira?", a: "Natanael", w: ["Filipe", "André", "Tomé"], ref: "João 1:48", d: 3 },
  { q: "Qual apóstolo foi irmão de Pedro?", a: "André", w: ["João", "Tiago", "Filipe"], ref: "João 1:40", d: 2 },
  { q: "Qual apóstolo era chamado \"o zelote\"?", a: "Simão", w: ["Judas Tadeu", "Mateus", "Tiago"], ref: "Lucas 6:15", d: 3 },

  // ---------------------------------------------------------------- difícil
  { q: "Quantos capítulos tem o livro de Gênesis?", a: "50", w: ["40", "66", "31"], ref: "Gênesis 1–50", d: 3 },
  { q: "Quantos capítulos tem o livro de Provérbios?", a: "31", w: ["50", "66", "21"], ref: "Provérbios 1–31", d: 3 },
  { q: "Quantos capítulos tem o livro de Isaías?", a: "66", w: ["50", "52", "40"], ref: "Isaías 1–66", d: 3 },
  { q: "Quantos capítulos tem o Evangelho de Mateus?", a: "28", w: ["16", "21", "24"], ref: "Mateus 1–28", d: 3 },
  { q: "Quantos capítulos tem o livro de Apocalipse?", a: "22", w: ["12", "28", "27"], ref: "Apocalipse 1–22", d: 3 },
  { q: "Qual é o capítulo mais longo da Bíblia?", a: "Salmo 119", w: ["Salmo 23", "Gênesis 1", "Isaías 53"], ref: "Salmos 119", d: 3 },
  { q: "Qual é o versículo mais curto da Bíblia em português (\"Jesus chorou\")?", a: "João 11:35", w: ["João 3:16", "Lucas 17:32", "Salmos 117:1"], ref: "João 11:35", d: 3 },
  { q: "Qual livro do Antigo Testamento não cita o nome de Deus no texto?", a: "Ester", w: ["Rute", "Jonas", "Daniel"], ref: "Livro de Ester", d: 3 },
  { q: "Qual livro do Antigo Testamento termina com a promessa de que Elias viria antes do grande dia do Senhor?", a: "Malaquias", w: ["Zacarias", "Joel", "Amós"], ref: "Malaquias 4:5", d: 3 },
  { q: "Quem foi o último juiz de Israel, antes dos reis?", a: "Samuel", w: ["Sansão", "Eli", "Gideão"], ref: "1 Samuel 7:15", d: 3 },
  { q: "Qual era o nome do pai de Sansão?", a: "Manoá", w: ["Elcana", "Zacarias", "Joás"], ref: "Juízes 13:2", d: 3 },
  { q: "Quem era o pai de Samuel?", a: "Elcana", w: ["Eli", "Jessé", "Manoá"], ref: "1 Samuel 1:1", d: 3 },
  { q: "Quem foi o filho rebelde de Davi que tentou tomar o trono?", a: "Absalão", w: ["Adonias", "Amnom", "Salomão"], ref: "2 Samuel 15", d: 3 },
  { q: "Quem foi o general de Davi que comandou o exército?", a: "Joabe", w: ["Abner", "Urias", "Benaia"], ref: "2 Samuel 8:16", d: 3 },
  { q: "Quem foi o marido de Bate-Seba, morto por ordem de Davi?", a: "Urias", w: ["Joabe", "Abner", "Natã"], ref: "2 Samuel 11:15", d: 3 },
  { q: "Qual rei de Judá teve a vida prolongada por 15 anos depois de orar?", a: "Ezequias", w: ["Josias", "Josafá", "Uzias"], ref: "2 Reis 20:6", d: 3 },
  { q: "Qual rei de Judá ficou famoso por ter encontrado o Livro da Lei no templo?", a: "Josias", w: ["Ezequias", "Joás", "Manassés"], ref: "2 Reis 22:8", d: 3 },
  { q: "Qual rei construiu o templo em Jerusalém?", a: "Salomão", w: ["Davi", "Ezequias", "Zorobabel"], ref: "1 Reis 6", d: 2 },
  { q: "Qual rainha visitou Salomão para testar sua sabedoria?", a: "A rainha de Sebá", w: ["A rainha Vasti", "A rainha Jezabel", "A rainha Atalia"], ref: "1 Reis 10:1", d: 3 },
  { q: "Qual rainha perseguiu o profeta Elias?", a: "Jezabel", w: ["Atalia", "Vasti", "Dalila"], ref: "1 Reis 19:1-2", d: 3 },
  { q: "Quem foi o sucessor do profeta Elias?", a: "Eliseu", w: ["Isaías", "Jeremias", "Giezi"], ref: "1 Reis 19:19-21", d: 2 },
  { q: "Qual general sírio foi curado da lepra ao se banhar sete vezes no Jordão?", a: "Naamã", w: ["Hazael", "Benadade", "Sísera"], ref: "2 Reis 5:14", d: 3 },
  { q: "Quem foi o servo ganancioso de Eliseu que ficou com lepra?", a: "Giezi", w: ["Abisai", "Baruque", "Obadias"], ref: "2 Reis 5:27", d: 3 },
  { q: "Qual era a cidade onde Jonas deveria pregar?", a: "Nínive", w: ["Babilônia", "Tarso", "Damasco"], ref: "Jonas 1:2", d: 2 },
  { q: "Qual foi o profeta que escreveu Lamentações?", a: "Jeremias", w: ["Isaías", "Ezequiel", "Daniel"], ref: "Lamentações 1:1 (tradição)", d: 3 },
  { q: "Qual profeta viu um carro de fogo cheio de olhos e uma roda dentro de uma roda?", a: "Ezequiel", w: ["Isaías", "Daniel", "Zacarias"], ref: "Ezequiel 1", d: 3 },
  { q: "Qual era o nome hebraico de Daniel dado na Babilônia?", a: "Beltessazar", w: ["Sadraque", "Abede-Nego", "Mesaque"], ref: "Daniel 1:7", d: 3 },
  { q: "Quais eram os nomes babilônicos dos três amigos de Daniel?", a: "Sadraque, Mesaque e Abede-Nego", w: ["Hananias, Misael e Azarias", "Esdras, Neemias e Zorobabel", "Mardoqueu, Hamã e Assuero"], ref: "Daniel 1:7", d: 3 },
  { q: "Qual cidade foi destruída por Deus mas poupou a família de Ló?", a: "Sodoma", w: ["Nínive", "Jericó", "Ai"], ref: "Gênesis 19:15-29", d: 2 },
  { q: "Quem reconstruiu os muros de Jerusalém depois do exílio?", a: "Neemias", w: ["Esdras", "Zorobabel", "Ageu"], ref: "Neemias 6:15", d: 2 },
  { q: "Quem era o sacerdote e escriba que leu a Lei ao povo depois do exílio?", a: "Esdras", w: ["Neemias", "Zorobabel", "Zacarias"], ref: "Neemias 8:1-3", d: 3 },
  { q: "Qual rei persa permitiu que os judeus voltassem a Jerusalém?", a: "Ciro", w: ["Dario", "Xerxes", "Artaxerxes"], ref: "Esdras 1:1-3", d: 3 },
  { q: "Qual era o nome do primo de Ester que a criou?", a: "Mardoqueu", w: ["Hamã", "Hegai", "Assuero"], ref: "Ester 2:7", d: 3 },
  { q: "Qual foi o vilão do livro de Ester, que planejou destruir os judeus?", a: "Hamã", w: ["Mardoqueu", "Assuero", "Hegai"], ref: "Ester 3:6", d: 3 },
  { q: "Quantos amigos de Jó o visitaram para consolá-lo (e acabaram o criticando)?", a: "3", w: ["2", "4", "7"], ref: "Jó 2:11", d: 3 },
  { q: "Qual era o nome da terra de Jó?", a: "Uz", w: ["Moabe", "Edom", "Sebá"], ref: "Jó 1:1", d: 3 },
  { q: "Quantos anos Matusalém viveu?", a: "969", w: ["930", "777", "1000"], ref: "Gênesis 5:27", d: 3 },
  { q: "Quem foi levado por Deus sem passar pela morte, antes do dilúvio?", a: "Enoque", w: ["Matusalém", "Lameque", "Sete"], ref: "Gênesis 5:24", d: 3 },
  { q: "Qual era o nome do pai de Abraão?", a: "Terá", w: ["Naor", "Harã", "Ló"], ref: "Gênesis 11:26", d: 3 },
  { q: "Qual era o nome de Abraão antes de Deus mudá-lo?", a: "Abrão", w: ["Abimeleque", "Abner", "Aarão"], ref: "Gênesis 17:5", d: 3 },
  { q: "Qual era o nome de Jacó depois da luta com o anjo?", a: "Israel", w: ["Judá", "Efraim", "Abraão"], ref: "Gênesis 32:28", d: 2 },
  { q: "Qual filho de José recebeu a bênção principal de Jacó, mesmo sendo o mais novo?", a: "Efraim", w: ["Manassés", "Benjamim", "Judá"], ref: "Gênesis 48:14", d: 3 },
  { q: "Qual tribo de Israel foi separada para o serviço do tabernáculo?", a: "Levi", w: ["Judá", "Dã", "Benjamim"], ref: "Números 3:12", d: 3 },
  { q: "De qual tribo veio o rei Davi?", a: "Judá", w: ["Levi", "Benjamim", "Efraim"], ref: "Rute 4:18-22", d: 3 },
  { q: "De qual tribo foi o rei Saul?", a: "Benjamim", w: ["Judá", "Levi", "Efraim"], ref: "1 Samuel 9:1-2", d: 3 },
  { q: "De qual tribo era o apóstolo Paulo?", a: "Benjamim", w: ["Judá", "Levi", "Rúben"], ref: "Filipenses 3:5", d: 3 },
  { q: "Quantas pedras Davi pegou do ribeiro para enfrentar Golias?", a: "5", w: ["1", "3", "12"], ref: "1 Samuel 17:40", d: 3 },
  { q: "Quantos anos Salomão levou para construir o templo?", a: "7", w: ["3", "13", "40"], ref: "1 Reis 6:38", d: 3 },
  { q: "Quantos anos o rei Salomão reinou?", a: "40", w: ["20", "33", "50"], ref: "1 Reis 11:42", d: 3 },
  { q: "Qual era o nome do pai de João Batista?", a: "Zacarias", w: ["José", "Simeão", "Eli"], ref: "Lucas 1:13", d: 2 },
  { q: "Qual idoso reconheceu Jesus no templo e disse \"agora, Senhor, podes despedir em paz o teu servo\"?", a: "Simeão", w: ["Zacarias", "Eli", "Nicodemos"], ref: "Lucas 2:25-29", d: 3 },
  { q: "Qual profetisa, viúva de 84 anos, também reconheceu Jesus no templo?", a: "Ana", w: ["Isabel", "Hulda", "Débora"], ref: "Lucas 2:36-38", d: 3 },
  { q: "Qual mulher orou no templo por um filho e depois teve Samuel?", a: "Ana", w: ["Hulda", "Sara", "Débora"], ref: "1 Samuel 1:10-20", d: 2 },
  { q: "Quem eram os filhos de Zebedeu?", a: "Tiago e João", w: ["Pedro e André", "Filipe e Bartolomeu", "Mateus e Tomé"], ref: "Mateus 4:21", d: 2 },
  { q: "Qual apóstolo era chamado por Jesus de \"Boanerges\" (filho do trovão)? (um dos dois irmãos)", a: "Tiago e João", w: ["Pedro e André", "Tomé e Mateus", "Simão e Judas"], ref: "Marcos 3:17", d: 3 },
  { q: "Quem era Barnabé, cujo nome significa \"filho da consolação\"?", a: "Um levita de Chipre que ajudou Paulo", w: ["Um centurião romano", "Um fariseu de Jerusalém", "Um pescador da Galileia"], ref: "Atos 4:36", d: 3 },
  { q: "Em qual cidade os seguidores de Jesus foram chamados de cristãos pela primeira vez?", a: "Antioquia", w: ["Jerusalém", "Roma", "Éfeso"], ref: "Atos 11:26", d: 3 },
  { q: "Qual ilha foi o local onde João recebeu a revelação do Apocalipse?", a: "Patmos", w: ["Creta", "Chipre", "Malta"], ref: "Apocalipse 1:9", d: 3 },
  { q: "Quantas igrejas recebem cartas no começo do Apocalipse?", a: "7", w: ["3", "12", "5"], ref: "Apocalipse 1:11", d: 2 },
  { q: "Em qual ilha o apóstolo Paulo foi picado por uma víbora e não sofreu dano?", a: "Malta", w: ["Creta", "Patmos", "Chipre"], ref: "Atos 28:1-5", d: 3 },
  { q: "Qual livro do Novo Testamento é uma carta de Paulo a um senhor de escravo sobre um escravo chamado Onésimo?", a: "Filemom", w: ["Tito", "Colossenses", "Tiago"], ref: "Filemom 10", d: 3 },
  { q: "Quem foi o homem que ajudou Apolo a entender melhor o caminho, junto com sua esposa Priscila?", a: "Áquila", w: ["Silas", "Tíquico", "Demas"], ref: "Atos 18:26", d: 3 },
  { q: "Qual carta do Novo Testamento diz \"a fé sem obras é morta\"?", a: "Tiago", w: ["Hebreus", "Romanos", "1 Pedro"], ref: "Tiago 2:26", d: 2 },
  { q: "Qual carta diz \"Deus é amor\"?", a: "1 João", w: ["Romanos", "Filipenses", "Tiago"], ref: "1 João 4:8", d: 2 },
  { q: "Em que livro está o texto \"Tudo tem o seu tempo determinado\"?", a: "Eclesiastes", w: ["Provérbios", "Cantares", "Salmos"], ref: "Eclesiastes 3:1", d: 2 },
  { q: "Qual livro poético do Antigo Testamento é um canto de amor atribuído a Salomão?", a: "Cantares de Salomão", w: ["Eclesiastes", "Provérbios", "Lamentações"], ref: "Cantares 1:1", d: 3 },

  // ---------------------------------------------------------------- mais perguntas
  { q: "Qual ave trouxe a Noé um ramo de oliveira?", a: "Pomba", w: ["Corvo", "Águia", "Andorinha"], ref: "Gênesis 8:11", d: 1 },
  { q: "Quem foi o pai de Esaú e Jacó?", a: "Isaque", w: ["Abraão", "Labão", "Ismael"], ref: "Gênesis 25:19-26", d: 1 },
  { q: "Quem escreveu a maioria das cartas do Novo Testamento?", a: "Paulo", w: ["Pedro", "João", "Tiago"], ref: "Romanos a Filemom", d: 1 },
  { q: "Qual é o primeiro dos Dez Mandamentos?", a: "Não terás outros deuses diante de mim", w: ["Não matarás", "Honra teu pai e tua mãe", "Santificarás o sábado"], ref: "Êxodo 20:3", d: 1 },
  { q: "Quantos filhos Noé teve?", a: "3", w: ["2", "4", "12"], ref: "Gênesis 6:10", d: 1 },
  { q: "O que Davi usou para derrubar Golias?", a: "Uma funda e uma pedra", w: ["Uma espada", "Uma lança", "Um arco"], ref: "1 Samuel 17:49", d: 1 },
  { q: "Quem pregou o primeiro sermão no dia de Pentecostes?", a: "Pedro", w: ["Paulo", "João", "Estêvão"], ref: "Atos 2:14", d: 1 },
  { q: "Qual rio o povo de Israel atravessou para entrar na terra prometida?", a: "Jordão", w: ["Nilo", "Eufrates", "Tigre"], ref: "Josué 3", d: 1 },
  { q: "Em qual cidade Paulo se converteu a caminho?", a: "Damasco", w: ["Jerusalém", "Antioquia", "Roma"], ref: "Atos 9:3", d: 1 },
  { q: "Qual filho de Davi construiu o templo?", a: "Salomão", w: ["Absalão", "Adonias", "Natã"], ref: "1 Reis 6:1", d: 1 },
  { q: "Quem foi o filho que Ana pediu a Deus no templo e depois entregou ao serviço do Senhor?", a: "Samuel", w: ["Davi", "Saul", "Elias"], ref: "1 Samuel 1:20-28", d: 1 },
  { q: "Quantas pessoas estavam na arca de Noé?", a: "8", w: ["2", "12", "7"], ref: "1 Pedro 3:20", d: 2 },
  { q: "Quem recebeu a visita de três homens junto aos carvalhos de Manre?", a: "Abraão", w: ["Isaque", "Ló", "Noé"], ref: "Gênesis 18:1-12", d: 2 },
  { q: "Quem disse \"Eis-me aqui, envia-me a mim\"?", a: "Isaías", w: ["Jeremias", "Jonas", "Samuel"], ref: "Isaías 6:8", d: 2 },
  { q: "Em que monte Abraão levou Isaque para oferecer a Deus?", a: "Moriá", w: ["Sinai", "Carmelo", "Hermom"], ref: "Gênesis 22:2", d: 2 },
  { q: "Qual mulher foi dada enganosamente a Jacó no lugar de Raquel?", a: "Lia", w: ["Zilpa", "Bila", "Sara"], ref: "Gênesis 29:23-25", d: 2 },
  { q: "Quem sepultou Jesus em um túmulo novo, escavado na rocha?", a: "José de Arimateia", w: ["Nicodemos", "Pedro", "Zaqueu"], ref: "Mateus 27:59-60", d: 2 },
  { q: "Em que mar Jesus acalmou a tempestade?", a: "Mar da Galileia", w: ["Mar Morto", "Mar Vermelho", "Mar Mediterrâneo"], ref: "Marcos 4:35-41", d: 2 },
  { q: "Qual era o nome do servo cuja orelha Pedro cortou ao defender Jesus?", a: "Malco", w: ["Caifás", "Anás", "Barrabás"], ref: "João 18:10", d: 2 },
  { q: "Quem eram Áquila e Priscila?", a: "Um casal que fazia tendas e ajudou Paulo", w: ["Dois irmãos de Jesus", "Dois discípulos de João Batista", "Pastores de Belém"], ref: "Atos 18:2-3", d: 2 },
  { q: "Quantos anos Davi reinou sobre Israel?", a: "40", w: ["20", "33", "70"], ref: "2 Samuel 5:4", d: 2 },
  { q: "Qual rei de Israel mandou fazer os bezerros de ouro em Betel e Dã?", a: "Jeroboão", w: ["Acabe", "Roboão", "Jeú"], ref: "1 Reis 12:28-29", d: 2 },
  { q: "Qual profeta aconselhou o rei Ezequias quando a Assíria o cercou?", a: "Isaías", w: ["Jeremias", "Oseias", "Amós"], ref: "2 Reis 19:2", d: 3 },
  { q: "Qual cidade da Macedônia foi a primeira da Europa a receber o Evangelho por Paulo?", a: "Filipos", w: ["Atenas", "Corinto", "Roma"], ref: "Atos 16:12", d: 2 },
  { q: "Qual carta de Paulo foi escrita aos cristãos da cidade de Colossos?", a: "Colossenses", w: ["Coríntios", "Gálatas", "Efésios"], ref: "Colossenses 1:2", d: 2 },
  { q: "Qual carta afirma que \"Deus é luz\" e que devemos andar na luz?", a: "1 João", w: ["Judas", "Tiago", "2 Pedro"], ref: "1 João 1:5-7", d: 3 },
  { q: "Qual era o nome do pai de Moisés?", a: "Anrão", w: ["Arão", "Calebe", "Jetro"], ref: "Êxodo 6:20", d: 3 },
  { q: "Qual era o nome da mãe de Moisés?", a: "Joquebede", w: ["Miriã", "Zípora", "Elisabete"], ref: "Êxodo 6:20", d: 3 },
  { q: "Quem perguntou ao anjo: \"Se o Senhor é conosco, por que nos sucedeu tudo isto?\"", a: "Gideão", w: ["Sansão", "Josué", "Baraque"], ref: "Juízes 6:13", d: 3 },
  { q: "Qual juiz de Israel teve os olhos arrancados pelos filisteus?", a: "Sansão", w: ["Gideão", "Jefté", "Samuel"], ref: "Juízes 16:21", d: 2 },
  { q: "Qual rei foi transformado por um tempo a viver como animal até reconhecer a Deus?", a: "Nabucodonosor", w: ["Ezequias", "Manassés", "Uzias"], ref: "Daniel 4:33", d: 3 },
  { q: "Qual rei de Israel foi ungido por um jovem profeta a mando de Eliseu e dirigia o carro como louco?", a: "Jeú", w: ["Acabe", "Jeroboão", "Zinri"], ref: "2 Reis 9:20", d: 3 },
  { q: "Qual profeta anunciou que o Messias nasceria em Belém?", a: "Miqueias", w: ["Isaías", "Jeremias", "Naum"], ref: "Miqueias 5:2", d: 3 },
  { q: "Em que cidade Jesus ressuscitou o filho de uma viúva?", a: "Naim", w: ["Caná", "Betânia", "Nazaré"], ref: "Lucas 7:11-15", d: 3 },
  { q: "Qual rei disse a Paulo: \"por pouco me persuades a me tornar cristão\"?", a: "Agripa", w: ["Herodes", "Félix", "Festo"], ref: "Atos 26:28", d: 3 },
  { q: "Qual governador romano deixou Paulo preso por dois anos esperando suborno?", a: "Félix", w: ["Festo", "Pilatos", "Cornélio"], ref: "Atos 24:26-27", d: 3 },
  { q: "Quem escreveu as cartas 1 e 2 Pedro?", a: "Pedro", w: ["Paulo", "João", "Judas"], ref: "1 Pedro 1:1", d: 2 },
  { q: "Qual era o rei da Babilônia durante o banquete em que a mão escreveu na parede?", a: "Belsazar", w: ["Dario", "Ciro", "Nabucodonosor"], ref: "Daniel 5:1", d: 3 },
  { q: "Quantos filhos Jó tinha no começo do livro?", a: "10 (sete filhos e três filhas)", w: ["12", "7", "3"], ref: "Jó 1:2", d: 3 },
];
