// Versículos extras do "Complete o Versículo" (Nova Versão Internacional (NVI)). Cada versículo é escrito uma vez e
// gera uma pergunta por lacuna. Textos longos que não tenho certeza de memória terminam em "…".
// Entram no FIM da lista (content.ts) para não mudar as partidas antigas.
import type { Level, VerseItem } from "./content";

/** [palavra da lacuna (use "palavra#2" para a 2ª ocorrência), 3 erradas, nível] */
type Blank = [string, string, string, string, Level];
type Verse = [ref: string, text: string, ...blanks: Blank[]];

const VERSES_DATA: Verse[] = [
  ["Gênesis 1:1", "No princípio Deus criou os céus e a terra.", ["céus", "mares", "anjos", "montes", 1], ["princípio", "caminho", "dilúvio", "silêncio", 1], ["Deus", "O Senhor", "Jesus", "Adão", 1], ["terra", "mar", "sol", "lua", 1]],
  ["Gênesis 1:27", "Criou Deus o homem à sua imagem, à imagem de Deus o criou; homem e mulher os criou.", ["imagem", "força", "glória", "sombra", 1], ["mulher", "criança", "anjo", "pastor", 1], ["homem", "anjo", "leão", "rei", 1]],
  ["Gênesis 50:20", "Vocês planejaram o mal contra mim, mas Deus o tornou em bem, para que hoje fosse preservada a vida de muitos.", ["bem", "glória", "paz", "verdade", 3], ["preservada", "esquecida", "perdida", "contada", 3], ["planejaram", "esqueceram", "pagaram", "pediram", 3]],
  ["Êxodo 20:3", "Não tenha outros deuses além de mim.", ["outros", "muitos", "falsos", "novos", 1], ["deuses", "reis", "anjos", "santos", 1]],
  ["Números 6:24", "O Senhor te abençoe e te guarde;", ["abençoe", "ensine", "console", "visite", 2], ["guarde", "chame", "mostre", "espere", 2]],
  ["Deuteronômio 6:5", "Ame o Senhor, o seu Deus, de todo o seu coração, de toda a sua alma e de todas as suas forças.", ["forças", "obras", "palavras", "riquezas", 2], ["alma", "casa", "voz", "mente", 2]],
  ["Josué 24:15", "Mas eu e a minha família serviremos ao Senhor.", ["serviremos", "temeremos", "buscaremos", "seguiremos", 2], ["família", "tribo", "cidade", "casa", 2]],
  ["Rute 1:16", "O seu povo será o meu povo e o seu Deus será o meu Deus.", ["povo", "rei", "lar", "templo", 1], ["Deus#2", "Senhor", "Rei", "Pai", 2]],
  ["Ester 4:14", "Quem sabe se não foi para uma ocasião como esta que você chegou à posição de rainha?", ["rainha", "serva", "viúva", "princesa", 2]],
  ["Jó 19:25", "Eu sei que o meu Redentor vive, e que no fim se levantará sobre a terra.", ["Redentor", "Pastor", "Rei", "Juiz", 3], ["vive", "chega", "canta", "vê", 3]],
  ["Salmos 1:1", "Como é feliz aquele que não segue o conselho dos ímpios, não imita a conduta dos pecadores nem se assenta na roda dos zombadores!", ["conselho", "templo", "caminho#2", "mercado", 3]],
  ["Salmos 4:8", "Em paz me deito e logo adormeço, pois só tu, Senhor, me fazes viver em segurança.", ["paz", "pé", "luz", "oração", 2]],
  ["Salmos 18:2", "O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus é o meu rochedo, em quem me refugio.", ["rocha", "estrela", "casa", "cidade", 2], ["libertador", "carpinteiro", "caminho", "pastor", 3]],
  ["Salmos 19:1", "Os céus declaram a glória de Deus, e o firmamento proclama a obra das suas mãos.", ["glória", "força", "bondade", "lei", 2], ["firmamento", "deserto", "mar", "monte", 3]],
  ["Salmos 23:4", "Mesmo que eu ande por um vale de trevas e morte, não temerei perigo algum, pois tu estás comigo; a tua vara e o teu cajado me protegem.", ["comigo", "perto", "presente", "acima", 1], ["vale", "monte", "rio", "deserto", 1], ["cajado", "escudo", "manto", "pão", 2]],
  ["Salmos 24:1", "Do Senhor é a terra e tudo o que nela existe, o mundo e todos os que nele vivem.", ["terra", "luz", "vida", "casa", 2]],
  ["Salmos 34:8", "Provem e vejam como o Senhor é bom. Como é feliz o homem que nele se refugia!", ["bom", "justo", "forte", "grande", 1], ["refugia", "esquece", "orgulha", "cansa", 3]],
  ["Salmos 34:18", "O Senhor está perto dos que têm o coração quebrantado e salva os de espírito abatido.", ["quebrantado", "alegre", "puro", "forte", 3]],
  ["Salmos 37:4", "Deleite-se no Senhor, e ele atenderá aos desejos do seu coração.", ["coração", "povo", "tempo", "caminho", 2]],
  ["Salmos 42:1", "Assim como a corça anseia por águas correntes, a minha alma anseia por ti, ó Deus.", ["corça", "águia", "ovelha", "pomba", 2], ["águas", "colinas", "campos", "estrelas", 3]],
  ["Salmos 51:10", "Cria em mim um coração puro, ó Deus, e renova dentro de mim um espírito estável.", ["puro", "forte", "novo", "grande", 3], ["renova", "guarda", "constrói", "visita", 3]],
  ["Salmos 55:22", "Lance o seu fardo sobre o Senhor, e ele o susterá; jamais permitirá que o justo venha a cair.", ["susterá", "esquecerá", "levará", "chamará", 3]],
  ["Salmos 90:12", "Ensina-nos a contar os nossos dias, para que o nosso coração alcance sabedoria.", ["dias", "bens", "passos", "erros", 3]],
  ["Salmos 91:1", "Aquele que habita no abrigo do Altíssimo e descansa à sombra do Todo-poderoso.", ["sombra", "casa", "mão", "luz", 2]],
  ["Salmos 96:1", "Cantem ao Senhor um novo cântico; cante ao Senhor, toda a terra!", ["cântico", "sacrifício", "pedido", "grito", 1], ["novo", "antigo", "longo", "triste", 1]],
  ["Salmos 100:1", "Aclamem o Senhor, todas as terras!", ["terras", "nações", "casas", "tribos", 3]],
  ["Salmos 111:10", "O temor do Senhor é o princípio da sabedoria; todos os que cumprem os seus preceitos revelam bom senso.", ["temor", "amor", "nome", "dia", 2], ["sabedoria", "riqueza", "guerra", "vitória", 2]],
  ["Salmos 118:24", "Este é o dia em que o Senhor agiu; alegremo-nos e regozijemo-nos nele.", ["dia", "tempo", "monte", "povo", 1]],
  ["Salmos 121:2", "O meu socorro vem do Senhor, que fez os céus e a terra.", ["socorro", "poder", "descanso", "pão", 2], ["céus", "montes", "rios", "campos", 2]],
  ["Salmos 122:1", "Alegrei-me quando me disseram: Vamos à casa do Senhor.", ["Alegrei-me", "Cansei-me", "Assustei-me", "Calei-me", 2]],
  ["Salmos 127:1", "Se o Senhor não edificar a casa, em vão trabalham os construtores.", ["edificar", "visitar", "guardar", "ver", 3], ["vão", "paz", "pressa", "tempo", 3]],
  ["Salmos 136:1", "Deem graças ao Senhor, porque ele é bom. O seu amor dura para sempre.", ["sempre", "pouco", "um dia", "o inverno", 1]],
  ["Salmos 145:18", "O Senhor está perto de todos os que o invocam, de todos os que o invocam com sinceridade.", ["invocam", "ignoram", "temem", "seguem", 3]],
  ["Salmos 147:3", "Ele cura os de coração quebrantado e cuida das suas feridas.", ["quebrantado", "endurecido", "alegre", "puro", 3], ["feridas", "cordas", "vestes", "lágrimas", 3]],
  ["Provérbios 1:7", "O temor do Senhor é o princípio do conhecimento, mas os insensatos desprezam a sabedoria e a disciplina.", ["princípio", "fim", "caminho", "dom", 2], ["desprezam", "buscam", "guardam", "amam", 3]],
  ["Provérbios 3:6", "Reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas.", ["caminhos", "dias", "passos", "tempos", 2], ["endireitará", "esquecerá", "cobrirá", "contará", 3]],
  ["Provérbios 4:23", "Acima de tudo, guarde o seu coração, pois dele procedem as fontes da vida.", ["coração", "tesouro", "corpo", "nome", 2], ["fontes", "caminhos", "dias", "frutos", 3]],
  ["Provérbios 9:10", "O temor do Senhor é o princípio da sabedoria, e o conhecimento do Santo é entendimento.", ["princípio", "fim", "pão", "caminho", 2]],
  ["Provérbios 10:12", "O ódio provoca brigas, mas o amor encobre todas as transgressões.", ["ódio", "riso", "sono", "sol", 2]],
  ["Provérbios 17:17", "O amigo ama em todo o tempo; para as horas de adversidade nasce o irmão.", ["amigo", "pobre", "povo", "sábio", 2], ["adversidade", "festa", "viagem", "colheita", 3]],
  ["Eclesiastes 12:1", "Lembre-se do seu Criador nos dias da sua juventude, antes que venham os dias difíceis…", ["Criador", "Pastor", "Rei", "Mestre", 2]],
  ["Isaías 9:6", "Pois um menino nos nasceu, um filho nos foi dado, e o governo estará sobre os seus ombros.", ["menino", "profeta", "rei", "anjo", 1], ["nasceu", "caiu", "partiu", "chorou", 1]],
  ["Isaías 26:3", "Tu guardarás em perfeita paz aquele cujo propósito está firme, porque em ti confia.", ["paz", "luz", "vida", "força", 2], ["propósito", "caminho", "passo", "nome", 3]],
  ["Isaías 40:31", "Mas aqueles que esperam no Senhor renovam as suas forças. Voam alto como águias; correm e não ficam exaustos, andam e não se cansam.", ["águias", "pombas", "anjos", "falcões", 2], ["esperam", "temem", "buscam", "negam", 2]],
  ["Isaías 41:13", "Pois eu sou o Senhor, o seu Deus, que o segura pela mão direita e lhe diz: Não tema; eu o ajudarei.", ["direita", "esquerda", "pequena", "fraca", 2]],
  ["Isaías 53:5", "O castigo que nos trouxe paz estava sobre ele, e pelas suas feridas fomos curados.", ["castigo", "prêmio", "pão", "cântico", 3], ["feridas", "cordas", "vestes", "lágrimas", 3], ["curados", "guardados", "lavados", "aceitos", 2], ["paz", "luz", "vida", "força", 1]],
  ["Isaías 55:6", "Busquem o Senhor enquanto é possível achá-lo; invoquem-no enquanto está perto.", ["perto", "cansado", "dormindo", "longe", 2], ["Busquem", "Esqueçam", "Deixem", "Evitem", 2]],
  ["Jeremias 29:13", "Vocês me procurarão e me acharão quando me procurarem de todo o coração.", ["coração", "tempo", "povo", "caminho", 2], ["procurarem", "esquecerem", "ouvirem", "temerem", 2]],
  ["Jeremias 33:3", "Clame a mim e responderei e lhe direi coisas grandes e insondáveis que você não conhece.", ["grandes", "novas", "antigas", "simples", 3], ["insondáveis", "pequenas", "simples", "antigas", 3], ["Clame", "Cale", "Fuja", "Corra", 2]],
  ["Ezequiel 36:26", "Darei a vocês um coração novo e porei em vocês um espírito novo; tirarei de vocês o coração de pedra e darei a vocês um coração de carne.", ["pedra", "ferro", "ouro", "barro", 2], ["novo", "velho", "forte", "grande", 2]],
  ["Miqueias 6:8", "Ele mostrou a você, ó homem, o que é bom e o que o Senhor exige de você: Pratique a justiça, ame a fidelidade e ande humildemente com o seu Deus.", ["humildemente", "lentamente", "sozinho", "firmemente", 3], ["justiça", "riqueza", "vitória", "guerra", 3], ["fidelidade", "riqueza", "vitória", "guerra", 3]],
  ["Zacarias 4:6", "Não por força nem por poder, mas pelo meu Espírito, diz o Senhor dos Exércitos.", ["Espírito", "nome", "povo", "braço", 2], ["força", "pressa", "ouro", "muros", 2]],
  ["Mateus 4:19", "Venham, sigam-me, e eu os farei pescadores de homens.", ["homens", "peixes", "reis", "ovelhas", 1], ["pescadores", "pastores", "soldados", "mestres", 1]],
  ["Mateus 5:3", "Bem-aventurados os pobres em espírito, pois deles é o Reino dos céus.", ["pobres", "fracos", "simples", "tristes", 2], ["Reino", "templo", "caminho", "tesouro", 1]],
  ["Mateus 5:4", "Bem-aventurados os que choram, pois serão consolados.", ["choram", "riem", "correm", "dormem", 2], ["consolados", "esquecidos", "castigados", "ricos", 2]],
  ["Mateus 5:6", "Bem-aventurados os que têm fome e sede de justiça, pois serão satisfeitos.", ["justiça", "poder", "ouro", "fama", 2]],
  ["Mateus 5:7", "Bem-aventurados os misericordiosos, pois obterão misericórdia.", ["misericordiosos", "orgulhosos", "ricos", "rápidos", 2]],
  ["Mateus 5:8", "Bem-aventurados os puros de coração, pois verão a Deus.", ["verão", "temerão", "esquecerão", "ouvirão", 2]],
  ["Mateus 5:9", "Bem-aventurados os pacificadores, pois serão chamados filhos de Deus.", ["pacificadores", "mansos", "puros", "humildes", 2], ["filhos", "servos", "amigos", "irmãos", 2]],
  ["Mateus 5:14", "Vocês são a luz do mundo. Uma cidade construída sobre um monte não pode ser escondida.", ["luz", "voz", "paz", "força", 1], ["monte", "rio", "deserto", "vale", 2]],
  ["Mateus 6:9", "Pai nosso, que estás nos céus! Santificado seja o teu nome.", ["céus", "montes", "campos", "mares", 1]],
  ["Mateus 6:11", "Dá-nos hoje o nosso pão de cada dia.", ["pão", "vinho", "mel", "azeite", 1], ["hoje", "amanhã", "sempre", "ontem", 1]],
  ["Mateus 6:21", "Pois onde seu tesouro estiver, ali também estará seu coração.", ["tesouro", "lar", "trabalho", "amigo", 2], ["coração", "sono", "pé", "nome", 1]],
  ["Mateus 7:12", "Em tudo, façam aos outros o que vocês querem que eles lhes façam, pois esta é a Lei e os Profetas.", ["façam", "digam", "deem", "paguem", 3], ["Profetas", "Reis", "Juízes", "Anjos", 2]],
  ["Mateus 11:29", "Tomem sobre vocês o meu jugo e aprendam de mim…", ["jugo", "manto", "cajado", "pão", 3]],
  ["Mateus 18:20", "Pois onde se reunirem dois ou três em meu nome, ali eu estou no meio deles.", ["nome", "templo", "altar", "caminho", 2], ["três", "cinco", "dez", "doze", 2]],
  ["Mateus 22:37", "Ame o Senhor, o seu Deus, de todo o seu coração, de toda a sua alma e de todo o seu entendimento.", ["entendimento", "poder", "tempo", "desejo", 2], ["alma", "casa", "voz", "força", 2]],
  ["Mateus 26:41", "Vigiem e orem para que não caiam em tentação. O espírito está pronto, mas a carne é fraca.", ["fraca", "forte", "rica", "cansada", 2]],
  ["Mateus 28:19", "Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai e do Filho e do Espírito Santo.", ["discípulos", "soldados", "mestres", "irmãos", 1], ["nações", "cidades", "casas", "ilhas", 1], ["batizando-os", "ensinando-os", "vestindo-os", "guardando-os", 2]],
  ["Marcos 1:15", "O tempo é chegado. O Reino de Deus está próximo. Arrependam-se e creiam nas boas-novas!", ["próximo", "distante", "escondido", "fechado", 2], ["Arrependam-se", "Alegrem-se", "Levantem-se", "Calem-se", 2]],
  ["Marcos 8:36", "Pois, que adianta ao homem ganhar o mundo inteiro e perder a sua alma?", ["alma", "casa", "fama", "vida longa", 3], ["mundo", "reino", "ouro", "povo", 2]],
  ["Marcos 9:23", "Se você pode? Tudo é possível àquele que crê.", ["crê", "pede", "corre", "espera", 2], ["possível", "difícil", "demorado", "oculto", 2]],
  ["Marcos 16:15", "Vão pelo mundo todo e preguem o evangelho a todas as pessoas.", ["mundo", "país", "povo", "deserto", 1]],
  ["Lucas 1:37", "Pois nada é impossível para Deus.", ["impossível", "difícil", "demorado", "oculto", 1], ["nada", "tudo", "pouco", "muito", 1]],
  ["Lucas 6:36", "Sejam misericordiosos, assim como o Pai de vocês é misericordioso.", ["misericordiosos", "orgulhosos", "ricos", "rápidos", 2], ["Pai", "Rei", "Mestre", "Pastor", 2]],
  ["Lucas 19:10", "Pois o Filho do homem veio buscar e salvar o que estava perdido.", ["perdido", "fraco", "pobre", "doente", 2], ["buscar", "julgar", "ensinar", "vender", 2], ["salvar", "julgar", "ensinar", "vender", 2]],
  ["Lucas 24:6", "Ele não está aqui; ressuscitou!", ["ressuscitou", "dormiu", "partiu", "chorou", 1], ["aqui", "lá", "perto", "dentro", 1]],
  ["João 1:14", "A Palavra tornou-se carne e viveu entre nós. Vimos a sua glória, glória como do Unigênito vindo do Pai, cheio de graça e de verdade.", ["carne", "luz", "pão", "homem", 2], ["graça", "ouro", "força", "poder", 2]],
  ["João 3:17", "Pois Deus enviou o seu Filho ao mundo, não para condenar o mundo, mas para que este fosse salvo por meio dele.", ["salvo", "julgado", "curado", "ensinado", 3], ["condenar", "abençoar", "visitar", "ensinar", 3]],
  ["João 4:24", "Deus é espírito, e é necessário que os seus adoradores o adorem em espírito e em verdade.", ["espírito", "fogo", "luz", "rei", 2], ["adoradores", "servos", "filhos", "amigos", 3]],
  ["João 6:35", "Eu sou o pão da vida. Aquele que vem a mim nunca terá fome; aquele que crê em mim nunca terá sede.", ["pão", "vinho", "mel", "azeite", 1], ["fome", "medo", "pressa", "sono", 2], ["sede", "frio", "calor", "sono", 2]],
  ["João 8:12", "Eu sou a luz do mundo. Quem me segue, nunca andará em trevas, mas terá a luz da vida.", ["luz", "voz", "paz", "porta", 1], ["trevas", "medo", "tristeza", "dúvida", 2], ["segue", "teme", "ouve", "vê", 2]],
  ["João 8:32", "Conhecerão a verdade, e a verdade os libertará.", ["verdade", "lei", "paz", "luz", 1], ["libertará", "ensinará", "guardará", "salvará", 2]],
  ["João 10:10", "O ladrão vem apenas para roubar, matar e destruir; eu vim para que tenham vida, e a tenham plenamente.", ["ladrão", "pastor", "rei", "mestre", 2], ["destruir", "ensinar", "visitar", "curar", 3], ["plenamente", "rapidamente", "raramente", "pouco", 2], ["roubar", "curar", "ensinar", "guardar", 3]],
  ["João 10:11", "Eu sou o bom pastor. O bom pastor dá a sua vida pelas ovelhas.", ["ovelhas", "cabras", "portas", "pastagens", 1], ["pastor", "rei", "mestre", "juiz", 1]],
  ["João 11:25", "Eu sou a ressurreição e a vida. Aquele que crê em mim, ainda que morra, viverá.", ["ressurreição", "verdade", "porta", "luz", 2], ["viverá", "dormirá", "esperará", "voltará", 2]],
  ["João 13:34", "Um novo mandamento lhes dou: Amem-se uns aos outros. Como eu os amei, vocês devem amar-se uns aos outros.", ["novo", "antigo", "grande", "primeiro", 2], ["Amem-se", "Ouçam-se", "Sigam-se", "Ajudem-se", 2]],
  ["João 14:6", "Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai, a não ser por mim.", ["caminho", "pastor", "pão", "mestre", 1], ["Pai", "céu", "templo", "reino", 2], ["verdade", "lei", "paz", "luz", 1]],
  ["João 14:27", "Deixo a paz com vocês; a minha paz lhes dou. Não a dou como o mundo a dá.", ["paz", "lei", "força", "glória", 1]],
  ["João 15:5", "Eu sou a videira; vocês são os ramos.", ["videira", "figueira", "oliveira", "palmeira", 1], ["ramos", "frutos", "raízes", "folhas", 1]],
  ["João 16:33", "Nesse mundo vocês terão aflições; mas tenham ânimo! Eu venci o mundo.", ["venci", "criei", "guardo", "amo", 2], ["aflições", "festas", "viagens", "colheitas", 2], ["ânimo", "pressa", "medo", "sono", 2]],
  ["João 20:29", "Felizes os que não viram e creram.", ["creram", "fugiram", "dormiram", "cantaram", 2], ["Felizes", "Tristes", "Cansados", "Sozinhos", 2]],
  ["Atos 1:8", "Mas receberão poder quando o Espírito Santo descer sobre vocês, e serão minhas testemunhas…", ["testemunhas", "discípulos", "servos", "mensageiros", 2], ["poder", "ouro", "pão", "descanso", 2]],
  ["Atos 4:12", "Não há salvação em nenhum outro, pois não há debaixo do céu nenhum outro nome dado entre os homens pelo qual devamos ser salvos.", ["salvação", "riqueza", "descanso", "vitória", 2], ["nome", "templo", "caminho", "rei", 2]],
  ["Atos 16:31", "Creia no Senhor Jesus, e serão salvos, você e todos os da sua casa.", ["casa", "terra", "tribo", "cidade", 1], ["Creia", "Fuja", "Espere", "Ouça", 1]],
  ["Romanos 1:16", "Não me envergonho do evangelho, porque ele é o poder de Deus para a salvação de todo aquele que crê…", ["envergonho", "orgulho", "esqueço", "cansei", 3], ["poder", "nome", "caminho", "livro", 2]],
  ["Romanos 3:23", "pois todos pecaram e estão destituídos da glória de Deus.", ["pecaram", "choraram", "oraram", "esperaram", 1], ["glória", "casa", "mão", "terra", 1]],
  ["Romanos 5:1", "Portanto, justificados mediante a fé, temos paz com Deus, por meio de nosso Senhor Jesus Cristo.", ["paz", "medo", "pressa", "dúvida", 1]],
  ["Romanos 5:8", "Mas Deus demonstra seu amor por nós: Cristo morreu em nosso favor quando ainda éramos pecadores.", ["amor", "poder", "juízo", "nome", 2], ["pecadores", "justos", "fiéis", "sábios", 2]],
  ["Romanos 6:23", "Pois o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor.", ["morte", "dor", "prisão", "fome", 2], ["salário", "prêmio", "caminho", "fruto", 2], ["gratuito", "caro", "oculto", "difícil", 3]],
  ["Romanos 8:1", "Portanto, agora já não há condenação para os que estão em Cristo Jesus.", ["condenação", "tristeza", "dívida", "separação", 3]],
  ["Romanos 10:9", "Se você confessar com a sua boca que Jesus é Senhor e crer em seu coração que Deus o ressuscitou dentre os mortos, será salvo.", ["ressuscitou", "enviou", "ungiu", "glorificou", 3], ["confessar", "negar", "esconder", "ouvir", 3], ["Senhor", "Rei", "Mestre", "Pastor", 1]],
  ["Romanos 12:2", "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente, para que sejam capazes de experimentar e comprovar a boa, agradável e perfeita vontade de Deus.", ["mente", "vida", "casa", "voz", 2], ["amoldem", "alegrem", "apressem", "cansem", 3]],
  ["Romanos 12:12", "Alegrem-se na esperança, sejam pacientes na tribulação, perseverem na oração.", ["oração", "fé", "obra", "jornada", 2], ["tribulação", "festa", "viagem", "colheita", 2]],
  ["Romanos 12:21", "Não se deixem vencer pelo mal, mas vençam o mal com o bem.", ["bem", "fogo", "ouro", "medo", 1], ["vencer", "ensinar", "levar", "guardar", 2]],
  ["Romanos 13:10", "O amor não faz mal ao próximo. Portanto, o amor é o cumprimento da Lei.", ["próximo", "inimigo", "pobre", "estrangeiro", 2], ["cumprimento", "esquecimento", "começo", "fim", 3], ["Lei", "festa", "ordem", "guerra", 2]],
  ["1 Coríntios 10:31", "Assim, quer vocês comam, bebam ou façam qualquer outra coisa, façam tudo para a glória de Deus.", ["glória", "fama", "paz", "força", 2]],
  ["1 Coríntios 13:4", "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.", ["paciente", "rápido", "forte", "sábio", 1], ["bondoso", "rápido", "forte", "sábio", 2], ["vangloria", "alegra", "cansa", "esconde", 3]],
  ["1 Coríntios 16:14", "Façam tudo com amor.", ["amor", "pressa", "calma", "cuidado", 1]],
  ["2 Coríntios 5:7", "Vivemos por fé, e não pelo que vemos.", ["fé", "medo", "pressa", "sorte", 1], ["vemos", "temos", "pedimos", "ouvimos", 2]],
  ["2 Coríntios 5:17", "Portanto, se alguém está em Cristo, é nova criação. As coisas antigas já passaram; eis que surgiram coisas novas!", ["antigas", "belas", "pequenas", "tristes", 2]],
  ["2 Coríntios 9:7", "Cada um dê conforme determinou em seu coração, não com pesar nem por obrigação, pois Deus ama quem dá com alegria.", ["alegria", "tristeza", "pressa", "medo", 1], ["ama", "teme", "ouve", "guarda", 1], ["pesar", "pressa", "medo", "calma", 3], ["obrigação", "festa", "vontade", "pressa", 3]],
  ["2 Coríntios 12:9", "Minha graça é suficiente a você, pois o meu poder se aperfeiçoa na fraqueza.", ["fraqueza", "riqueza", "pressa", "fartura", 2], ["aperfeiçoa", "esconde", "cansa", "acaba", 3]],
  ["Gálatas 5:1", "Foi para a liberdade que Cristo nos libertou. Portanto, permaneçam firmes e não se deixem submeter novamente a um jugo de escravidão.", ["liberdade", "riqueza", "festa", "paz", 2], ["escravidão", "alegria", "viagem", "pobreza", 2]],
  ["Gálatas 5:22", "Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade, mansidão e domínio próprio.", ["fidelidade", "orgulho", "ciúme", "ira", 2], ["alegria", "tristeza", "pressa", "dúvida", 1], ["paciência", "pressa", "ira", "dúvida", 2], ["mansidão", "orgulho", "ciúme", "ira", 2]],
  ["Gálatas 6:9", "E não nos cansemos de fazer o bem, pois no tempo próprio colheremos, se não desanimarmos.", ["cansemos", "alegremos", "apressemos", "calemos", 2], ["colheremos", "dormiremos", "partiremos", "venderemos", 3]],
  ["Efésios 2:8", "Pois vocês são salvos pela graça, por meio da fé, e isto não vem de vocês, é dom de Deus.", ["graça", "lei", "obra", "força", 2], ["fé", "pressa", "sorte", "fama", 2], ["dom", "preço", "castigo", "sonho", 2]],
  ["Efésios 4:32", "Sejam bondosos e compassivos uns para com os outros, perdoando-se mutuamente, assim como Deus os perdoou em Cristo.", ["perdoou", "chamou", "ensinou", "guardou", 3], ["compassivos", "orgulhosos", "apressados", "calados", 3]],
  ["Efésios 6:1", "Filhos, obedeçam a seus pais no Senhor, pois isto é justo.", ["pais", "mestres", "irmãos", "amigos", 1]],
  ["Efésios 6:11", "Vistam toda a armadura de Deus, para poderem ficar firmes contra as ciladas do diabo.", ["armadura", "força", "sabedoria", "paz", 2], ["ciladas", "festas", "estradas", "ofertas", 3]],
  ["Filipenses 1:6", "tendo plena convicção de que aquele que começou boa obra em vocês vai completá-la até o dia de Cristo Jesus.", ["completá-la", "esquecê-la", "vendê-la", "guardá-la", 3], ["começou", "terminou", "esqueceu", "escondeu", 2], ["convicção", "dúvida", "pressa", "vontade", 3]],
  ["Filipenses 4:4", "Alegrem-se sempre no Senhor. Novamente direi: Alegrem-se!", ["sempre", "pouco", "às vezes", "nunca", 1]],
  ["Filipenses 4:6", "Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, e com ação de graças, apresentem seus pedidos a Deus.", ["oração", "pressa", "fama", "riqueza", 2], ["ansiosos", "cansados", "tristes", "apressados", 2], ["súplicas", "festas", "viagens", "ofertas", 3], ["pedidos", "gritos", "bens", "planos", 2]],
  ["Colossenses 3:23", "Tudo o que fizerem, façam de todo o coração, como para o Senhor, e não para os homens.", ["coração", "tempo", "modo", "povo", 2], ["homens", "reis", "anjos", "filhos", 2]],
  ["1 Tessalonicenses 5:16", "Estejam sempre alegres, orem continuamente, deem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus.", ["graças", "ofertas", "ordens", "gritos", 2], ["vontade", "ordem", "pressa", "festa", 2], ["alegres", "tristes", "calados", "cansados", 1], ["continuamente", "raramente", "rapidamente", "tristemente", 2], ["circunstâncias", "festas", "viagens", "cidades", 3]],
  ["1 Timóteo 6:10", "Pois o amor ao dinheiro é a raiz de todos os males. Algumas pessoas, por cobiçarem o dinheiro, desviaram-se da fé e se atormentaram com muitos sofrimentos.", ["raiz", "fruto", "folha", "ramo", 3], ["dinheiro", "poder", "estudo", "trabalho", 2]],
  ["2 Timóteo 1:7", "Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio.", ["covardia", "pobreza", "tristeza", "dúvida", 2]],
  ["2 Timóteo 3:16", "Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça.", ["inspirada", "escrita", "guardada", "ouvida", 2], ["repreensão", "fama", "viagem", "festa", 3]],
  ["Hebreus 4:16", "Assim, aproximemo-nos do trono da graça com toda a confiança, a fim de recebermos misericórdia e encontrarmos graça que nos ajude no momento da necessidade.", ["trono", "muro", "templo", "altar", 2]],
  ["Hebreus 11:6", "Sem fé é impossível agradar a Deus, pois quem dele se aproxima precisa crer que ele existe e que recompensa aqueles que o buscam.", ["fé", "amor", "paz", "dinheiro", 2], ["agradar", "enganar", "ensinar", "vencer", 3]],
  ["Hebreus 13:8", "Jesus Cristo é o mesmo, ontem, hoje e para sempre.", ["mesmo", "maior", "único", "primeiro", 2]],
  ["Tiago 1:5", "Se algum de vocês tem falta de sabedoria, peça a Deus, que a todos dá livremente, de boa vontade; e lhe será concedida.", ["sabedoria", "coragem", "paz", "força", 2]],
  ["1 Pedro 5:7", "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.", ["ansiedade", "riqueza", "alegria", "história", 2], ["cuidado", "pressa", "medo", "sono", 2]],
  ["1 João 1:9", "Se confessarmos os nossos pecados, ele é fiel e justo para perdoar os nossos pecados e nos purificar de toda injustiça.", ["pecados", "sonhos", "medos", "planos", 2], ["fiel", "rápido", "forte", "cansado", 2], ["purificar", "castigar", "esquecer", "cobrar", 3]],
  ["1 João 4:8", "Quem não ama não conhece a Deus, porque Deus é amor.", ["amor", "luz", "vida", "paz", 1], ["conhece", "teme", "vê", "ouve", 2]],
  ["1 João 4:19", "Nós amamos porque ele nos amou primeiro.", ["primeiro", "muito", "assim", "também", 2], ["amamos", "tememos", "seguimos", "ouvimos", 1]],
  ["Apocalipse 3:20", "Eis que estou à porta e bato. Se alguém ouvir a minha voz e abrir a porta, entrarei, e cearemos juntos.", ["porta", "janela", "torre", "muralha", 1], ["bato", "durmo", "espero", "grito", 3]],
  ["Apocalipse 21:4", "Ele enxugará dos seus olhos toda lágrima. Não haverá mais morte, nem tristeza, nem choro, nem dor, pois a antiga ordem já passou.", ["lágrima", "poeira", "ferida", "mágoa", 2], ["morte", "noite", "fome", "guerra", 2]],
  ["Êxodo 14:14", "O Senhor lutará por vocês…", ["lutará", "falará", "andará", "cantará", 2]],
  ["Êxodo 20:12", "Honre seu pai e sua mãe, para que você tenha vida longa na terra que o Senhor, o seu Deus, lhe dá.", ["pai", "irmão", "avô", "tio", 1], ["mãe", "tia", "avó", "irmã", 1]],
  ["Deuteronômio 31:8", "O Senhor mesmo irá à sua frente e estará com você; ele nunca o deixará, nunca o abandonará. Não tenha medo! Não desanime!", ["frente", "lado", "costas", "volta", 2], ["abandonará", "esquecerá", "trairá", "entregará", 3], ["desanime", "corra", "grite", "pare", 2]],
  ["Salmos 27:14", "Espere no Senhor. Seja forte! Coragem! Espere no Senhor.", ["Coragem", "Calma", "Pressa", "Silêncio", 2], ["forte", "calmo", "rápido", "humilde", 1]],
  ["Provérbios 15:1", "A resposta calma desvia a fúria, mas a palavra ríspida desperta a ira.", ["calma", "rápida", "alta", "longa", 2], ["fúria", "fome", "sono", "dor", 3], ["ríspida", "bonita", "longa", "curta", 3]],
  ["Provérbios 16:3", "Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos.", ["Consagre", "Esconda", "Venda", "Esqueça", 3], ["planos", "amigos", "bens", "dias", 2]],
  ["Mateus 5:5", "Bem-aventurados os humildes, pois eles receberão a terra por herança.", ["humildes", "fortes", "ricos", "rápidos", 2], ["herança", "pressa", "sorte", "venda", 3]],
  ["Mateus 7:7", "Peçam, e lhes será dado; busquem, e encontrarão; batam, e a porta lhes será aberta.", ["Peçam", "Corram", "Cantem", "Fujam", 1], ["batam", "corram", "andem", "orem", 1], ["porta", "janela", "casa", "mesa", 1]],
  ["Mateus 9:37", "A colheita é grande, mas os trabalhadores são poucos.", ["colheita", "casa", "rede", "tenda", 2], ["trabalhadores", "pastores", "soldados", "pescadores", 2]],
  ["Mateus 25:40", "O Rei responderá: Digo a verdade: o que vocês fizeram a algum dos meus menores irmãos, a mim o fizeram.", ["menores", "maiores", "ricos", "sábios", 3], ["Rei", "Juiz", "Mestre", "Pastor", 2]],
  ["Atos 2:38", "Arrependam-se e sejam batizados, cada um de vocês, em nome de Jesus Cristo, para perdão dos seus pecados. E receberão o dom do Espírito Santo.", ["Arrependam-se", "Esperem", "Escutem", "Vigiem", 2], ["perdão", "lembrança", "festa", "viagem", 3]],
  ["1 Coríntios 15:58", "Portanto, meus amados irmãos, mantenham-se firmes, e que nada os abale. Sejam sempre dedicados à obra do Senhor, pois vocês sabem que o seu trabalho no Senhor não será inútil.", ["firmes", "rápidos", "calados", "tristes", 2], ["inútil", "curto", "fácil", "pequeno", 3]],
  ["Filipenses 4:19", "O meu Deus suprirá todas as necessidades de vocês, segundo as suas gloriosas riquezas em Cristo Jesus.", ["necessidades", "dívidas", "tarefas", "festas", 3], ["riquezas", "pobrezas", "pressas", "dúvidas", 2]],
  ["Tiago 1:22", "Não se limitem apenas a ouvir a palavra, pois assim vocês se enganarão. Façam o que ela diz.", ["Façam", "Esqueçam", "Vendam", "Contem", 2], ["ouvir", "falar", "escrever", "cantar", 2]],
  ["Tiago 4:8", "Aproximem-se de Deus, e ele se aproximará de vocês.", ["Aproximem-se", "Afastem-se", "Escondam-se", "Calem-se", 1], ["aproximará", "afastará", "calará", "levantará", 2]],
  ["1 Pedro 4:8", "Sobretudo, amem-se sinceramente uns aos outros, porque o amor perdoa muitíssimos pecados.", ["sinceramente", "rapidamente", "raramente", "tristemente", 3], ["perdoa", "esconde", "conta", "mostra", 3]],
  ["Salmos 139:14", "Eu te louvo porque me fizeste de modo especial e admirável. Tuas obras são maravilhosas! Disso tenho plena certeza.", ["admirável", "pequeno", "simples", "comum", 3], ["especial", "fraco", "pequeno", "simples", 2]],
  ["Provérbios 13:20", "Quem anda com os sábios será sábio, mas o companheiro dos tolos acabará mal.", ["sábios", "ricos", "fortes", "jovens", 1], ["tolos", "reis", "amigos", "pobres", 2]],
  ["Provérbios 14:30", "O coração tranquilo dá vida ao corpo, mas a inveja apodrece os ossos.", ["inveja", "pressa", "raiva", "fome", 2], ["tranquilo", "duro", "triste", "agitado", 3]],
  ["Provérbios 25:28", "Como uma cidade com muros derrubados, assim é quem não sabe dominar-se.", ["muros", "torres", "portas", "casas", 2], ["dominar-se", "esconder-se", "apressar-se", "calar-se", 3], ["cidade", "casa", "aldeia", "torre", 1]],
  ["Mateus 5:16", "Assim brilhe a luz de vocês diante dos homens, para que vejam as suas boas obras e glorifiquem ao Pai de vocês, que está nos céus.", ["brilhe", "apague", "esconda", "durma", 2], ["boas obras", "bons planos", "belas casas", "grandes festas", 2], ["Pai", "Rei", "Mestre", "Senhor", 1]],
];

function build(): VerseItem[] {
  const out: VerseItem[] = [];
  for (const [ref, text, ...blanks] of VERSES_DATA) {
    for (const [spec, w1, w2, w3, d] of blanks) {
      const [word, nth] = spec.split("#");
      let idx = -1;
      for (let n = Number(nth ?? 1); n > 0; n--) idx = text.indexOf(word, idx + 1);
      if (idx < 0) continue; // proteção: lacuna que não está no texto é ignorada
      // ajusta o nível pelo tamanho da palavra: curta e comum = fácil; longa = difícil
      const level: Level = d === 2 && word.length <= 4 ? 1 : d === 2 && word.length >= 11 ? 3 : d;
      out.push({
        ref,
        before: text.slice(0, idx).trim(),
        after: text.slice(idx + word.length).trim(),
        a: word,
        w: [w1, w2, w3],
        d: level,
      });
    }
  }
  return out;
}

export const VERSES_EXTRA: VerseItem[] = build();
