// Versículos extras do "Complete o Versículo" (Almeida Revista e Atualizada). Cada versículo é escrito uma vez e
// gera uma pergunta por lacuna. Textos longos que não tenho certeza de memória terminam em "…".
// Entram no FIM da lista (content.ts) para não mudar as partidas antigas.
import type { Level, VerseItem } from "./content";

/** [palavra da lacuna (use "palavra#2" para a 2ª ocorrência), 3 erradas, nível] */
type Blank = [string, string, string, string, Level];
type Verse = [ref: string, text: string, ...blanks: Blank[]];

const VERSES_DATA: Verse[] = [
  ["Gênesis 1:1", "No princípio, criou Deus os céus e a terra.", ["céus", "mares", "anjos", "montes", 1], ["princípio", "caminho", "dilúvio", "silêncio", 1]],
  ["Gênesis 1:27", "Criou Deus, pois, o homem à sua imagem, à imagem de Deus o criou; homem e mulher os criou.", ["imagem", "força", "glória", "sombra", 1], ["mulher", "criança", "anjo", "pastor", 1]],
  ["Gênesis 50:20", "Vós, na verdade, intentastes o mal contra mim, porém Deus o tornou em bem, para fazer, como vedes agora, que se conserve muita gente em vida.", ["bem", "glória", "paz", "verdade", 3], ["intentastes", "pagastes", "devolvestes", "escondestes", 3]],
  ["Êxodo 3:14", "Disse Deus a Moisés: EU SOU O QUE SOU.", ["SOU#1", "FUI", "SEREI", "VIM", 3]],
  ["Êxodo 14:14", "O Senhor pelejará por vós, e vós vos calareis.", ["pelejará", "falará", "virá", "andará", 2], ["calareis", "cansareis", "alegrareis", "levantareis", 2]],
  ["Êxodo 20:3", "Não terás outros deuses diante de mim.", ["outros", "muitos", "falsos", "novos", 1], ["diante", "atrás", "dentro", "perto", 2]],
  ["Êxodo 20:12", "Honra teu pai e tua mãe, para que se prolonguem os teus dias na terra que o Senhor, teu Deus, te dá.", ["Honra", "Ouve", "Segue", "Teme", 1], ["dias", "anos", "filhos", "bens", 2]],
  ["Êxodo 33:14", "Respondeu o Senhor: A minha presença irá contigo, e eu te darei descanso.", ["presença", "palavra", "glória", "voz", 3], ["descanso", "vitória", "riqueza", "coragem", 2]],
  ["Levítico 19:18", "Amarás o teu próximo como a ti mesmo. Eu sou o Senhor.", ["próximo", "inimigo", "vizinho", "irmão", 2], ["Amarás", "Servirás", "Seguirás", "Ouvirás", 2]],
  ["Números 6:24", "O Senhor te abençoe e te guarde;", ["abençoe", "ensine", "console", "visite", 2], ["guarde", "chame", "mostre", "espere", 2]],
  ["Deuteronômio 6:4", "Ouve, Israel, o Senhor, nosso Deus, é o único Senhor.", ["Ouve", "Vê", "Corre", "Canta", 2], ["único", "maior", "primeiro", "eterno", 3]],
  ["Deuteronômio 6:5", "Amarás, pois, o Senhor, teu Deus, de todo o teu coração, de toda a tua alma e de todas as tuas forças.", ["forças", "obras", "palavras", "riquezas", 2], ["alma", "casa", "voz", "mente", 2]],
  ["Deuteronômio 31:8", "O Senhor mesmo é quem vai adiante de ti; ele será contigo, não te deixará, nem te desamparará; não temas, nem te atemorizes.", ["adiante", "atrás", "perto", "longe", 3], ["desamparará", "esquecerá", "trairá", "entregará", 3]],
  ["Josué 24:15", "Eu e a minha casa serviremos ao Senhor.", ["serviremos", "temeremos", "buscaremos", "seguiremos", 2], ["casa", "tribo", "família", "cidade", 3]],
  ["Rute 1:16", "O teu povo é o meu povo, o teu Deus é o meu Deus.", ["povo", "rei", "lar", "templo", 1], ["Deus#2", "Senhor", "Rei", "Pai", 2]],
  ["Ester 4:14", "Quem sabe se para conjuntura como esta é que foste elevada a rainha?", ["conjuntura", "viagem", "festa", "guerra", 3], ["rainha", "serva", "viúva", "princesa", 2]],
  ["Neemias 8:10", "A alegria do Senhor é a vossa força.", ["alegria", "paz", "palavra", "glória", 1], ["força", "casa", "vida", "luz", 1]],
  ["Jó 1:21", "Nu saí do ventre de minha mãe, e nu voltarei; o Senhor o deu, o Senhor o tomou; bendito seja o nome do Senhor!", ["tomou", "guardou", "ouviu", "trouxe", 2], ["bendito", "louvado", "grande", "santo", 3]],
  ["Jó 19:25", "Porque eu sei que o meu Redentor vive e por fim se levantará sobre a terra.", ["Redentor", "Pastor", "Rei", "Juiz", 3], ["vive", "chega", "canta", "vê", 3]],
  ["Salmos 1:1", "Bem-aventurado o homem que não anda no conselho dos ímpios, não se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores.", ["conselho", "templo", "caminho#2", "mercado", 3], ["escarnecedores", "ladrões", "soberbos", "sábios", 3]],
  ["Salmos 4:8", "Em paz me deito e logo pego no sono, porque, Senhor, só tu me fazes repousar seguro.", ["paz", "pé", "luz", "oração", 2], ["sono", "canto", "cajado", "trabalho", 2]],
  ["Salmos 18:2", "O Senhor é a minha rocha, o meu baluarte, o meu libertador;", ["rocha", "estrela", "casa", "cidade", 2], ["libertador", "carpinteiro", "caminho", "pastor", 3]],
  ["Salmos 19:1", "Os céus proclamam a glória de Deus, e o firmamento anuncia as obras das suas mãos.", ["glória", "força", "bondade", "lei", 2], ["firmamento", "deserto", "mar", "monte", 3]],
  ["Salmos 23:4", "Ainda que eu ande pelo vale da sombra da morte, não temerei mal nenhum, porque tu estás comigo; o teu bordão e o teu cajado me consolam.", ["comigo", "perto", "presente", "acima", 1], ["vale", "monte", "rio", "deserto", 1], ["cajado", "escudo", "manto", "pão", 2]],
  ["Salmos 23:6", "Bondade e misericórdia certamente me seguirão todos os dias da minha vida; e habitarei na Casa do Senhor para todo o sempre.", ["seguirão", "cercarão", "guardarão", "abençoarão", 3], ["habitarei", "dormirei", "cantarei", "voltarei", 3]],
  ["Salmos 24:1", "Ao Senhor pertence a terra e tudo o que nela se contém, o mundo e aqueles que nele habitam.", ["pertence", "obedece", "agradece", "responde", 3], ["terra", "luz", "vida", "casa", 2]],
  ["Salmos 27:14", "Espera no Senhor, tem bom ânimo, e fortifique-se o teu coração; espera, pois, no Senhor.", ["Espera", "Corre", "Canta", "Cala", 2], ["ânimo", "sono", "pão", "tempo", 2]],
  ["Salmos 34:8", "Provai e vede que o Senhor é bom; bem-aventurado o homem que nele se refugia.", ["bom", "justo", "forte", "grande", 1], ["Provai", "Cantai", "Pedi", "Correi", 2], ["refugia", "esquece", "orgulha", "cansa", 3]],
  ["Salmos 34:18", "Perto está o Senhor dos que têm o coração quebrantado e salva os de espírito oprimido.", ["Perto", "Longe", "Acima", "Atrás", 2], ["quebrantado", "alegre", "puro", "forte", 3]],
  ["Salmos 37:4", "Agrada-te do Senhor, e ele satisfará os desejos do teu coração.", ["coração", "povo", "tempo", "caminho", 2], ["satisfará", "esquecerá", "fechará", "pesará", 3]],
  ["Salmos 42:1", "Como suspira a corça pelas correntes das águas, assim, por ti, ó Deus, suspira a minha alma.", ["corça", "águia", "ovelha", "pomba", 2], ["águas", "colinas", "campos", "estrelas", 3]],
  ["Salmos 46:10", "Aquietai-vos e sabei que eu sou Deus;", ["Aquietai-vos", "Levantai-vos", "Apressai-vos", "Alegrai-vos", 2], ["sabei", "vede", "ouvi", "crede", 3]],
  ["Salmos 51:10", "Cria em mim, ó Deus, um coração puro, e renova dentro de mim um espírito inabalável.", ["puro", "forte", "novo", "grande", 3], ["renova", "guarda", "constrói", "visita", 3]],
  ["Salmos 55:22", "Confia os teus cuidados ao Senhor, e ele te susterá;", ["cuidados", "bens", "planos", "passos", 3], ["susterá", "esquecerá", "levará", "chamará", 3]],
  ["Salmos 90:12", "Ensina-nos a contar os nossos dias, para que alcancemos coração sábio.", ["dias", "bens", "passos", "erros", 3], ["sábio", "grande", "forte", "rico", 2]],
  ["Salmos 91:1", "Aquele que habita no esconderijo do Altíssimo e descansa à sombra do Onipotente.", ["esconderijo", "templo", "monte", "palácio", 3], ["sombra", "casa", "mão", "luz", 2]],
  ["Salmos 92:1", "Bom é render graças ao Senhor e cantar louvores ao teu nome, ó Altíssimo;", ["graças", "ofertas", "orações", "sacrifícios", 3], ["louvores", "lamentos", "pedidos", "medos", 2]],
  ["Salmos 95:6", "Vinde, adoremos e prostremo-nos; ajoelhemos diante do Senhor, que nos criou.", ["adoremos", "corramos", "durmamos", "partamos", 2], ["criou", "guiou", "chamou", "salvou", 2]],
  ["Salmos 96:1", "Cantai ao Senhor um cântico novo; cantai ao Senhor, todas as terras.", ["cântico", "sacrifício", "pedido", "grito", 1], ["novo", "antigo", "longo", "triste", 1]],
  ["Salmos 98:1", "Cantai ao Senhor um cântico novo, porque ele tem feito maravilhas.", ["maravilhas", "castelos", "caminhos", "muros", 2]],
  ["Salmos 100:1", "Celebrai com júbilo ao Senhor, todas as terras.", ["júbilo", "pressa", "temor", "silêncio", 3], ["terras", "nações", "casas", "tribos", 3]],
  ["Salmos 103:2", "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios.", ["Bendize", "Cala", "Foge", "Corre", 2], ["esqueças", "afastes", "cales", "canses", 3]],
  ["Salmos 111:10", "O temor do Senhor é o princípio da sabedoria;", ["temor", "amor", "nome", "dia", 2], ["sabedoria", "riqueza", "guerra", "vitória", 2]],
  ["Salmos 118:24", "Este é o dia que o Senhor fez; regozijemo-nos e alegremo-nos nele.", ["fez", "deu", "ouviu", "guardou", 1], ["dia", "tempo", "monte", "povo", 1]],
  ["Salmos 119:130", "A entrada das tuas palavras clareia e dá entendimento aos simples.", ["clareia", "esconde", "cansa", "pesa", 3], ["entendimento", "tesouro", "descanso", "pão", 3]],
  ["Salmos 121:2", "O meu socorro vem do Senhor, que fez os céus e a terra.", ["socorro", "poder", "descanso", "pão", 2], ["céus", "montes", "rios", "campos", 2]],
  ["Salmos 122:1", "Alegrei-me quando me disseram: Vamos à Casa do Senhor.", ["Alegrei-me", "Cansei-me", "Assustei-me", "Calei-me", 2], ["Casa", "Cidade", "Montanha", "Festa", 2]],
  ["Salmos 127:1", "Se o Senhor não edificar a casa, em vão trabalham os que a edificam;", ["edificar", "visitar", "guardar", "ver", 3], ["vão", "paz", "pressa", "tempo", 3]],
  ["Salmos 136:1", "Rendei graças ao Senhor, porque ele é bom, porque a sua misericórdia dura para sempre.", ["misericórdia", "justiça", "glória", "palavra", 2], ["sempre", "pouco", "um dia", "o inverno", 1]],
  ["Salmos 145:18", "Perto está o Senhor de todos os que o invocam, de todos os que o invocam em verdade.", ["invocam", "ignoram", "temem", "seguem", 3], ["verdade", "segredo", "paz", "voz", 3]],
  ["Salmos 147:3", "Sara os de coração quebrantado e lhes ata as feridas.", ["quebrantado", "endurecido", "alegre", "puro", 3], ["feridas", "cordas", "vestes", "lágrimas", 3]],
  ["Salmos 150:6", "Tudo quanto tem fôlego louve ao Senhor. Aleluia!", ["fôlego", "voz", "vida", "forma", 2], ["Aleluia", "Amém", "Hosana", "Glória", 1]],
  ["Provérbios 1:7", "O temor do Senhor é o princípio do saber, mas os loucos desprezam a sabedoria e a instrução.", ["princípio", "fim", "caminho", "dom", 2], ["desprezam", "buscam", "guardam", "amam", 3]],
  ["Provérbios 3:6", "Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.", ["caminhos", "dias", "passos", "tempos", 2], ["endireitará", "esquecerá", "cobrirá", "contará", 3]],
  ["Provérbios 4:23", "Acima de tudo que guardares, guarda o coração, porque dele procedem as fontes da vida.", ["coração", "tesouro", "corpo", "nome", 2], ["fontes", "caminhos", "dias", "frutos", 3]],
  ["Provérbios 9:10", "O temor do Senhor é o princípio da sabedoria, e o conhecimento do Santo é prudência.", ["princípio", "fim", "pão", "caminho", 2], ["prudência", "pobreza", "tristeza", "pressa", 3]],
  ["Provérbios 10:12", "O ódio excita contendas, mas o amor cobre todas as transgressões.", ["ódio", "riso", "sono", "sol", 2], ["cobre", "conta", "mostra", "revela", 3]],
  ["Provérbios 15:1", "A resposta branda desvia o furor, mas a palavra dura suscita a ira.", ["branda", "rápida", "sábia", "alta", 2], ["furor", "sono", "caminho", "perigo", 3]],
  ["Provérbios 16:3", "Confia ao Senhor as tuas obras, e teus desígnios serão estabelecidos.", ["obras", "dívidas", "lutas", "viagens", 3], ["desígnios", "inimigos", "amigos", "bens", 3]],
  ["Provérbios 17:17", "Em todo o tempo ama o amigo, e na angústia se faz o irmão.", ["amigo", "pobre", "povo", "sábio", 2], ["angústia", "festa", "viagem", "casa", 2]],
  ["Eclesiastes 4:9", "Melhor é serem dois do que um, porque têm melhor paga do seu trabalho.", ["dois", "três", "cem", "mil", 1], ["trabalho", "descanso", "caminho", "sono", 2]],
  ["Eclesiastes 12:1", "Lembra-te também do teu Criador nos dias da tua mocidade, antes que venham os maus dias…", ["Criador", "Pastor", "Rei", "Mestre", 2], ["mocidade", "viagem", "colheita", "riqueza", 2]],
  ["Isaías 1:18", "Vinde, pois, e arrazoemos, diz o Senhor; ainda que os vossos pecados sejam como a escarlata, eles se tornarão brancos como a neve…", ["neve", "areia", "pedra", "nuvem", 3], ["escarlata", "areia", "cinza", "terra", 3]],
  ["Isaías 9:6", "Porque um menino nos nasceu, um filho se nos deu…", ["menino", "profeta", "rei", "anjo", 1], ["nasceu", "caiu", "partiu", "chorou", 1]],
  ["Isaías 26:3", "Tu, Senhor, guardarás em perfeita paz aquele cujo propósito está firme em ti, porque ele confia em ti.", ["paz", "luz", "vida", "força", 2], ["propósito", "caminho", "passo", "nome", 3]],
  ["Isaías 40:31", "Mas os que esperam no Senhor renovam as suas forças, sobem com asas como águias, correm e não se cansam, caminham e não se fatigam.", ["águias", "pombas", "anjos", "falcões", 2], ["esperam", "temem", "buscam", "negam", 2], ["fatigam", "perdem", "afastam", "assustam", 3]],
  ["Isaías 41:13", "Porque eu, o Senhor, teu Deus, te tomo pela tua mão direita e te digo: Não temas, que eu te ajudo.", ["direita", "esquerda", "pequena", "fraca", 2], ["ajudo", "guardo", "visito", "sigo", 2]],
  ["Isaías 53:5", "O castigo que nos traz a paz estava sobre ele, e pelas suas pisaduras fomos sarados.", ["sarados", "guardados", "lavados", "aceitos", 3], ["castigo", "prêmio", "pão", "cântico", 3]],
  ["Isaías 55:6", "Buscai o Senhor enquanto se pode achar, invocai-o enquanto está perto.", ["Buscai", "Esquecei", "Deixai", "Evitai", 2], ["perto", "cansado", "dormindo", "longe", 2]],
  ["Jeremias 29:13", "Buscar-me-eis e me achareis quando me buscardes de todo o vosso coração.", ["achareis", "perdereis", "ouvireis", "temereis", 2], ["coração", "tempo", "povo", "caminho", 2]],
  ["Jeremias 33:3", "Clama a mim, e responder-te-ei e anunciar-te-ei coisas grandes e ocultas, que não sabes.", ["Clama", "Cala", "Foge", "Corre", 2], ["grandes", "novas", "antigas", "simples", 3]],
  ["Ezequiel 36:26", "Dar-vos-ei coração novo e porei dentro de vós espírito novo; tirarei de vós o coração de pedra e vos darei coração de carne.", ["pedra", "ferro", "ouro", "barro", 2], ["novo", "velho", "forte", "grande", 2]],
  ["Amós 5:24", "Corra, porém, o juízo como as águas, e a justiça, como o ribeiro perene.", ["juízo", "fogo", "vento", "pão", 3], ["perene", "seco", "pequeno", "frio", 3]],
  ["Miqueias 6:8", "Ele te declarou, ó homem, o que é bom e que é o que o Senhor pede de ti: que pratiques a justiça, e ames a misericórdia, e andes humildemente com o teu Deus.", ["humildemente", "lentamente", "sozinho", "firmemente", 3], ["justiça", "riqueza", "vitória", "guerra", 3]],
  ["Zacarias 4:6", "Não por força nem por poder, mas pelo meu Espírito, diz o Senhor dos Exércitos.", ["Espírito", "nome", "povo", "braço", 2], ["força", "pressa", "ouro", "muros", 2]],
  ["Mateus 4:19", "Vinde após mim, e eu vos farei pescadores de homens.", ["homens", "peixes", "reis", "ovelhas", 1], ["pescadores", "pastores", "soldados", "mestres", 1]],
  ["Mateus 5:3", "Bem-aventurados os pobres de espírito, porque deles é o reino dos céus.", ["pobres", "fracos", "simples", "tristes", 2], ["reino", "templo", "caminho", "tesouro", 1]],
  ["Mateus 5:4", "Bem-aventurados os que choram, porque serão consolados.", ["choram", "riem", "correm", "dormem", 2], ["consolados", "esquecidos", "castigados", "ricos", 2]],
  ["Mateus 5:5", "Bem-aventurados os mansos, porque herdarão a terra.", ["mansos", "fortes", "ricos", "rápidos", 2], ["herdarão", "perderão", "venderão", "deixarão", 2]],
  ["Mateus 5:6", "Bem-aventurados os que têm fome e sede de justiça, porque serão fartos.", ["justiça", "poder", "ouro", "fama", 2], ["fartos", "tristes", "cansados", "esquecidos", 2]],
  ["Mateus 5:7", "Bem-aventurados os misericordiosos, porque alcançarão misericórdia.", ["misericordiosos", "orgulhosos", "ricos", "rápidos", 2], ["alcançarão", "perderão", "esconderão", "venderão", 3]],
  ["Mateus 5:8", "Bem-aventurados os limpos de coração, porque verão a Deus.", ["limpos", "ricos", "fortes", "sábios", 2], ["verão", "temerão", "esquecerão", "ouvirão", 2]],
  ["Mateus 5:9", "Bem-aventurados os pacificadores, porque serão chamados filhos de Deus.", ["pacificadores", "mansos", "puros", "humildes", 2], ["filhos", "servos", "amigos", "irmãos", 2]],
  ["Mateus 5:14", "Vós sois a luz do mundo; não se pode esconder uma cidade edificada sobre um monte.", ["luz", "voz", "paz", "força", 1], ["monte", "rio", "deserto", "vale", 2], ["esconder", "ver", "contar", "tocar", 2]],
  ["Mateus 6:9", "Pai nosso, que estás nos céus, santificado seja o teu nome;", ["céus", "montes", "campos", "mares", 1], ["santificado", "esquecido", "temido", "afastado", 2]],
  ["Mateus 6:11", "O pão nosso de cada dia dá-nos hoje;", ["pão", "vinho", "mel", "azeite", 1], ["hoje", "amanhã", "sempre", "ontem", 1]],
  ["Mateus 6:21", "Porque onde está o teu tesouro, aí estará também o teu coração.", ["tesouro", "lar", "trabalho", "amigo", 2], ["coração", "sono", "pé", "nome", 1]],
  ["Mateus 7:7", "Pedi, e dar-se-vos-á; buscai, e achareis; batei, e abrir-se-vos-á.", ["batei", "correi", "andai", "orai", 1], ["achareis", "perdereis", "vereis", "ouvireis", 2], ["Pedi", "Cantai", "Fugi", "Calai", 1]],
  ["Mateus 7:12", "Tudo quanto, pois, quereis que os homens vos façam, assim fazei-o vós também a eles; porque esta é a lei e os profetas.", ["façam", "digam", "deem", "paguem", 3], ["profetas", "reis", "juízes", "anjos", 2]],
  ["Mateus 9:37", "A seara, na verdade, é grande, mas poucos os ceifeiros.", ["seara", "casa", "rede", "tenda", 2], ["ceifeiros", "pastores", "soldados", "pescadores", 2]],
  ["Mateus 11:29", "Tomai sobre vós o meu jugo e aprendei de mim…", ["jugo", "manto", "cajado", "pão", 3], ["aprendei", "esquecei", "fugi", "cantai", 3]],
  ["Mateus 18:20", "Porque, onde estiverem dois ou três reunidos em meu nome, ali estou no meio deles.", ["nome", "templo", "altar", "caminho", 2], ["três", "cinco", "dez", "doze", 2]],
  ["Mateus 22:37", "Amarás o Senhor, teu Deus, de todo o teu coração, de toda a tua alma e de todo o teu entendimento.", ["entendimento", "poder", "tempo", "desejo", 2], ["alma", "casa", "voz", "força", 2]],
  ["Mateus 25:40", "Em verdade vos digo que sempre que o fizestes a um destes meus pequeninos irmãos, a mim o fizestes.", ["pequeninos", "poderosos", "ricos", "sábios", 3], ["fizestes", "negastes", "ouvistes", "vistes", 3]],
  ["Mateus 26:41", "Vigiai e orai, para que não entreis em tentação; o espírito, na verdade, está pronto, mas a carne é fraca.", ["Vigiai", "Dormi", "Corrai", "Calai", 2], ["fraca", "forte", "rica", "cansada", 2]],
  ["Mateus 28:19", "Ide, portanto, fazei discípulos de todas as nações, batizando-os em nome do Pai e do Filho e do Espírito Santo.", ["discípulos", "soldados", "mestres", "irmãos", 1], ["nações", "cidades", "casas", "ilhas", 1], ["batizando-os", "ensinando-os", "vestindo-os", "guardando-os", 2]],
  ["Marcos 1:15", "O tempo está cumprido, e o reino de Deus está próximo; arrependei-vos e crede no evangelho.", ["próximo", "distante", "escondido", "fechado", 2], ["arrependei-vos", "alegrai-vos", "levantai-vos", "calai-vos", 2]],
  ["Marcos 8:36", "Pois que aproveitará o homem se ganhar o mundo inteiro e perder a sua alma?", ["alma", "casa", "fama", "vida longa", 3], ["mundo", "reino", "ouro", "povo", 2]],
  ["Marcos 9:23", "Se podes! Tudo é possível ao que crê.", ["crê", "pede", "corre", "espera", 2], ["possível", "difícil", "demorado", "oculto", 2]],
  ["Marcos 16:15", "Ide por todo o mundo e pregai o evangelho a toda criatura.", ["mundo", "país", "povo", "deserto", 1], ["pregai", "escondei", "vendei", "guardai", 1], ["criatura", "cidade", "casa", "tribo", 2]],
  ["Lucas 1:37", "Porque para Deus nada é impossível.", ["impossível", "difícil", "demorado", "oculto", 1], ["nada", "tudo", "pouco", "muito", 1]],
  ["Lucas 6:36", "Sede misericordiosos, como também vosso Pai é misericordioso.", ["misericordiosos", "orgulhosos", "ricos", "rápidos", 2], ["Pai", "Rei", "Mestre", "Pastor", 2]],
  ["Lucas 19:10", "Porque o Filho do Homem veio buscar e salvar o perdido.", ["perdido", "fraco", "pobre", "doente", 2], ["buscar", "julgar", "ensinar", "vender", 2]],
  ["Lucas 24:6", "Não está aqui, mas ressuscitou.", ["ressuscitou", "dormiu", "partiu", "chorou", 1], ["aqui", "lá", "perto", "dentro", 1]],
  ["João 1:1", "No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.", ["Verbo", "Mestre", "Senhor", "Espírito", 2], ["princípio", "fim", "caminho", "deserto", 2]],
  ["João 1:14", "E o Verbo se fez carne e habitou entre nós, cheio de graça e de verdade.", ["carne", "luz", "pão", "homem", 2], ["graça", "ouro", "força", "glória", 2], ["habitou", "passou", "dormiu", "voltou", 2]],
  ["João 3:17", "Porquanto Deus enviou o seu Filho ao mundo, não para que condenasse o mundo, mas para que o mundo fosse salvo por ele.", ["salvo", "julgado", "curado", "ensinado", 3], ["condenasse", "abençoasse", "visitasse", "ensinasse", 3]],
  ["João 4:24", "Deus é espírito; e importa que os seus adoradores o adorem em espírito e em verdade.", ["espírito", "fogo", "luz", "rei", 2], ["adoradores", "servos", "filhos", "amigos", 3]],
  ["João 6:35", "Eu sou o pão da vida; o que vem a mim jamais terá fome; e o que crê em mim jamais terá sede.", ["pão", "vinho", "mel", "azeite", 1], ["fome", "medo", "pressa", "sono", 2], ["sede", "frio", "calor", "sono", 2]],
  ["João 8:12", "Eu sou a luz do mundo; quem me segue não andará em trevas, mas terá a luz da vida.", ["luz", "voz", "paz", "porta", 1], ["trevas", "medo", "tristeza", "dúvida", 2], ["segue", "teme", "ouve", "vê", 2]],
  ["João 8:32", "E conhecereis a verdade, e a verdade vos libertará.", ["verdade", "lei", "paz", "luz", 1], ["libertará", "ensinará", "guardará", "salvará", 2]],
  ["João 10:10", "O ladrão vem somente para roubar, matar e destruir; eu vim para que tenham vida e a tenham em abundância.", ["abundância", "segurança", "paz", "glória", 2], ["ladrão", "pastor", "rei", "mestre", 2], ["destruir", "ensinar", "visitar", "curar", 3]],
  ["João 10:11", "Eu sou o bom pastor; o bom pastor dá a vida pelas ovelhas.", ["ovelhas", "cabras", "portas", "pastagens", 1], ["pastor", "rei", "mestre", "juiz", 1]],
  ["João 11:25", "Eu sou a ressurreição e a vida; quem crê em mim, ainda que morra, viverá.", ["ressurreição", "verdade", "porta", "luz", 2], ["viverá", "dormirá", "esperará", "voltará", 2]],
  ["João 13:34", "Um novo mandamento vos dou: que vos ameis uns aos outros…", ["novo", "antigo", "grande", "primeiro", 2], ["ameis", "ouçais", "sigais", "ajudeis", 2]],
  ["João 14:6", "Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai senão por mim.", ["caminho", "pastor", "pão", "mestre", 1], ["Pai", "céu", "templo", "reino", 2]],
  ["João 14:27", "Deixo-vos a paz, a minha paz vos dou;", ["paz", "lei", "força", "glória", 1], ["Deixo-vos", "Roubo-vos", "Escondo-vos", "Cobro-vos", 2]],
  ["João 15:5", "Eu sou a videira, vós, os ramos.", ["videira", "figueira", "oliveira", "palmeira", 1], ["ramos", "frutos", "raízes", "folhas", 1]],
  ["João 16:33", "No mundo, passais por aflições; mas tende bom ânimo, eu venci o mundo.", ["venci", "criei", "guardo", "amo", 2], ["aflições", "festas", "viagens", "colheitas", 2]],
  ["João 20:29", "Porque me viste, creste; bem-aventurados os que não viram e creram.", ["creram", "fugiram", "dormiram", "cantaram", 2], ["viste", "chamaste", "ouviste", "seguiste", 2]],
  ["Atos 1:8", "Mas recebereis poder, ao descer sobre vós o Espírito Santo, e sereis minhas testemunhas…", ["testemunhas", "discípulos", "servos", "mensageiros", 2], ["poder", "ouro", "pão", "descanso", 2]],
  ["Atos 2:38", "Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para remissão dos vossos pecados, e recebereis o dom do Espírito Santo.", ["Arrependei-vos", "Esperai", "Escutai", "Vigiai", 2], ["remissão", "lembrança", "festa", "viagem", 3]],
  ["Atos 4:12", "E em nenhum outro há salvação, porque abaixo do céu não existe nenhum outro nome, dado entre os homens, pelo qual importa que sejamos salvos.", ["salvação", "riqueza", "descanso", "vitória", 2], ["nome", "templo", "caminho", "rei", 2]],
  ["Atos 16:31", "Crê no Senhor Jesus e serás salvo, tu e a tua casa.", ["salvo", "livre", "curado", "abençoado", 1], ["casa", "terra", "tribo", "cidade", 1]],
  ["Romanos 1:16", "Pois não me envergonho do evangelho, porque é o poder de Deus…", ["envergonho", "orgulho", "esqueço", "cansei", 3], ["poder", "nome", "caminho", "livro", 2]],
  ["Romanos 3:23", "Pois todos pecaram e carecem da glória de Deus.", ["pecaram", "choraram", "oraram", "esperaram", 1], ["glória", "casa", "mão", "terra", 1]],
  ["Romanos 5:1", "Justificados, pois, mediante a fé, temos paz com Deus por meio de nosso Senhor Jesus Cristo;", ["Justificados", "Cansados", "Assustados", "Esquecidos", 3], ["paz", "medo", "pressa", "dúvida", 1]],
  ["Romanos 5:8", "Mas Deus prova o seu próprio amor para conosco pelo fato de ter Cristo morrido por nós, sendo nós ainda pecadores.", ["amor", "poder", "juízo", "nome", 2], ["pecadores", "justos", "fiéis", "sábios", 2]],
  ["Romanos 6:23", "Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor.", ["morte", "dor", "prisão", "fome", 2], ["salário", "prêmio", "caminho", "fruto", 2], ["gratuito", "caro", "oculto", "difícil", 3]],
  ["Romanos 8:1", "Portanto, agora, nenhuma condenação há para os que estão em Cristo Jesus.", ["condenação", "tristeza", "dívida", "separação", 3], ["nenhuma", "muita", "alguma", "toda", 2]],
  ["Romanos 10:9", "Se, com a tua boca, confessares Jesus como Senhor e, em teu coração, creres que Deus o ressuscitou dentre os mortos, serás salvo.", ["ressuscitou", "enviou", "ungiu", "glorificou", 3], ["confessares", "negares", "esconderes", "ouvires", 3]],
  ["Romanos 12:2", "E não vos conformeis com este século, mas transformai-vos pela renovação da vossa mente, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus.", ["mente", "vida", "casa", "voz", 2], ["conformeis", "alegreis", "apresseis", "cansais", 3]],
  ["Romanos 12:12", "Regozijai-vos na esperança, sede pacientes na tribulação, perseverai na oração.", ["oração", "fé", "obra", "jornada", 2], ["tribulação", "festa", "viagem", "colheita", 2]],
  ["Romanos 12:21", "Não te deixes vencer do mal, mas vence o mal com o bem.", ["bem", "fogo", "ouro", "medo", 1], ["vencer", "ensinar", "levar", "guardar", 2]],
  ["Romanos 13:10", "O amor não faz mal ao próximo; de sorte que o cumprimento da lei é o amor.", ["próximo", "inimigo", "pobre", "estrangeiro", 2], ["cumprimento", "esquecimento", "começo", "fim", 3]],
  ["1 Coríntios 10:31", "Portanto, quer comais, quer bebais ou façais outra coisa qualquer, fazei tudo para a glória de Deus.", ["glória", "fama", "paz", "força", 2], ["comais", "durmais", "cantais", "corrais", 2]],
  ["1 Coríntios 13:4", "O amor é paciente, é benigno…", ["paciente", "rápido", "forte", "sábio", 1], ["benigno", "orgulhoso", "ciumento", "duro", 3]],
  ["1 Coríntios 15:58", "Portanto, meus amados irmãos, sede firmes, inabaláveis e sempre abundantes na obra do Senhor, sabendo que, no Senhor, o vosso trabalho não é vão.", ["vão", "curto", "fácil", "pequeno", 3], ["inabaláveis", "cansados", "apressados", "calados", 3]],
  ["1 Coríntios 16:14", "Todos os vossos atos sejam feitos com amor.", ["amor", "pressa", "calma", "cuidado", 1], ["atos", "sonhos", "dias", "bens", 2]],
  ["2 Coríntios 5:7", "Visto que andamos por fé e não pelo que vemos.", ["fé", "medo", "pressa", "sorte", 1], ["vemos", "temos", "pedimos", "ouvimos", 2]],
  ["2 Coríntios 5:17", "E, assim, se alguém está em Cristo, é nova criatura; as coisas antigas já passaram; eis que se fizeram novas.", ["criatura", "pessoa", "casa", "terra", 2], ["antigas", "belas", "pequenas", "tristes", 2]],
  ["2 Coríntios 9:7", "Porque Deus ama a quem dá com alegria.", ["alegria", "tristeza", "pressa", "medo", 1], ["ama", "teme", "ouve", "guarda", 1]],
  ["2 Coríntios 12:9", "Então, ele me disse: A minha graça te basta, porque o poder se aperfeiçoa na fraqueza.", ["fraqueza", "riqueza", "pressa", "fartura", 2], ["basta", "falta", "cansa", "pesa", 2], ["aperfeiçoa", "esconde", "cansa", "acaba", 3]],
  ["Gálatas 5:1", "Para a liberdade foi que Cristo nos libertou; permanecei, pois, firmes e não vos submetais, de novo, a jugo de escravidão.", ["liberdade", "riqueza", "festa", "paz", 2], ["escravidão", "alegria", "viagem", "pobreza", 2]],
  ["Gálatas 5:22", "Mas o fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade, mansidão, domínio próprio.", ["fidelidade", "orgulho", "ciúme", "ira", 2], ["alegria", "tristeza", "pressa", "dúvida", 1]],
  ["Gálatas 6:9", "E não nos cansemos de fazer o bem, porque, a seu tempo, ceifaremos, se não desfalecermos.", ["ceifaremos", "dormiremos", "partiremos", "venderemos", 3], ["cansemos", "alegremos", "apressemos", "calemos", 2]],
  ["Efésios 2:8", "Porque pela graça sois salvos, mediante a fé; e isto não vem de vós; é dom de Deus.", ["graça", "lei", "obra", "força", 2], ["fé", "pressa", "sorte", "fama", 2], ["dom", "preço", "castigo", "sonho", 2]],
  ["Efésios 4:32", "Pelo contrário, sede bondosos e compassivos uns para com os outros, perdoando-vos mutuamente, como também Deus, em Cristo, vos perdoou.", ["perdoou", "chamou", "ensinou", "guardou", 3], ["compassivos", "orgulhosos", "apressados", "calados", 3]],
  ["Efésios 6:1", "Filhos, obedecei a vossos pais no Senhor, pois isto é justo.", ["pais", "mestres", "irmãos", "amigos", 1], ["obedecei", "esquecei", "fugi", "corrigi", 1]],
  ["Efésios 6:11", "Revesti-vos de toda a armadura de Deus, para poderdes ficar firmes contra as ciladas do diabo.", ["armadura", "força", "sabedoria", "paz", 2], ["ciladas", "festas", "estradas", "ofertas", 3]],
  ["Filipenses 1:6", "Estou plenamente certo de que aquele que começou boa obra em vós há de completá-la até ao Dia de Cristo Jesus.", ["completá-la", "esquecê-la", "vendê-la", "guardá-la", 3], ["começou", "terminou", "esqueceu", "escondeu", 2]],
  ["Filipenses 4:4", "Alegrai-vos sempre no Senhor; outra vez digo: alegrai-vos.", ["Alegrai-vos", "Orai", "Louvai", "Cantai", 1], ["sempre", "pouco", "às vezes", "nunca", 1]],
  ["Filipenses 4:6", "Em tudo, porém, sejam conhecidas, diante de Deus, as vossas petições, pela oração e pela súplica, com ações de graças.", ["oração", "pressa", "fama", "riqueza", 2], ["petições", "riquezas", "tarefas", "festas", 3]],
  ["Filipenses 4:19", "O meu Deus, segundo a sua riqueza em glória, há de suprir, em Cristo Jesus, cada uma de vossas necessidades.", ["suprir", "esquecer", "contar", "vender", 3], ["riqueza", "pobreza", "pressa", "fama", 2]],
  ["Colossenses 3:23", "E tudo o que fizerdes, fazei-o de todo o coração, como para o Senhor e não para os homens.", ["coração", "tempo", "modo", "povo", 2], ["homens", "reis", "anjos", "filhos", 2]],
  ["1 Tessalonicenses 5:16", "Alegrai-vos sempre. Orai sem cessar. Em tudo, dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.", ["cessar", "pressa", "dúvida", "temor", 1], ["graças", "ofertas", "ordens", "gritos", 2], ["vontade", "ordem", "pressa", "festa", 2]],
  ["1 Timóteo 6:10", "Porque o amor ao dinheiro é raiz de todos os males; e alguns, nessa cobiça, se desviaram da fé e a si mesmos se atormentaram com muitas dores.", ["raiz", "fruto", "folha", "ramo", 3], ["dinheiro", "poder", "estudo", "trabalho", 2]],
  ["2 Timóteo 1:7", "Porque Deus não nos tem dado espírito de covardia, mas de poder, de amor e de moderação.", ["covardia", "pobreza", "tristeza", "dúvida", 2], ["moderação", "pressa", "riqueza", "vingança", 3]],
  ["2 Timóteo 3:16", "Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a educação na justiça.", ["inspirada", "escrita", "guardada", "ouvida", 2], ["repreensão", "fama", "viagem", "festa", 3]],
  ["Hebreus 4:16", "Acheguemo-nos, portanto, confiadamente, junto ao trono da graça, a fim de recebermos misericórdia e alcançarmos graça para socorro em ocasião oportuna.", ["trono", "muro", "templo", "altar", 2], ["Acheguemo-nos", "Afastemo-nos", "Escondamo-nos", "Calemo-nos", 3]],
  ["Hebreus 11:6", "Ora, sem fé é impossível agradar a Deus, porquanto é necessário que aquele que se aproxima de Deus creia que ele existe e que se torna galardoador dos que o buscam.", ["fé", "amor", "paz", "dinheiro", 2], ["agradar", "enganar", "ensinar", "vencer", 3], ["galardoador", "juiz", "mestre", "pastor", 3]],
  ["Hebreus 13:8", "Jesus Cristo é o mesmo, ontem, e hoje, e eternamente.", ["mesmo", "maior", "único", "primeiro", 2], ["eternamente", "raramente", "somente", "novamente", 2]],
  ["Tiago 1:5", "Se, porém, algum de vós necessita de sabedoria, peça-a a Deus, que a todos dá liberalmente, e nada lhes impropera; e ser-lhe-á concedida.", ["sabedoria", "coragem", "paz", "força", 2], ["liberalmente", "raramente", "tristemente", "lentamente", 3]],
  ["Tiago 1:22", "Tornai-vos, pois, praticantes da palavra e não somente ouvintes, enganando-vos a vós mesmos.", ["praticantes", "ouvintes", "cantores", "mestres", 2], ["ouvintes", "pregadores", "escritores", "lutadores", 2]],
  ["Tiago 4:8", "Chegai-vos a Deus, e ele se chegará a vós outros.", ["chegará", "afastará", "calará", "levantará", 2], ["Chegai-vos", "Afastai-vos", "Escondei-vos", "Calai-vos", 2]],
  ["1 Pedro 4:8", "Acima de tudo, porém, tende amor intenso uns para com os outros, porque o amor cobre multidão de pecados.", ["intenso", "pequeno", "raro", "frio", 3], ["multidão", "pouca", "nenhuma", "metade", 3]],
  ["1 Pedro 5:7", "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.", ["ansiedade", "riqueza", "alegria", "história", 2], ["cuidado", "pressa", "medo", "sono", 2]],
  ["1 João 1:9", "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça.", ["pecados", "sonhos", "medos", "planos", 2], ["fiel", "rápido", "forte", "cansado", 2], ["purificar", "castigar", "esquecer", "cobrar", 3]],
  ["1 João 4:8", "Aquele que não ama não conhece a Deus, pois Deus é amor.", ["amor", "luz", "vida", "paz", 1], ["conhece", "teme", "vê", "ouve", 2]],
  ["1 João 4:19", "Nós amamos porque ele nos amou primeiro.", ["primeiro", "muito", "assim", "também", 2], ["amamos", "tememos", "seguimos", "ouvimos", 1]],
  ["Apocalipse 3:20", "Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa e com ele cearei, e ele, comigo.", ["porta", "janela", "torre", "muralha", 1], ["cearei", "dormirei", "cantarei", "partirei", 2], ["bato", "durmo", "espero", "grito", 3]],
  ["Apocalipse 21:4", "E lhes enxugará dos olhos toda lágrima, e a morte já não existirá, já não haverá luto, nem pranto, nem dor, porque as primeiras coisas passaram.", ["lágrima", "poeira", "ferida", "mágoa", 2], ["pranto", "riso", "festa", "canto", 3], ["morte", "noite", "fome", "guerra", 2]],
];

function build(): VerseItem[] {
  const out: VerseItem[] = [];
  for (const [ref, text, ...blanks] of VERSES_DATA) {
    for (const [spec, w1, w2, w3, d] of blanks) {
      const [word, nth] = spec.split("#");
      let idx = -1;
      for (let n = Number(nth ?? 1); n > 0; n--) idx = text.indexOf(word, idx + 1);
      if (idx < 0) continue; // proteção: lacuna que não está no texto é ignorada
      // ajusta o nível pelo tamanho da palavra: curta e comum = fácil; longa = difícil
      const level: Level = d === 2 && word.length <= 4 ? 1 : d === 2 && word.length >= 11 ? 3 : d;
      out.push({
        ref,
        before: text.slice(0, idx).trim(),
        after: text.slice(idx + word.length).trim(),
        a: word,
        w: [w1, w2, w3],
        d: level,
      });
    }
  }
  return out;
}

export const VERSES_EXTRA: VerseItem[] = build();
