// Personagens extras do "Quem Sou Eu?" (Bíblia protestante). As dicas vão da mais vaga para a mais clara.
// Entram no FIM da lista (content.ts) para não mudar as partidas antigas.
import type { Level, WhoItem } from "./content";

type Row = [key: string, name: string, ref: string, h1: string, h2: string, h3: string, h4: string, d: Level];

const ROWS: Row[] = [
  // ------------------------------------------------------------------ fácil
  ["adao", "Adão", "Gênesis 1–3", "Fui o primeiro de todos e não tive pai nem mãe.", "Deus me formou do pó da terra.", "Dei nome a todos os animais.", "Vivi no Éden com minha esposa, Eva, até comermos do fruto proibido.", 1],
  ["eva", "Eva", "Gênesis 2–3", "Fui criada de uma costela.", "Fui a primeira mulher do mundo.", "Uma serpente me enganou.", "Comi do fruto proibido e dei também ao meu marido, Adão.", 1],
  ["caim", "Caim", "Gênesis 4", "Fui o primeiro filho de Adão e Eva.", "Eu era lavrador, e meu irmão cuidava de ovelhas.", "Deus aceitou a oferta do meu irmão e não a minha.", "Por inveja, fui o primeiro a tirar a vida de alguém: meu irmão Abel.", 1],
  ["abel", "Abel", "Gênesis 4", "Fui o segundo filho de Adão e Eva.", "Eu cuidava de ovelhas.", "Ofereci a Deus o melhor do meu rebanho.", "Meu irmão Caim me tirou a vida por inveja.", 1],
  ["sara", "Sara", "Gênesis 17–21", "Fui casada com um homem que Deus chamou para sair da sua terra.", "Ri quando ouvi que teria um filho na velhice.", "Meu filho se chamou Isaque.", "Meu marido foi Abraão.", 1],
  ["isaque", "Isaque", "Gênesis 21–27", "Nasci quando meus pais já eram muito velhos.", "Quase fui oferecido num altar, mas Deus providenciou um carneiro.", "Casei com Rebeca.", "Fui pai de Esaú e Jacó.", 1],
  ["jaco", "Jacó", "Gênesis 25–50", "Nasci segurando o calcanhar do meu irmão gêmeo.", "Tive um sonho com uma escada que chegava ao céu.", "Lutei com um anjo e ganhei outro nome.", "Meu novo nome foi Israel, e tive doze filhos.", 1],
  ["esau", "Esaú", "Gênesis 25–27", "Eu era peludo e gostava de caçar.", "Vendi um direito importante por um prato de comida.", "Meu irmão gêmeo me enganou para receber a bênção.", "Meu irmão se chamava Jacó.", 1],
  ["aarao", "Arão", "Êxodo 4–7", "Eu era bom de falar.", "Meu irmão tinha medo de falar diante do faraó.", "Fui o primeiro sumo sacerdote de Israel.", "Meu irmão foi Moisés.", 1],
  ["josue", "Josué", "Josué 1–6", "Fui o ajudante de um grande líder.", "Fui um dos espias que confiaram em Deus.", "Atravessei o rio Jordão a pé enxuto com o povo.", "Marchei em volta de Jericó até os muros caírem.", 1],
  ["golias", "Golias", "1 Samuel 17", "Eu era um guerreiro enorme.", "Vinha do povo filisteu.", "Durante quarenta dias desafiei o exército de Israel.", "Um jovem pastor me derrubou com uma pedra.", 1],
  ["saul", "Saul", "1 Samuel 9–31", "Eu era mais alto que todos do meu povo.", "Procurava jumentas perdidas quando fui chamado.", "Samuel me ungiu.", "Fui o primeiro rei de Israel.", 1],
  ["maria", "Maria", "Lucas 1–2", "Eu era uma jovem de Nazaré.", "Um anjo me visitou com uma notícia.", "Disse: Eis aqui a serva do Senhor.", "Fui a mãe de Jesus.", 1],
  ["jose-nt", "José, pai de Jesus", "Mateus 1–2", "Eu era carpinteiro.", "Um anjo falou comigo em sonho.", "Levei minha família para o Egito para fugir de Herodes.", "Cuidei de Jesus como pai e fui casado com Maria.", 1],
  ["joao-batista", "João Batista", "Mateus 3", "Vivi no deserto.", "Usava roupa de pelos de camelo.", "Comia gafanhotos e mel silvestre.", "Batizei Jesus no rio Jordão.", 1],
  ["andre", "André", "João 1:40-42", "Fui discípulo de João Batista antes de seguir Jesus.", "Eu era pescador na Galileia.", "Levei meu irmão até Jesus.", "Meu irmão era Simão Pedro.", 1],
  ["joao", "João, o apóstolo", "João 13; Apocalipse 1", "Eu era pescador e filho de Zebedeu.", "Fui chamado de o discípulo amado.", "Estava ao pé da cruz com a mãe de Jesus.", "Escrevi um Evangelho e o Apocalipse.", 1],
  ["mateus", "Mateus", "Mateus 9:9", "Eu era mal visto pelo meu trabalho.", "Estava sentado na coletoria quando Jesus me chamou.", "Deixei tudo para seguir Jesus.", "Fui cobrador de impostos e escrevi o primeiro Evangelho.", 1],
  ["tome", "Tomé", "João 20:24-29", "Eu era um dos doze discípulos.", "Não estava com os outros quando Jesus apareceu.", "Disse que só acreditaria se visse as marcas nas mãos de Jesus.", "Fiquei conhecido como o discípulo que duvidou.", 1],
  ["judas", "Judas Iscariotes", "Mateus 26:14-16", "Eu era um dos doze e cuidava da bolsa de dinheiro.", "Combinei um preço com os chefes dos sacerdotes.", "Recebi trinta moedas de prata.", "Entreguei Jesus com um beijo.", 1],
  ["maria-madalena", "Maria Madalena", "João 20:1-18", "Jesus me libertou de sete demônios.", "Eu o seguia e o servia.", "Estive junto à cruz.", "Fui a primeira a ver Jesus ressuscitado.", 1],
  ["marta", "Marta", "Lucas 10:38-42", "Recebi Jesus na minha casa em Betânia.", "Eu ficava ocupada com muito serviço.", "Minha irmã Maria preferiu ficar ouvindo Jesus.", "Meu irmão era Lázaro.", 1],
  ["lazaro", "Lázaro", "João 11", "Moro em Betânia e sou amigo de Jesus.", "Tenho duas irmãs: Marta e Maria.", "Fiquei doente e morri.", "Jesus me chamou e saí do túmulo depois de quatro dias.", 1],
  ["estevao", "Estêvão", "Atos 6–7", "Fui escolhido para servir às mesas da igreja.", "Eu era cheio de fé e do Espírito Santo.", "Falei corajosamente diante do concílio.", "Fui o primeiro mártir cristão, apedrejado.", 1],
  ["timoteo", "Timóteo", "1 e 2 Timóteo", "Minha mãe se chamava Êunice e minha avó, Loide.", "Conheci as Escrituras desde criança.", "Fui discípulo e companheiro de viagem de Paulo.", "Paulo me escreveu duas cartas e disse: ninguém despreze a tua mocidade.", 1],
  ["gabriel", "Gabriel", "Lucas 1", "Não sou humano.", "Sou mensageiro de Deus.", "Visitei o profeta Daniel e, depois, o sacerdote Zacarias.", "Anunciei a Maria que ela seria mãe de Jesus.", 1],
  ["farao", "Faraó do Egito", "Êxodo 5–14", "Eu era o rei de uma grande nação.", "Escravizei o povo de Deus.", "Meu coração se endureceu várias vezes.", "Deixei o povo sair depois das dez pragas, mas depois os persegui até o Mar Vermelho.", 1],
  ["nabucodonosor", "Nabucodonosor", "Daniel 2–4", "Eu era rei da Babilônia.", "Tive um sonho com uma grande estátua.", "Mandei jogar três jovens numa fornalha de fogo.", "Fiquei por um tempo vivendo como um animal até reconhecer o Deus de Daniel.", 1],
  ["herodes", "Herodes, o Grande", "Mateus 2", "Eu era rei da Judeia.", "Fiquei perturbado quando os magos perguntaram pelo rei dos judeus.", "Tinha medo de perder o trono.", "Mandei matar os meninos de Belém.", 1],
  ["pilatos", "Pôncio Pilatos", "Mateus 27", "Eu era governador romano da Judeia.", "Não achei culpa em Jesus.", "Perguntei: Que é a verdade?", "Lavei as mãos e entreguei Jesus para ser crucificado.", 1],
  ["barrabas", "Barrabás", "Mateus 27:15-26", "Eu estava preso.", "Era conhecido como bandido e rebelde.", "A multidão pôde escolher alguém para ser solto.", "Fui solto no lugar de Jesus.", 1],
  ["nicodemos", "Nicodemos", "João 3; 19", "Era fariseu e membro do conselho dos judeus.", "Fui falar com Jesus à noite.", "Ouvi sobre nascer de novo.", "Mais tarde ajudei a sepultar Jesus.", 1],
  ["jose-arimateia", "José de Arimateia", "Mateus 27:57-60", "Eu era rico e discípulo de Jesus em segredo.", "Era membro do conselho, mas não concordei com a condenação.", "Procurei Pilatos depois da morte de Jesus.", "Pedi o corpo de Jesus e o coloquei no meu túmulo novo.", 1],
  ["bartimeu", "Bartimeu", "Marcos 10:46-52", "Eu ficava à beira do caminho em Jericó.", "Eu era mendigo e cego.", "Gritei mais alto quando mandaram eu me calar.", "Jesus me curou, e passei a seguí-lo.", 1],
  ["jairo", "Jairo", "Marcos 5:21-43", "Eu era chefe de uma sinagoga.", "Pedi a Jesus por alguém da minha casa.", "Minha filha de doze anos estava morrendo.", "Jesus a levantou e disse: Menina, levanta-te.", 1],
  ["miria", "Miriã", "Êxodo 2; 15", "Eu era irmã mais velha de dois grandes homens.", "Fiquei vigiando um cesto no rio.", "Falei com a filha do faraó.", "Depois da travessia do Mar Vermelho, toquei pandeiro e cantei.", 1],
  ["raquel", "Raquel", "Gênesis 29–35", "Cuidava das ovelhas do meu pai.", "Jacó se apaixonou por mim e trabalhou sete anos para me ter.", "Minha irmã mais velha se chamava Lia.", "Fui mãe de José e Benjamim.", 1],
  ["rebeca", "Rebeca", "Gênesis 24", "Dei de beber a um servo e aos seus camelos.", "Aceitei partir para uma terra distante.", "Casei com um homem chamado Isaque.", "Fui mãe de Esaú e Jacó.", 1],
  ["potifar", "Potifar", "Gênesis 39", "Eu era oficial do faraó.", "Comprei um jovem hebreu como servo.", "Confiei tudo da minha casa a ele.", "A minha esposa o acusou falsamente.", 2],
  ["noemi", "Noemi", "Rute 1", "Saí de Belém por causa de uma fome.", "Perdi meu marido e meus dois filhos em Moabe.", "Pedi que me chamassem de Mara, que significa amarga.", "Voltei com minha nora Rute.", 1],
  ["boaz", "Boaz", "Rute 2–4", "Eu era um homem rico de Belém.", "Deixei que uma jovem estrangeira colhesse espigas no meu campo.", "Fui parente próximo de Noemi.", "Casei com Rute.", 1],
  ["ana-samuel", "Ana, mãe de Samuel", "1 Samuel 1", "Eu não tinha filhos e sofria por isso.", "Orei no templo com tanta intensidade que o sacerdote achou que eu estava embriagada.", "Prometi dedicar meu filho ao Senhor.", "Meu filho foi o profeta Samuel.", 1],
  ["samuel", "Samuel", "1 Samuel 3; 16", "Minha mãe me entregou ao templo ainda criança.", "Ouvi uma voz me chamar à noite e achei que era o sacerdote Eli.", "Fui profeta e juiz de Israel.", "Ungi Saul e depois Davi como reis.", 1],
  ["jonatas", "Jônatas", "1 Samuel 18–20", "Meu pai era rei.", "Eu era um guerreiro corajoso.", "Fiz aliança de amizade com um jovem pastor.", "Fui o grande amigo de Davi.", 1],
  ["bate-seba", "Bate-Seba", "2 Samuel 11–12", "Meu marido era soldado do rei.", "Um rei me viu ao longe, tomando banho.", "Meu marido morreu na guerra por ordem do rei.", "Fui esposa de Davi e mãe de Salomão.", 1],
  ["absalao", "Absalão", "2 Samuel 15–18", "Eu era um príncipe muito bonito, de cabelos longos.", "Meu pai era um rei famoso.", "Conspirei para tomar o trono dele.", "Meu cabelo ficou preso nos galhos de um carvalho durante a fuga.", 1],
  ["jezabel", "Jezabel", "1 Reis 16–21", "Eu era rainha e adorava Baal.", "Mandei matar profetas do Senhor.", "Usei o nome do rei para tomar a vinha de Nabote.", "Jurei perseguir o profeta Elias.", 1],
  ["acabe", "Acabe", "1 Reis 16–22", "Fui rei de Israel.", "Minha esposa era Jezabel.", "Cobicei a vinha de Nabote.", "Fui o rei do tempo de Elias.", 1],
  ["eliseu", "Eliseu", "2 Reis 2–6", "Eu estava arando com doze juntas de bois quando fui chamado.", "Recebi a capa de um grande profeta.", "Pedi porção dobrada do espírito dele.", "Fui o sucessor de Elias.", 1],
  ["naama", "Naamã", "2 Reis 5", "Eu era general de um exército estrangeiro.", "Tinha lepra.", "Uma menina israelita serva da minha esposa me falou do profeta.", "Fui curado ao me lavar sete vezes no rio Jordão.", 1],
  ["jeremias", "Jeremias", "Jeremias 1", "Deus me chamou quando eu ainda era muito jovem.", "Disse que não sabia falar, pois era apenas um menino.", "Chorei pelo meu povo.", "Sou chamado de o profeta chorão.", 1],
  ["isaias", "Isaías", "Isaías 6", "Vi o Senhor sentado num trono alto.", "Serafins clamavam: Santo, Santo, Santo.", "Respondi: Eis-me aqui, envia-me a mim.", "Fui profeta e falei do Servo que seria traspassado.", 1],
  ["ezequiel", "Ezequiel", "Ezequiel 37", "Fui profeta no exílio da Babilônia.", "Tive visões de rodas e de seres vivos.", "Deus me levou a um vale cheio de ossos.", "Os ossos secos voltaram à vida.", 1],
  ["sadraque", "Sadraque", "Daniel 3", "Fui levado para a Babilônia.", "Tinha dois amigos e um deles se chamava Daniel.", "Recusei adorar uma estátua de ouro.", "Fui jogado na fornalha com Mesaque e Abede-Nego e não me queimei.", 1],
  ["mardoqueu", "Mardoqueu", "Ester 2–8", "Eu era judeu na Pérsia.", "Criei uma jovem órfã como filha.", "Não me ajoelhei diante de Hamã.", "Pedi à rainha Ester que falasse com o rei para salvar o nosso povo.", 1],
  ["jo", "Jó", "Jó 1–42", "Eu era muito rico e temente a Deus.", "Perdi meus filhos, meus bens e minha saúde.", "Três amigos vieram me consolar, mas acabaram me criticando.", "Mesmo sofrendo, disse: O Senhor o deu, o Senhor o tomou.", 1],
  ["dalila", "Dalila", "Juízes 16", "Eu vivia no vale de Soreque.", "Os príncipes dos filisteus me ofereceram muito dinheiro.", "Fiquei insistindo para descobrir um segredo.", "Fui quem descobriu que a força de Sansão estava no cabelo.", 1],
  ["gideao", "Gideão", "Juízes 6–7", "Eu estava debulhando trigo escondido quando um anjo me chamou.", "Pedi sinais com um velo de lã.", "Meu exército foi reduzido a trezentos homens.", "Venci os midianitas com trombetas, jarros e tochas.", 1],
  ["lo", "Ló", "Gênesis 19", "Eu era sobrinho de Abraão.", "Fui morar numa cidade da planície.", "Anjos me tiraram de lá antes da destruição.", "Minha esposa olhou para trás e virou estátua de sal.", 1],
  ["benjamim", "Benjamim", "Gênesis 42–45", "Eu era o filho mais novo de Jacó.", "Minha mãe morreu quando nasci.", "Meu irmão José mandou esconder um copo de prata no meu saco.", "Fui o último dos doze filhos de Jacó.", 1],

  // ------------------------------------------------------------------ médio
  ["enoque", "Enoque", "Gênesis 5:21-24", "Vivi antes do dilúvio.", "Andei com Deus.", "Meu filho Matusalém foi o homem que mais viveu.", "Deus me levou, e não vi a morte.", 2],
  ["matusalem", "Matusalém", "Gênesis 5:27", "Meu pai foi um homem que andou com Deus.", "Meu neto construiu uma grande embarcação.", "Meu nome virou sinônimo de idade muito avançada.", "Vivi 969 anos.", 2],
  ["ninrode", "Ninrode", "Gênesis 10:8-12", "Eu era neto de um filho de Noé.", "Fui um poderoso caçador diante do Senhor.", "Meu reino começou em Babel.", "Fui um dos primeiros grandes reis depois do dilúvio.", 2],
  ["hagar", "Hagar", "Gênesis 16; 21", "Eu era egípcia e servia numa casa.", "Fui dada ao dono da casa para ter um filho.", "Fugi para o deserto e um anjo me encontrou junto a uma fonte.", "Meu filho se chamou Ismael.", 1],
  ["ismael", "Ismael", "Gênesis 16; 21", "Minha mãe era egípcia.", "Fui o primeiro filho do meu pai.", "Fui mandado embora com minha mãe para o deserto.", "Meu pai foi Abraão e meu meio-irmão, Isaque.", 1],
  ["labao", "Labão", "Gênesis 29–31", "Eu era tio e depois sogro de um homem de quem me aproveitei.", "Enganei-o no casamento, trocando a noiva.", "Tinha duas filhas.", "Meu sobrinho Jacó trabalhou para mim por muitos anos.", 1],
  ["lia", "Lia", "Gênesis 29–30", "Eu tinha olhos fracos, e minha irmã era mais bonita.", "Meu pai me deu em casamento antes da minha irmã.", "Tive muitos filhos, entre eles Judá e Levi.", "Fui a primeira esposa de Jacó.", 1],
  ["juda", "Judá", "Gênesis 37; 44", "Sou um dos doze filhos de Jacó.", "Sugeri vender meu irmão em vez de deixá-lo na cova.", "Mais tarde me ofereci como escravo no lugar de Benjamim.", "Da minha tribo viria o rei Davi.", 1],
  ["ruben", "Rúben", "Gênesis 37:21-22", "Sou o primogênito de Jacó.", "Não quis que meu irmão fosse morto.", "Planejei tirá-lo da cova depois.", "Voltei e não o encontrei: meu irmão José tinha sido vendido.", 1],
  ["tamar", "Tamar", "Gênesis 38", "Fui nora de Judá.", "Fiquei viúva.", "Cobri o rosto com véu para ser reconhecida.", "Tive gêmeos e entrei na linhagem de Davi.", 2],
  ["jetro", "Jetro", "Êxodo 2–3; 18", "Eu era sacerdote em Midiã.", "Tive sete filhas.", "Acolhi um fugitivo do Egito.", "Fui sogro de Moisés e o aconselhei a escolher ajudantes.", 1],
  ["zipora", "Zípora", "Êxodo 2:21; 4:25", "Eu cuidava das ovelhas do meu pai em Midiã.", "Casei com um hebreu criado no Egito.", "Tive um filho chamado Gérson.", "Meu marido foi Moisés.", 2],
  ["calebe", "Calebe", "Números 13–14", "Fui espiar uma terra com onze companheiros.", "Dez deles tiveram medo; eu e Josué não.", "Disse: Subamos e tomemos a terra.", "Aos 85 anos, pedi o monte de Hebrom.", 1],
  ["balaao", "Balaão", "Números 22–24", "Eu era um adivinho.", "O rei de Moabe me ofereceu pagamento para amaldiçoar Israel.", "Ao invés de maldição, só consegui abençoar.", "Minha jumenta falou comigo.", 1],
  ["raabe", "Raabe", "Josué 2; 6", "Eu morava numa casa sobre o muro da cidade.", "Escondi dois espias debaixo de talos de linho.", "Pedi que poupassem minha família.", "Pendurei um cordão vermelho na janela quando Jericó foi tomada.", 1],
  ["baraque", "Baraque", "Juízes 4–5", "Fui um general de Israel.", "Só fui à batalha se uma profetisa fosse comigo.", "Dez mil homens me seguiram até o monte Tabor.", "Derrotei Sísera com a ajuda de Débora.", 2],
  ["jael", "Jael", "Juízes 4:17-22", "Eu morava numa tenda.", "Convidei um general cansado para entrar.", "Dei leite a ele e o cobri com um manto.", "Matei Sísera com uma estaca de tenda.", 2],
  ["jefte", "Jefté", "Juízes 11", "Meus irmãos me expulsaram por ser filho de outra mulher.", "Virei chefe de um bando e depois fui chamado para liderar.", "Fiz um voto precipitado.", "Fui um dos juízes de Israel.", 1],
  ["eli", "Eli", "1 Samuel 1–4", "Eu era sacerdote em Siló.", "Achei que uma mulher estava embriagada, mas ela orava.", "Criei um menino no templo.", "Meus filhos foram maus, e morri caindo da cadeira.", 1],
  ["jesse", "Jessé", "1 Samuel 16", "Moro em Belém.", "Tenho oito filhos.", "Nem lembrei de chamar o mais novo, que cuidava das ovelhas.", "Fui o pai de Davi.", 1],
  ["mical", "Mical", "1 Samuel 18–19", "Eu era filha de um rei.", "Me apaixonei por um jovem guerreiro.", "Ajudei-o a fugir pela janela quando meu pai quis matá-lo.", "Fui esposa de Davi.", 1],
  ["abigail", "Abigail", "1 Samuel 25", "Eu era inteligente e bonita.", "Meu marido, Nabal, era rude e tolo.", "Levei pães, vinho e ovelhas a Davi.", "Evitei um derramamento de sangue e depois casei com Davi.", 2],
  ["joabe", "Joabe", "2 Samuel 2–20", "Eu comandava um exército.", "Era sobrinho do rei.", "Matei Abner e Absalão.", "Fui o general de Davi.", 1],
  ["nata", "Natã", "2 Samuel 12", "Fui profeta na corte do rei.", "Contei uma parábola sobre uma ovelhinha.", "O rei se indignou com o homem da história.", "Disse a Davi: Tu és o homem!", 1],
  ["urias", "Urias, o heteu", "2 Samuel 11", "Eu era soldado fiel.", "Não quis ir para casa enquanto meus companheiros estavam no campo de batalha.", "Levei uma carta que era a minha própria sentença.", "Fui marido de Bate-Seba.", 2],
  ["rainha-seba", "Rainha de Sebá", "1 Reis 10", "Eu era rainha de uma terra distante.", "Viajei com camelos carregados de especiarias e ouro.", "Fiz perguntas difíceis a um rei famoso.", "Fiquei admirada com a sabedoria de Salomão.", 2],
  ["roboao", "Roboão", "1 Reis 12", "Eu era filho de um rei muito sábio.", "Ouvi o conselho dos jovens em vez dos anciãos.", "Disse que o meu dedo mínimo era mais grosso que a cintura do meu pai.", "Meu reino se dividiu em dois.", 2],
  ["jeroboao", "Jeroboão", "1 Reis 12", "Fui oficial de Salomão.", "Dez tribos me escolheram como rei.", "Fiz dois bezerros de ouro e os coloquei em Betel e Dã.", "Fui o primeiro rei do reino do norte.", 2],
  ["nabote", "Nabote", "1 Reis 21", "Eu tinha uma vinha ao lado do palácio.", "Não quis vendê-la, pois era herança dos meus pais.", "Fui acusado falsamente por duas testemunhas.", "Fui morto por ordem da rainha Jezabel.", 2],
  ["giezi", "Giezi", "2 Reis 5:20-27", "Eu era servo de um grande profeta.", "Corri atrás de um general curado.", "Pedi talentos de prata e roupas a ele, escondido do meu senhor.", "Fiquei com a lepra que era do general.", 2],
  ["ezequias", "Ezequias", "2 Reis 18–20", "Fui rei de Judá.", "Orei com uma carta aberta diante do Senhor.", "Deus acrescentou quinze anos à minha vida.", "Fiz um túnel para levar água a Jerusalém.", 1],
  ["josias", "Josias", "2 Reis 22–23", "Comecei a reinar com 8 anos de idade.", "Mandei reformar o templo.", "O sumo sacerdote achou o Livro da Lei.", "Rasguei as minhas vestes e fiz um grande avivamento.", 1],
  ["hulda", "Hulda", "2 Reis 22:14-20", "Eu era profetisa em Jerusalém.", "Moro no segundo bairro da cidade.", "O rei me mandou consultar.", "Confirmei o que o Livro da Lei dizia.", 2],
  ["oseias", "Oseias", "Oseias 1–3", "Deus me mandou casar com uma mulher infiel.", "Meu casamento mostrava o amor de Deus por um povo infiel.", "Tive filhos com nomes simbólicos.", "Minha esposa se chamava Gômer.", 2],
  ["joel", "Joel", "Joel 2", "Falei de uma praga de gafanhotos.", "Pedi ao povo que rasgasse o coração e não as roupas.", "Profetizei que Deus derramaria o Espírito sobre toda carne.", "Pedro citou minhas palavras no Pentecostes.", 3],
  ["amos", "Amós", "Amós 1; 7", "Eu era pastor de ovelhas e cuidava de sicômoros.", "Não era filho de profeta.", "Falei sobre injustiça com os pobres.", "Disse: Corra o juízo como as águas.", 2],
  ["obadias", "Obadias", "Obadias", "Meu livro é o menor do Antigo Testamento.", "Falei contra uma nação vizinha.", "Edom foi o alvo da minha profecia.", "Escrevi apenas um capítulo.", 3],
  ["miqueias", "Miqueias", "Miqueias 5; 6", "Fui profeta no tempo de Isaías.", "Profetizei sobre um lugar pequeno.", "Disse onde nasceria o governador de Israel: Belém.", "Escrevi: que pratiques a justiça e andes humildemente com o teu Deus.", 3],
  ["naum", "Naum", "Naum 1–3", "Fui profeta de Deus.", "Falei sobre uma cidade grande, antes poupada.", "Meu livro é o oposto do de Jonas.", "Anunciei a queda de Nínive.", 3],
  ["habacuque", "Habacuque", "Habacuque 1–3", "Fui profeta e fiz perguntas difíceis a Deus.", "Perguntei: até quando, Senhor?", "Ouvi que o justo viverá pela sua fé.", "Mesmo sem figos nem rebanhos, decidi me alegrar no Senhor.", 3],
  ["sofonias", "Sofonias", "Sofonias 1–3", "Fui profeta no tempo do rei Josias.", "Falei do grande dia do Senhor.", "Disse que o Senhor se alegraria com o seu povo com cânticos.", "Sou o profeta do livro anterior a Ageu.", 3],
  ["ageu", "Ageu", "Ageu 1–2", "Fui profeta depois do exílio.", "Disse ao povo: Considerai os vossos caminhos.", "O povo morava em casas boas, mas o templo estava em ruínas.", "Incentivei a reconstrução do templo.", 3],
  ["zacarias-profeta", "Zacarias, o profeta", "Zacarias 4; 9", "Tive visões de candeeiros e oliveiras.", "Fui profeta depois do exílio.", "Disse: Não por força nem por poder, mas pelo meu Espírito.", "Profetizei o Rei que viria montado num jumentinho.", 3],
  ["malaquias", "Malaquias", "Malaquias 3–4", "Fui o último profeta do Antigo Testamento.", "Falei sobre os dízimos.", "Meu nome significa meu mensageiro.", "Anunciei que Elias viria antes do grande dia do Senhor.", 2],
  ["zorobabel", "Zorobabel", "Esdras 3; Ageu 2", "Eu era governador de Judá depois do exílio.", "Descendia de Davi.", "Voltei da Babilônia com um grupo de exilados.", "Liderei a reconstrução do templo.", 2],
  ["esdras", "Esdras", "Esdras 7; Neemias 8", "Eu era sacerdote e escriba.", "Voltei da Babilônia com um grupo de pessoas.", "Dediquei o coração a estudar a Lei do Senhor.", "Li o Livro da Lei ao povo em Jerusalém.", 1],
  ["neemias", "Neemias", "Neemias 1–6", "Eu era copeiro do rei da Pérsia.", "Chorei ao saber que os muros da minha cidade estavam derrubados.", "Pedi licença ao rei para voltar.", "Reconstruí os muros de Jerusalém em 52 dias.", 1],
  ["hama", "Hamã", "Ester 3–7", "Eu era um alto oficial do rei persa.", "Odiava um homem que não se curvava diante de mim.", "Tramei a destruição de todos os judeus.", "Acabei na forca que preparei para outro.", 2],
  ["assuero", "Assuero (Xerxes)", "Ester 1–8", "Governei 127 províncias.", "Dei um grande banquete e depus a minha rainha.", "Escolhi uma jovem judia como nova rainha.", "Meu nome também é conhecido como Xerxes.", 2],
  ["vasti", "Vasti", "Ester 1", "Fui rainha da Pérsia.", "Dava um banquete para as mulheres enquanto o rei dava um para os homens.", "Recusei vir à presença do rei quando ele me chamou.", "Fui deposta e substituída por Ester.", 2],
  ["belsazar", "Belsazar", "Daniel 5", "Eu era rei da Babilônia.", "Dei um grande banquete com taças do templo.", "Uma mão escreveu na parede.", "Naquela mesma noite, meu reino foi tomado.", 2],
  ["dario", "Dario, o medo", "Daniel 6", "Fui rei depois da queda da Babilônia.", "Assinei um decreto sem perceber a armadilha.", "Fiquei triste, sem dormir, quando meu conselheiro foi lançado aos leões.", "De manhã, vi Daniel vivo.", 2],
  ["ciro", "Ciro", "Esdras 1", "Fui rei da Pérsia.", "Isaías falou de mim pelo nome muito antes.", "Deus moveu o meu coração.", "Permiti que os judeus voltassem a Jerusalém para reconstruir o templo.", 2],
  ["hirao", "Hirão", "1 Reis 5", "Eu era rei de Tiro.", "Fui amigo de um rei de Israel, pai de outro.", "Enviei cedros do Líbano.", "Ajudei Salomão a construir o templo.", 3],
  ["fineias", "Fineias", "Números 25", "Sou neto de Arão.", "Zelei pela honra de Deus no meio do povo.", "Fiquei conhecido por agir com rapidez com uma lança.", "Recebi de Deus uma aliança de paz e sacerdócio.", 3],
  ["obede", "Obede", "Rute 4", "Sou filho de Rute e Boaz.", "Minha avó se chamava Noemi.", "Sou o pai de Jessé.", "Fui avô do rei Davi.", 3],
  ["elcana", "Elcana", "1 Samuel 1", "Eu tinha duas esposas.", "Subia todos os anos a Siló para adorar.", "Amava muito uma delas, que não tinha filhos.", "Sou o pai do profeta Samuel.", 3],
  ["ananias-damasco", "Ananias de Damasco", "Atos 9:10-17", "Eu era discípulo em Damasco.", "O Senhor me chamou numa visão.", "Fiquei com medo, pois o homem tinha perseguido os crentes.", "Orei por Saulo, e ele recuperou a visão.", 2],
  ["safira", "Safira", "Atos 5:1-11", "Meu marido e eu vendemos um terreno.", "Combinamos guardar parte do dinheiro para nós.", "Dissemos que entregamos tudo.", "Eu e Ananias mentimos ao Espírito Santo.", 2],
  ["dorcas", "Dorcas (Tabita)", "Atos 9:36-42", "Eu morava em Jope.", "Fazia muitas boas obras.", "Fazia túnicas e vestes para os pobres.", "Pedro orou, e fui ressuscitada.", 2],
  ["eutico", "Êutico", "Atos 20:7-12", "Eu era jovem em Trôade.", "Sentei na janela durante um longo discurso.", "Adormeci e caí do terceiro andar.", "Paulo me abraçou e fui restaurado.", 2],
  ["lidia", "Lídia", "Atos 16:13-15", "Eu era comerciante.", "Vendia tecidos de púrpura.", "Fiquei ouvindo Paulo junto a um rio em Filipos.", "Fui a primeira a se converter na Europa e abri minha casa para os missionários.", 2],
  ["barnabe", "Barnabé", "Atos 4; 11; 13", "Meu nome significa filho da consolação.", "Vendi um campo e entreguei o dinheiro aos apóstolos.", "Apresentei Paulo aos outros discípulos.", "Fui companheiro de Paulo na primeira viagem missionária.", 2],
  ["silas", "Silas", "Atos 15–16", "Fui um líder da igreja em Jerusalém.", "Acompanhei Paulo na segunda viagem.", "Fui açoitado e preso em Filipos.", "Cantei louvores à meia-noite na prisão, até o terremoto.", 2],
  ["marcos", "João Marcos", "Atos 12–15; 2 Timóteo 4:11", "Minha mãe tinha uma casa onde se reuniam em oração.", "Fui com Paulo e Barnabé, mas voltei no meio da viagem.", "Paulo e Barnabé discordaram sobre mim.", "Escrevi um Evangelho.", 2],
  ["tito", "Tito", "Tito 1", "Eu era grego.", "Não fui obrigado a ser circuncidado.", "Paulo me deixou em Creta.", "Paulo me escreveu uma carta pastoral.", 2],
  ["lucas", "Lucas", "Colossenses 4:14; Atos 1:1", "Eu era médico.", "Viajei com Paulo.", "Escrevi para alguém chamado Teófilo.", "Escrevi o terceiro Evangelho e o livro de Atos.", 2],
  ["aquila-priscila", "Áquila e Priscila", "Atos 18", "Somos um casal que fazia tendas.", "Fomos expulsos de Roma.", "Hospedamos Paulo em Corinto.", "Ensinamos melhor o caminho a Apolo.", 2],
  ["apolo", "Apolo", "Atos 18:24-28", "Eu era de Alexandria.", "Era eloquente e conhecia bem as Escrituras.", "Conhecia só o batismo de João.", "Um casal me explicou melhor o caminho.", 2],
  ["cornelio", "Cornélio", "Atos 10", "Eu era centurião romano em Cesareia.", "Orava a Deus e dava esmolas.", "Um anjo me disse para chamar um homem chamado Simão Pedro.", "Fui um dos primeiros gentios a receber o Espírito Santo.", 2],
  ["agripa", "Rei Agripa", "Atos 26", "Fui um rei que ouviu a defesa de um prisioneiro.", "Sabia das coisas sobre os profetas.", "Disse: Por pouco me persuades a me tornar cristão.", "Ouvi Paulo falar.", 2],
  ["felix", "Félix", "Atos 24", "Fui governador romano.", "Minha esposa se chamava Drusila.", "Tive medo quando Paulo falou de justiça e juízo.", "Deixei Paulo preso na esperança de receber suborno.", 2],
  ["onesimo", "Onésimo", "Filemom", "Eu era escravo e fugi.", "Encontrei Paulo preso.", "Me tornei cristão.", "Paulo me mandou de volta ao meu senhor Filemom com uma carta.", 2],
  ["filemom", "Filemom", "Filemom", "Eu era um cristão e minha casa era usada para reunir a igreja.", "Paulo me chamou de amado colaborador.", "Um escravo meu havia fugido.", "Paulo me pediu para receber Onésimo como irmão.", 2],
  ["eunice", "Eunice", "2 Timóteo 1:5", "Eu era judia convertida.", "Minha mãe se chamava Loide.", "Minha fé era sincera.", "Fui mãe de Timóteo.", 3],
  ["demas", "Demas", "2 Timóteo 4:10", "Fui companheiro de Paulo na prisão.", "Paulo me chamou de colaborador.", "O amor pelo mundo me enganou.", "Paulo disse que Demas me desamparou.", 3],
  ["tiago-irmao", "Tiago, irmão de Jesus", "Atos 15; Tiago 1", "Eu era irmão de Jesus pela família.", "No começo, não cria nele.", "Tornei-me líder da igreja em Jerusalém.", "Escrevi uma carta que diz que a fé sem obras é morta.", 2],
  ["tiago-zebedeu", "Tiago, filho de Zebedeu", "Marcos 1:19; Atos 12:2", "Eu era pescador.", "Tinha um irmão chamado João.", "Jesus nos apelidou de filhos do trovão.", "Fui o primeiro apóstolo martirizado.", 2],
  ["filipe-apostolo", "Filipe, o apóstolo", "João 1:43-46; 6:5-7", "Eu era de Betsaida.", "Disse a um amigo: Vem e vê.", "Fiquei calculando como alimentar uma grande multidão.", "Jesus me perguntou onde comprar pão para tantos.", 2],
  ["natanael", "Natanael (Bartolomeu)", "João 1:45-49", "Me perguntaram se de Nazaré podia sair algo bom.", "Estava debaixo de uma figueira.", "Jesus me chamou de verdadeiro israelita, sem dolo.", "Fui um dos doze apóstolos.", 2],
  ["simao-zelote", "Simão, o zelote", "Lucas 6:15", "Fui um dos doze discípulos.", "Meu apelido está ligado a um grupo político.", "Tinha o mesmo nome de Pedro.", "Era chamado de o zelote.", 3],
  ["matias", "Matias", "Atos 1:15-26", "Acompanhei Jesus desde o batismo.", "Fui testemunha da ressurreição.", "Os apóstolos lançaram sortes.", "Tomei o lugar de Judas entre os doze.", 2],
  ["simeao", "Simeão", "Lucas 2:25-35", "Eu era um homem justo e piedoso.", "O Espírito Santo me havia revelado que eu não morreria sem ver algo.", "Peguei um bebê nos braços no templo.", "Disse: Agora, Senhor, podes despedir em paz o teu servo.", 2],
  ["ana-profetisa", "Ana, a profetisa", "Lucas 2:36-38", "Eu era viúva de 84 anos.", "Não saía do templo, servindo com jejuns e orações.", "Vi uma criança no templo.", "Falei de Jesus a todos que esperavam a redenção.", 2],
  ["zacarias-pai", "Zacarias, pai de João", "Lucas 1:5-25", "Eu era sacerdote.", "Meu serviço era queimar incenso no templo.", "Um anjo apareceu e não acreditei.", "Fiquei mudo até meu filho nascer.", 2],
  ["isabel", "Isabel", "Lucas 1", "Eu era estéril e já idosa.", "Meu marido era sacerdote.", "Minha parente me visitou, e o bebê saltou no meu ventre.", "Fui a mãe de João Batista.", 2],
  ["joana", "Joana", "Lucas 8:1-3", "Meu marido era administrador de Herodes.", "Fui curada por Jesus.", "Ajudava com meus bens a sustentar o grupo que seguia Jesus.", "Estive entre as mulheres que viram o túmulo vazio.", 3],
  ["viuva-sarepta", "A viúva de Sarepta", "1 Reis 17", "Eu morava na terra de Sidom.", "Estava colhendo gravetos quando um homem me pediu água e pão.", "Só tinha um pouco de farinha e azeite.", "Nunca faltou farinha nem azeite, e o profeta Elias ficou em minha casa.", 2],
  ["sunamita", "A mulher sunamita", "2 Reis 4", "Eu construí um quarto no andar de cima.", "Recebia um profeta na minha casa.", "Meu filho adoeceu e morreu.", "Eliseu me devolveu o meu filho vivo.", 3],
  ["samaritana", "A mulher samaritana", "João 4", "Fui buscar água ao meio-dia.", "Um judeu me pediu de beber, o que era incomum.", "Ele me falou sobre água viva.", "Corri para a cidade dizendo: Vinde ver um homem que me disse tudo.", 2],
  ["viuva-pobre", "A viúva pobre", "Marcos 12:41-44", "Eu estava no templo.", "Eu era muito pobre.", "Coloquei duas moedinhas na oferta.", "Jesus disse que eu dei mais do que todos.", 2],
  ["centuriao-cafarnaum", "O centurião de Cafarnaum", "Mateus 8:5-13", "Eu era um oficial romano.", "Meu servo estava doente.", "Disse: Senhor, não sou digno de que entres na minha casa.", "Jesus se admirou da minha fé e curou meu servo à distância.", 2],
  ["filho-prodigo", "O filho pródigo", "Lucas 15:11-32", "Pedi a minha parte da herança.", "Gastei tudo numa terra distante.", "Fui cuidar de porcos e quis comer o que eles comiam.", "Voltei para casa, e meu pai me recebeu com festa.", 2],
  ["bom-samaritano", "O bom samaritano", "Lucas 10:25-37", "Eu estava viajando de Jerusalém a Jericó.", "Encontrei um homem ferido na estrada.", "Um sacerdote e um levita haviam passado de largo.", "Cuidei do ferido e paguei a hospedaria.", 2],
  ["mae-zebedeu", "A mãe dos filhos de Zebedeu", "Mateus 20:20-21", "Eu estava entre as mulheres que seguiam Jesus.", "Pedi algo especial para meus filhos.", "Meus filhos eram pescadores.", "Pedi que meus filhos se sentassem à direita e à esquerda de Jesus no reino.", 3],
  ["cleopas", "Cleopas", "Lucas 24:13-35", "Eu caminhava para Emaús.", "Um estranho se juntou a nós na estrada.", "Nosso coração ardia quando ele nos explicava as Escrituras.", "Reconheci Jesus ressuscitado ao partir o pão.", 3],

  // ------------------------------------------------------------------ difícil
  ["sem", "Sem", "Gênesis 9–11", "Sou filho de Noé.", "Estava na arca.", "Cobri meu pai com uma capa, sem olhar.", "Dos meus descendentes veio Abraão.", 3],
  ["jafe", "Jafé", "Gênesis 9–10", "Sou filho de Noé.", "Estive na arca.", "Cobri meu pai com uma capa.", "Meus descendentes se espalharam pelas ilhas.", 3],
  ["cao", "Cão", "Gênesis 9:20-25", "Sou um dos três filhos de Noé.", "Vi meu pai numa situação constrangedora.", "Contei aos meus irmãos em vez de cobrir meu pai.", "Meu filho Canaã foi amaldiçoado.", 3],
  ["tera", "Terá", "Gênesis 11:26-32", "Eu tinha três filhos: Abrão, Naor e Harã.", "Saí de Ur dos caldeus.", "Fui até Harã e fiquei por lá.", "Sou o pai de Abraão.", 3],
  ["abimeleque", "Abimeleque", "Gênesis 20; 26", "Fui rei de Gerar.", "Levei uma mulher bonita para o meu palácio, achando que era solteira.", "Deus me avisou em sonho.", "Fui enganado pela mentira de Abraão sobre sua esposa.", 3],
  ["melquisedeque", "Melquisedeque", "Gênesis 14; Hebreus 7", "Fui rei de Salém.", "Fui também sacerdote do Deus Altíssimo.", "Levei pão e vinho a Abrão.", "Abrão me deu o dízimo de tudo.", 3],
  ["dina", "Dina", "Gênesis 34", "Sou filha de Jacó.", "Tenho vários irmãos.", "Fui ver as mulheres da terra de Siquém.", "Meus irmãos Simeão e Levi me vingaram.", 3],
  ["asenate", "Asenate", "Gênesis 41:45", "Fui dada em casamento a um homem poderoso do Egito.", "Meu pai era sacerdote de On.", "Meu marido recebeu um novo nome egípcio do faraó.", "Fui a esposa de José e mãe de Efraim e Manassés.", 3],
  ["efraim", "Efraim", "Gênesis 48", "Sou filho de José.", "Nasci no Egito.", "Meu avô cruzou os braços ao me abençoar.", "Recebi a bênção da mão direita, mesmo sendo o mais novo.", 3],
  ["manasses", "Manassés", "Gênesis 41:51", "Sou filho de José com uma egípcia.", "Meu nome significa fazer esquecer.", "Meu irmão mais novo recebeu a bênção principal.", "Sou o primogênito de José.", 3],
  ["sifra-pua", "Sifrá e Puá", "Êxodo 1:15-21", "Éramos parteiras.", "O faraó mandou que matássemos os meninos hebreus.", "Tememos a Deus.", "Salvamos os bebês e mentimos ao faraó.", 3],
  ["bezalel", "Bezalel", "Êxodo 31:1-5", "Fui enchido do Espírito de Deus.", "Tinha sabedoria e habilidade para trabalhar em ouro, prata e bronze.", "Fui escolhido pelo nome.", "Fiz o tabernáculo e a arca da aliança com Aoliabe.", 3],
  ["nadabe-abiu", "Nadabe e Abiú", "Levítico 10:1-2", "Somos filhos de Arão.", "Éramos sacerdotes.", "Oferecemos fogo estranho ao Senhor.", "Fomos consumidos pelo fogo diante de Deus.", 3],
  ["cora", "Corá", "Números 16", "Fui levita.", "Me rebelei contra Moisés e Arão.", "Levei 250 líderes comigo.", "A terra se abriu e nos engoliu.", 3],
  ["ogue", "Ogue, rei de Basã", "Deuteronômio 3", "Fui rei de Basã.", "Era um dos últimos gigantes.", "Minha cama era de ferro e tinha cerca de quatro metros.", "Fui derrotado por Moisés.", 3],
  ["otoniel", "Otniel", "Juízes 3:7-11", "Sou sobrinho de Calebe.", "Casei com a filha dele depois de tomar uma cidade.", "Fui o primeiro juiz de Israel.", "Derrotei o rei da Mesopotâmia.", 3],
  ["eude", "Eúde", "Juízes 3:12-30", "Fui juiz de Israel.", "Eu era canhoto.", "Levei um presente ao rei de Moabe, com uma surpresa escondida.", "Libertei Israel de um rei muito gordo.", 3],
  ["abimeleque-gideao", "Abimeleque, filho de Gideão", "Juízes 9", "Meu pai foi um grande juiz.", "Matei setenta dos meus irmãos para me tornar rei.", "Uma mulher atirou uma pedra de moinho do alto de uma torre.", "Morri em Tebes.", 3],
  ["manoa", "Manoá", "Juízes 13", "Minha esposa não tinha filhos.", "Um anjo apareceu a ela e a mim.", "Orei para saber como criar o menino.", "Sou o pai de Sansão.", 3],
  ["hofni-fineias", "Hofni e Finéias", "1 Samuel 2–4", "Somos filhos de um sacerdote.", "Fomos maus e desonramos as ofertas.", "Levamos a arca para a batalha.", "Morremos no mesmo dia, e nosso pai Eli caiu da cadeira.", 3],
  ["nabal", "Nabal", "1 Samuel 25", "Eu era muito rico, tinha ovelhas e cabras.", "Era rude e mau.", "Recusei ajudar os homens de Davi.", "Meu nome significa tolo e morri de um mal súbito.", 3],
  ["abner", "Abner", "1 Samuel 14; 2 Samuel 3", "Fui general do primeiro rei de Israel.", "Meu primo era o rei.", "Depois mudei de lado para apoiar o sucessor.", "Joabe me matou.", 3],
  ["mefibosete", "Mefibosete", "2 Samuel 4; 9", "Sou filho de Jônatas.", "Fiquei manco aos cinco anos, quando minha ama me deixou cair.", "Davi me chamou para comer à mesa do rei.", "Sou neto de Saul.", 3],
  ["husai", "Husai", "2 Samuel 15–17", "Fui amigo de um rei.", "Fingi apoiar o filho do rei.", "Dei um conselho para atrasar o exército.", "Salvei Davi de Absalão.", 3],
  ["adonias", "Adonias", "1 Reis 1", "Sou filho de Davi.", "Tentei me proclamar rei quando meu pai estava idoso.", "Me refugiei no altar quando meu irmão foi coroado.", "Perdi a vida por tentar o trono.", 3],
  ["zadoque", "Zadoque", "1 Reis 1:32-39", "Fui sacerdote no tempo do rei Davi.", "Fiquei fiel a ele quando seu filho tentou o trono.", "Ungi um rei com um chifre de azeite.", "Ungi Salomão.", 3],
  ["obadias-mordomo", "Obadias, o mordomo", "1 Reis 18:3-16", "Eu era administrador do palácio de Acabe.", "Temia ao Senhor.", "Escondi cem profetas em cavernas.", "Fui o homem que encontrou Elias, para avisar o rei.", 3],
  ["jeu", "Jeú", "2 Reis 9–10", "Fui ungido rei sobre Israel.", "Dirigia meu carro como um louco.", "Mandei jogar pela janela uma rainha má.", "Destruí a família de Acabe e o culto a Baal.", 3],
  ["joas", "Joás, o menino rei", "2 Reis 11–12", "Fui escondido no templo por seis anos.", "Minha tia me salvou de uma avó assassina.", "Comecei a reinar com sete anos de idade.", "Mandei consertar o templo.", 3],
  ["atalia", "Atalia", "2 Reis 11", "Fui rainha de Judá.", "Mandei matar a descendência real.", "Um bebê foi escondido de mim.", "Fui a única mulher a reinar em Judá.", 3],
  ["uzias", "Uzias", "2 Crônicas 26", "Fui rei de Judá desde jovem.", "Prosperei enquanto buscava ao Senhor.", "Quis queimar incenso, o que era dever dos sacerdotes.", "Fiquei leproso até o dia da morte.", 3],
  ["manasses-rei", "Manassés, rei de Judá", "2 Crônicas 33", "Comecei a reinar com doze anos.", "Fiz mais mal que as nações que Deus expulsou.", "Fui levado preso para Babilônia.", "Me humilhei, e Deus me trouxe de volta a Jerusalém.", 3],
  ["gomer", "Gômer", "Oseias 1", "Fui esposa de um profeta.", "Fui infiel.", "Tive filhos com nomes simbólicos.", "Meu marido me buscou de volta.", 3],
  ["artaxerxes", "Artaxerxes", "Neemias 2", "Fui rei da Pérsia.", "Meu copeiro ficou triste na minha presença.", "Perguntei: Que me pedes?", "Dei licença a Neemias para reconstruir os muros.", 3],
  ["sambala", "Sambalate", "Neemias 4; 6", "Eu era governador de Samaria.", "Ridicularizei os trabalhadores.", "Tramei contra um grande construtor.", "Zombei dos que reconstruíam os muros de Jerusalém.", 3],
  ["elifaz", "Elifaz", "Jó 4–5", "Sou de Temã.", "Fui o primeiro a falar com meu amigo sofredor.", "Disse que ninguém inocente jamais perecera.", "Sou um dos três amigos de Jó.", 3],
  ["eliu", "Eliú", "Jó 32–37", "Eu era mais jovem que os outros.", "Fiquei esperando para falar.", "Me irei contra Jó e contra os três amigos.", "Falei antes de Deus responder do redemoinho.", 3],
  ["epafrodito", "Epafrodito", "Filipenses 2:25-30", "Fui enviado pela igreja de Filipos.", "Levei uma oferta ao apóstolo preso.", "Quase morri de doença.", "Paulo me chamou de irmão, cooperador e companheiro de luta.", 3],
  ["tiquico", "Tíquico", "Efésios 6:21", "Fui companheiro de Paulo.", "Levei cartas a várias igrejas.", "Paulo me chamou de irmão amado e fiel ministro.", "Entreguei a carta aos Efésios.", 3],
  ["gaio", "Gaio", "3 João 1", "Sou um cristão amado.", "O apóstolo disse que andava na verdade.", "Eu recebia irmãos viajantes em minha casa.", "Recebi uma das cartas de João.", 3],
  ["diotrefes", "Diótrefes", "3 João 9", "Gostava de ser o primeiro.", "Não recebia os irmãos.", "Falava mal dos apóstolos.", "Era arrogante e queria mandar na igreja.", 3],
  ["herodias", "Herodias", "Marcos 6:17-28", "Eu era esposa de um rei, mas antes fora esposa do irmão dele.", "Tinha rancor de um profeta.", "Minha filha dançou num banquete.", "Pedi a cabeça de João Batista.", 2],
  ["filha-herodias", "A filha de Herodias", "Marcos 6:22", "Dancei num banquete de aniversário.", "O rei prometeu me dar o que eu pedisse.", "Consultei minha mãe.", "Pedi a cabeça de João Batista numa bandeja.", 3],
  ["caifas", "Caifás", "Mateus 26:57-66", "Fui sumo sacerdote.", "Disse que era melhor que um homem morresse pelo povo.", "Rasguei as minhas vestes.", "Presidi o julgamento de Jesus.", 2],
  ["gamaliel", "Gamaliel", "Atos 5:34-39; 22:3", "Eu era um fariseu respeitado.", "Fui doutor da lei.", "Aconselhei o conselho a deixar os apóstolos.", "Fui mestre de Paulo.", 2],
  ["simao-mago", "Simão, o mago", "Atos 8:9-24", "Eu fazia magia em Samaria.", "Todos me admiravam.", "Fui batizado, mas quis comprar um dom com dinheiro.", "Pedro me repreendeu duramente.", 2],
  ["filipe-evangelista", "Filipe, o evangelista", "Atos 8:26-40", "Fui um dos sete escolhidos para servir.", "Anunciei Jesus em Samaria.", "Um anjo me mandou para o caminho do deserto.", "Batizei o eunuco etíope.", 2],
  ["eunuco-etiope", "O eunuco etíope", "Atos 8:26-40", "Eu era oficial da rainha da Etiópia.", "Voltava de Jerusalém, lendo Isaías no carro.", "Perguntei de quem o profeta falava.", "Fui batizado por Filipe.", 2],
  ["festo", "Festo", "Atos 25", "Fui governador romano.", "Sucedi a Félix.", "Ouvi o apelo de um preso a César.", "Disse a Paulo: Para César irás.", 3],
  ["loide", "Loide", "2 Timóteo 1:5", "Fui avó de um jovem pastor.", "Minha fé era sincera.", "Minha filha também creu.", "Sou a avó de Timóteo.", 3],
  ["julio", "Júlio, o centurião", "Atos 27", "Eu era centurião da corte imperial.", "Fui responsável por levar prisioneiros a Roma.", "Tratei Paulo com humanidade.", "Não deixei que os soldados matassem os presos durante o naufrágio.", 3],
  ["trifena-trifosa", "Trifena e Trifosa", "Romanos 16:12", "Somos duas mulheres.", "Paulo nos saudou em Roma.", "Trabalhávamos no Senhor.", "Paulo nos citou como as que se afadigam na obra do Senhor.", 3],
  ["febe", "Febe", "Romanos 16:1-2", "Eu era serva da igreja de Cencreia.", "Paulo me recomendou muito.", "Ajudei muitos, inclusive o apóstolo.", "Levei a carta de Paulo aos Romanos.", 3],
  ["oneziforo", "Onesíforo", "2 Timóteo 1:16-18", "Fui um amigo de Paulo.", "Procurei o apóstolo em Roma com diligência.", "Não me envergonhei das correntes dele.", "Várias vezes refrigerei o ânimo do apóstolo.", 3],
];

export const WHO_EXTRA: WhoItem[] = ROWS.map(([key, name, ref, h1, h2, h3, h4, d]) => ({ key, name, ref, hints: [h1, h2, h3, h4], d }));
